### ISSUE TITLE
24/7 having difficulty triggering Posted Bounty

### ISSUE THREAD

**Issue by spoonfunk** [mtgred/netrunner#1043]
Using 24/7 and then selecting posted bounty for use leads to the prompt getting stuck on the menu to choose whether or not to forfiet posted bounty.

Sometimes clicking on it, it will stay on the prompt but give the tag and the Bad pub...it also sometimes causes other wierd glitches

For instance 
1)used 24/7 and selected the agenda to forfiet to it
2) selected posted bounty
3) clicked yes to forfeit posted bounty (the menu then gets "stuck" at this point) 
4) the tag and bad pub are given (menu still stuck)
5) used scorch earth, target prevents 4 meat
6) used scorch earth again (for the kill) and the plastcrete somehow auto prevented

**Comment by JoelCFC25** [comment]
Thanks for the report. This is going to be tricky. In order to get the 2 tags from Breaking News to stick at the end of the Corp's turn (very frequently requested), we ended up having to do something fairly crude. You're not actually resolving the "when scored" ability of the card you target with 24/7, but rather an imposter--basically the target's card definition with any `:end-turn` stuff stripped away. 

In the case of Posted Bounty here, it's generating an NPE on the attempt to forfeit itself because the thing resolving is not _actually_ the card in the Corp score area.

**Comment by nealterrell** [comment]
@JoelCFC25, I think this can be fixed easily by changing the `card` in the second `resolve-ability` to `target`. We want the target agenda's ability to be resolved on the target, not on 24/7 News Cycle (which is what `card` refers to in that context). I'll try a fix.
