### ISSUE TITLE
Enhancement request.  Default core sets in deck builder

### ISSUE THREAD

**Issue by AlvazHall** [mtgred/netrunner#1096]
Much like we have the championship decks to start with, it would be nice, especially for the new players, to start with all the core sets.  I believe even the pro's would like to play some OG games every once and a while.

I know we can build them ourselves but its kind of a pain in the ass if you are new to the site/game and don't know all the tricks to finding deck lists online.

**Comment by zaroth** [comment]
To be honest, if we were to implement such an idea, I'd prefer to NOT include the pure faction coreset decks, but rather decks specifically tailored to teaching beginners (as this is the audience we're catering to here). As discussed [here](https://www.reddit.com/r/Netrunner/comments/40a6lk/are_ffg_core_decklists_available_for_jintekinet/), Oniya's deck from NetrunnerDB are a good start.

**Comment by zaroth** [comment]
Also, to anyone implementing this, probably the least intrusive way to do it would be to add a checkbox to the registration form, checked by default:

☑ Include default decklists

And then we could go wild with default decklists, while simultaneously not cluttering everyone's decks.

**Comment by JoelCFC25** [comment]
Bizarrely, the new AstroScript Pilot Program errata taking effect next week has now rendered it impossible to build a legal NBN deck using a single core set!

**Comment by sekoku** [comment]
@JoelCFC25: For the most part, I don't think most new players will honestly care about the MWL or being "tournament legal" when first starting so the MWL breaking NBN wouldn't be a huge issue there. IIRC the Worlds Decks that Jinteki includes already are MWL'd?

...Just checked. Kate's Casual due to Clone Chip and Jinteki is still valid. But using those as "teaching decks" seems counter-intuitive to me.

@zaroth: While I get what you're saying about using a community deck over Fantasy Flights "dump the neutrals in and just have fun!" I feel using one of the "dump the neutrals in" helps new players because 1) they buy only the core set and thereby don't have some of the expansion/datapacks that the "new player" netdecks seem to have (at least when I first started) and 2) most of the community seems to think that if players are going to go that route that Hass-Bioroid and Kate would be the best two decks to use for those purposes under FF's "rules/recommendations."

I know Jinteki was the one in an old (2013? 2014?) rulebook, but they updated the rulebook to not have a recommended deck. So, I'd ask on reddit/githubt/Jinteki/wherever in a survey for the playerbase to throw out decks or a "just use the FF decks, stupid/KISS" option in implementing them.

IMO, this should be implemented just to help newer players have a "standard" decks that the player-base knows/understands and can teach to players for those willing to teach. Like the Worlds, you can delete these and they're gone forever so I *doubt* they'd be clogging peoples deck-lists as an annoyance. But I feel strongly this is something the team should try to add (and it doesn't seem like it'd be an impossible task) to help new players not have to hunt something down and everyone would be on the same page for "power level/learning-without-stomping-them" purposes.

</long-winded>

**Comment by JoelCFC25** [comment]
Errata != MWL.  The AstroScript "limit 1 per deck" change is for all formats and settings, whereas MWL applies to competition only.

**Comment by sekoku** [comment]
Right. But I mean it's the same thing: I *highly* doubt most new players are gonna be worried about MWL/Errata and all that. They simply want to learn to play. But I mean, it'd be up to the community on what decks they'd want to use if not FF's "just dump the neutrals in and play" decks.

**Comment by sekoku** [comment]
Case in point, just today:

> revolverbloomSaturday Oct 29th - 18:48
> new to the game

> Erik TwiceSaturday Oct 29th - 18:49
> uuf that may take perhaps too long! But I can lend you a hand

> revolverbloomSaturday Oct 29th - 18:49
> how can we start a game?

> Erik TwiceSaturday Oct 29th - 18:49
> let me build a newbie deck

> Erik TwiceSaturday Oct 29th - 18:49
> and I'll give it a whirl

> revolverbloomSaturday Oct 29th - 18:49
> thanks man!

> Erik TwiceSaturday Oct 29th - 18:49
> hve you created your decks?

> revolverbloomSaturday Oct 29th - 18:49
> I guess I have a pre-built deck here?

After me joking about this sort of thing being a huge problem, @JoelCFC25 chimed in with:

> JoelCFC25Sunday Oct 30th - 14:25
> this is not something i have the ability to make happen. i recommend taking it up with @zaroth 

> JoelCFC25 Sunday Oct 30th - 14:26
> i quite strongly believe the site does not cater well at all to people who have not played in meat space at least a few times, though obviously there is no way to prevent people from doing it anyway.

> sekokuSunday Oct 30th - 14:28
> The problem with that is lack of players. We aren't Magic-sized, so when people say "well you can play it on Jinteki..." this is gonna attract new players. IMO something has to be done to help with that because assuming they have someone to play with in the physical space simply isn't there.

> JoelCFC25Sunday Oct 30th - 14:29
> i don't really agree, but will leave it at that. just my opinion
---

I mean I'm pushing for this BECAUSE the way to expand the game (IMO) is to make sure there is a way for players to play the game. A lot of the community has said that if it wasn't for Jinteki.net, they'd have probably dropped  the game a long time ago.

So conversely if people are interested in learning the game, and they have no Netrunner local "meta"/community to learn from: *How* can they learn? People tell them to play on Jinteki, and there are people out there (like me) that are willing to teach them. But then you ask them "well, do you have a deck ready?" They kinda "poker-face" and go ":| No? Uh, where can I get one?"

It's why I feel if there was a Core-only Starter Deck for Corp/Runner it'd solve the confusion of not having a deck available, everyone would be on the same page of having a teaching deck on-hand to help new players learn AND if these players pick-up/support the game for Fantasy Flight they'd get the Core-set anyway and maybe could then teach their <gender>friend or significant other or friends the game and make the game expand in their "meta" that way.

*shrug* But Joel's said Jinteki isn't really meant for beginners so I'm probably wasting my breath...

**Comment by JoelCFC25** [comment]
I will just state for the record since it was not clear from the paste job above:  my comments represented my **personal opinion** only--I don't speak on behalf of anyone else on the development team and no idea what the "official" position would be on how accommodating the site can/should be to newcomers to the game itself.

**Comment by sekoku** [comment]
Right. I didn't intend to make it out as an official statement or you as a bad guy or anything. It's just I'm not sure what the teams stance on trying to teach New Players is. From what I've seen, there are people out there that use Jinteki as a learning-to-play tool and thereby providing this would be a massive service. But if the official stance is "it's not worth our while" then I'll drop it.

**Comment by danhut** [comment]
I think this has been implemented by Neal and Joel for new Accounts?

**Comment by JoelCFC25** [comment]
Yep!
