### ISSUE TITLE
Turntable Turns off 24/7 News Cycle

### ISSUE THREAD

**Issue by ANRecho** [mtgred/netrunner#1125]
During recent games I have noticed that if turntable is used to swap an agenda out of the corp's score area, 24/7 news cycle is unable to target any agenda in the score area for the remainder of the game.

**Comment by JoelCFC25** [comment]
Thanks for the report. This is due to the gymnastics in the Turntable code where I attempted to get events and abilities hooked up to the Corp agenda newly swapped into the score area by Turntable (e.g., if the Corp gets a Gila Hands swapped back to them, it needs to subsequently be clickable to gain 3 credits for 2 clicks). 

For agendas like Breaking News that have no click abilities, it doesn't seem to be working, because I see the card data changes to `:abilities nil` in the game state after swapping a stolen Breaking News back to the Corp. 24/7 News Cycle needs something to be in `:abilities` in order to be able to target it.

Right now I have no idea what to do on this one...

**Comment by JoelCFC25** [comment]
I will have a partial fix for this soon. It still most likely won't work to target a specific card previously Turntabled back to you with 24/7, but cards you scored normally will no longer be rendered untargetable.

**Comment by JoelCFC25** [comment]
I'm going to close this for now, as it's been 95% fixed. As noted above, 24/7 will still not be able to target an agenda that was previously Turntabled to the Corp, but that can become it's own issue if someone ever manages to get in that situation.
