### ISSUE TITLE
Turntable allows you to switch news team for a real agenda

### ISSUE THREAD

**Issue by xyceres** [mtgred/netrunner#1152]
The card news team is not stolen but placed in the score area as an agenda but still triggers turntable.
Have yet to test notoriety, fan site, shi.kyu or excutives for the same issues.

**Comment by JoelCFC25** [comment]
Did you see this yourself firsthand? Any other cards in play that could have been pertinent? I cannot replicate this so far. Taking a News Team or Shi.Kyu or trashing a scoreable Executive all do a `move` and a `gain-agenda-point`, but none of these ever fire the `:agenda-stolen` event trigger, which is what Turntable listens for.

**Comment by xyceres** [comment]
I did see it if it helps it was noise vs sync there was two news teams in archives when the issue occurred. 
I'll see if I can reproduce when I get a chance.

**Comment by JoelCFC25** [comment]
Thanks for the info--I'll keep investigating.

**Comment by xyceres** [comment]
![turntablenewteam](https://cloud.githubusercontent.com/assets/13917038/12611606/b344eb06-c541-11e5-938f-72894f88cee7.png)

It's not easy to reproduce and it doesn't seem to work most of the time but i managed it at least once.

It doesn't bring up the message telling you you can turntable but clicking turntable still works and I believe these were the exact steps that cause it the first time (2 cyberdex and 2 newsteam in archives selecting both cyberdex first taking tags on first news team and taking 2nd as points to news team).

**Comment by JoelCFC25** [comment]
I have a theory now. Was it possible that the opponent had stolen an agenda earlier in the game with Turntable in play but either declined to swap for one of your agendas (or couldn't because you had none scored)? 

Basically Turntable is set up to have a single entry in its `:abilities` map, but that ability can't be activated unless a custom key exists in the card (`:swap true`). That key is set when an agenda steal occurs--but if the Runner chooses not to use it (or can't), the key is still there, allowing him to click Turntable essentially at any subsequent time. When it is clicked, Turntable will swap the last item in `[:runner :scored]` regardless of its type.  

So what I need to do is figure out how to dissociate `:swap true` if the Runner _doesn't_ immediately use Turntable after an agenda steal.

**Comment by JoelCFC25** [comment]
Progress update: I modified Turntable to not alert the Runner nor enable the ability activation if the Corp has no scored agendas--that part should stop an unused click ability of Turntable to linger on and potentially be used later when it shouldn't. I also required that the last item in `[:runner :scored]` be an Agenda in order for the swap procedure to proceed.

**Comment by xyceres** [comment]
I just tested your theory and it seems correct. Was able to swap a corp scored astro for my news team by stealing a QPM then placing a news team in score area and clicking turntable.

This does highlight another issue thou in that you can swap with turntable much later then you should be able to. I tested this by scoring another astro (agenda A) as runner the following up and scoring another agenda (agenda B) the turn after with corp and the runner could hit turntable to swap the A for B despite the fact  the window for A swaps with turntable was well and truely over and  the fact agenda B was scored after agenda A.

**Comment by JoelCFC25** [comment]
I can try adding an event handler for `:runner-spent-click` that will dissociate `:swap true` and see if that helps the situation.
