### ISSUE TITLE
Leela's ability will only work once if two agendas are stolen

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#1169]
I thought this was logged long ago but I couldn't find any record of it.

Anyway, probably pretty self-explanatory, but for completeness: If you multi-access and steal two agendas you will be told twice to click Leela to use her ability, but after you use it the first time it's no longer enabled. I've also tried firing Leela after the first steal but the dialogue box forces you to complete your accesses/steals first.

**Comment by JoelCFC25** [comment]
For me it's working, but admittedly not as well as it should because the access prompts get interleaved with Leela's targeting prompt. The key is to click Leela *immediately* after stealing the first agenda, but you won't get the prompt to target a card for bouncing to HQ until after the second steal occurs. I'll try adding `:priority true` and see if that helps.

**Comment by qmsm** [comment]
Priority true sounds like a winner then! Just for completeness, this is what I've just tested and as you say will work:

1. Access the agenda
2. Click 'Steal'
3. Prompt will ask you for next access, e.g. 'Card from hand'
4. Click Leela
5. Click 'Card from Hand'
6. You'll be asked which card you'd like to bounce, with target, as well as being told you're accessing another agenda
7. Click card to bounce
8. Click 'Steal' on second agenda
9. Repeat (if further access possible) or use Leela as normal

Interestingly (he says loosely) at step 4 you can click Leela as many times as you want, to bounce as many cards as you like. But that's probably cheating.
