### ISSUE TITLE
Deus X and multiple counts of net damage

### ISSUE THREAD

**Issue by PhantomOfAres** [mtgred/netrunner#1252]
While playing against Personal Evolution, if the runner has Deus X on the board, and accesses Fetal AI, the runner is presented with the option to prevent the first 2 net damage, from Fetal.  If the runner trashes Deus X, it prevents not only the damage from Fetal, but ALSO the damage from Personal Evolution.  This seems to happen with all amounts of net damage (ie multiple Komainu fires stacked up on one another.)  The only interaction I see it as a particular problem is Fetal + PE, since in other cases, it may behoove you to wait to prevent until the final one is fired, anyway.

**Comment by nealterrell** [comment]
Thanks for the report. This would require a rewrite of Film Critic, as that card is why Fetal AI technically is not accessed until the runner chooses to Steal, so the two damage events are happening in the same window rather than in two different windows. Until then, the `/take-net 1` command can help.
