### ISSUE TITLE
Cards in remote servers not rendering in Firefox (Arch Linux)

### ISSUE THREAD

**Issue by Eris-chan** [mtgred/netrunner#1263]
I've ran into this issue recently while trying to play on Jnet from my laptop-- any card in a remote server, be it asset, upgrade, or agenda, simply doesn't render on the Arch port of Firefox, *unless* there are multiple cards in the server.  I have not tried playing a corp game, but it's happpened in multiple of my runner games as well as spectating from the Corp's perspective, as seen in the attached image (in the log you can see the corp using Daily Business Show, but there are no remotes).  My current windows manager, should it be relevant, is bspwm with compton.  I've checked pacman and firefox is currently up-to-date with whatever is in the extra repository.  I realize this may be considered to be a fringe case, but it is... remotely frustrating (pun most certainly intended).
![screenfetch-2016-02-21_10-58-13](https://cloud.githubusercontent.com/assets/13139417/13203629/485232a2-d88a-11e5-957f-271a9f5d01a7.png)

**Comment by zaroth** [comment]
I happen to be playing from Firefox on Arch Linux every day and didn't ever encounter the issue you encountered. I don't think the problem lies in windows manager, more likely it's your firefox plugins - could you try launching your firefox in safe mode and tell if the issue persists? https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode

**Comment by domtancredi** [comment]
@Eris-chan is this still an issue? Can you reproduce in a safe-mode Firefox?
