### ISSUE TITLE
No rez or paid abilities phase after Runner declares Successful Run?

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#131]
Isn't there supposed to be a phase where paid abilities and non-ice cards can be rezzed after Runner declares that they will continue on with a successful run?

Currently the runner chooses Successful Run and access happens automatically, meaning that the Corp needs to use its paid abilities and rez non-ice cards BEFORE the Runner decides if they will continue with the successful run or not.

According to the Netrunner FAQ, the runner chooses if they will Jack Out or Continue (onto successful run). After they decide to Continue, there's a phase to use paid abilities and rez non-ice cards. Then the run is considered successful and access happens.

https://images-cdn.fantasyflightgames.com/ffg_content/android-netrunner/support/FAQ/Android-Netrunner%20FAQ_Printer_Friendly.pdf

Please correct me if I'm wrong on this one.

**Comment by Zulyen** [comment]
You right. I got the problem yesterday against a Weyland Deck.
i pass all the ice (included a Data Raven that tagged me) and i was approaching the server. My opponent rezzed a Dedicated Response Team i choose to Jack Out.

For my opponnent, the interpretation was different. He thought i already choose to access so used the window ability to rezzed his DRT.
We argue a little, he was right but he was ok to let met jack out (very kind of him, because before i saw the DRT, my intention was to access.)

**Comment by JoelCFC25** [comment]
Closing this in favor of #334 where all the discussion has occurred. @zaroth has an idea so there might be an improvement coming soon.
