### ISSUE TITLE
Crescentus not working

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#1314]
Playing Gabe against two different corps, ran HQ in two different games, broke ice on HQ, crescentus would not fire to derez ice.

**Comment by JoelCFC25** [comment]
Need more information--you didn't by chance pass the ICE you intended to derez, did you? Crescentus requires that you still be encountering the targeted ICE. So for example if there was only 1 ICE on HQ, you broke it, then advanced so the run arrow is at position 0 (between the ICE and the server), clicking on Crescentus will do nothing because `current-ice` resolves as nil.

**Comment by zaroth** [comment]
To sum up, the most common current use of crescentus should be as follows:

1. runner encounters chosen ICE (arrows points at it)
1. runner breaks subroutines of the encountered ICE
1. corp lets runner through by clicking "no further action"
1. runner clicks crescentus to derez encountered broken ICE
1. runner clicks "continue" to pass the derezzed ICE

It is very important that step 5 happens after step 4, not before. If you still can't use crescentus while following these steps, please report exactly what fails to happen at which step.

**Comment by tolaasin** [comment]
ah, that will be it. I thought I could do this at any time, not only during encounter.
