### ISSUE TITLE
Globalsec Security Clearance

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#1321]
the click lost on using Globalsec Security Clearance isn't properly removed

**Comment by enkwolf** [comment]
I also encountered this. Seems to be connected to the new "take clicks" feature - if you use Globalsec Clearance before pushing that button, then you have no clicks to lose (the chat window still says you lose a click but you're already at 0 clicks), and "take clicks" gives you 4.

**Comment by JoelCFC25** [comment]
Interesting. This was meant to have been fixed at #1283 and even included a unit test. Will take a look when I'm able.

**Comment by JoelCFC25** [comment]
Just to clarify--are you guys clicking GSC before hitting Start Turn? If so, you get 4 clicks after you start your turn (which is wrong), because `:per-turn` in the game state is wiped at the moment you click Start Turn. 

If on the other hand you hit Start Turn, you should see the blue pop-up alerting you that you can use GSC prior to clicking Take Clicks. If you want until _then_ to click GSC, you'll see what's on top of R&D and then correctly receive only 3 clicks when you hit Take Clicks.

**Comment by enkwolf** [comment]
Can't speak for the OP, but I definitely did
Start Turn -> GSC -> Take Clicks

This was last week, and the commit is from 13 days ago. So maybe it's worth checking out, although it does seem a bit weird that it would pass the unit test. I can play a couple of games this week with my Sunny deck to see if it comes up still.

**Comment by enkwolf** [comment]
Ok I tested today and it seems to work as intended. Maybe my last game was over 13 days ago after all.

**Comment by nealterrell** [comment]
The commit was only published a 2-3 days ago.
