### ISSUE TITLE
Option to Jack Out appears too soon on first ICE encountered

### ISSUE THREAD

**Issue by adamkski** [mtgred/netrunner#1343]
As a runner (especially as a newbie), when you do a run and encounter the first ICE it is confusing to see the 'Waiting for Corp to take action' message and see that you can click JACK OUT.  What this actually does is jack out after the first ICE is resolved (which is correct), but it suggest that you can click it to jack out before encountering the first ICE.  

I think the JACK OUT button should stay greyed out until after you have approached the first ICE (whether it is razzed or not if I understand the rule correctly).

Not too big a deal once you know, but definitely affected me as a first timer.

**Comment by zaroth** [comment]
Our philosophy historically has been to allow maximum flexibility for players to modify the game state manually - this included the ability to jack out at any time, as mentioned by mtgred in #334. However, this situation is a bit different then preventing runner the ability to jack-out in a specific run window (4.3).

This is simply because many players, me included, use the ability to jackout to quickly 'take back' a run they mistakenly made before the corp starts to reveal hidden information by rezzing approached ICE. Preventing quick jackout and forcing to write in chat to communicate or use `/jack-out` command would take this away and cause much frustration sometimes. So I think this particular part of game logic should stay as it is until the above issue is solved. An ability to quickly communicate to opponent something is up via a big WAIT button and/or to prevent game state changes/pause would be a good start (see e.g. #332).

I'm adding a discussion tag, since I'm curious what others think about this.

**Comment by Saintis** [comment]
The jack-out button is often used as an alternative of the corp triggering an end-the-run subroutine. Making the jack-out button unavailable for the first stage of the run would significantly slow down some parts of the game.

**Comment by zaroth** [comment]
@Saintis above could be fixed if Runner in addition to "Continue" and "Jack out" had a "Let the subroutines fire" button. Of course this would require a lot of reworking how subroutines are handled/implemented ;-)

But the usecase you mentioned is very common. So truly, ability to jack out at the current state of the codebase is simply crucial and I don't see it going anywhere soon.

**Comment by koalabearski** [comment]
I see a few points here that I have some thoughts on.

One is using jack out on your first approach is like an 'undo' button that lets you cancel a run you didn't intend to make.  I think it's unlikely that you misclick doing this given that you have to click make a run _and_ select a target server.  To me that's confirmation enough of your intent.  More likely is that you announce the run and immediately realize a consequence you hadn't before.  That's a much different kind of mistake that I think you should play on with to keep the game fair.  If you really wanted to find a middle ground, maybe a two to three second countdown that says "Approaching ICE" with a cancel button would be fair - but even that I'd make optional before you start the game.

The second is as an alternative to the corp triggering an end-the-run subroutine.  If you can jack out instead of wait for that subroutine, doesn't that mean you can do the same for any subroutine?  If that's the case, I think it's fair to wait and would take the same amount of time since you should be waiting for the corp's subroutines.  Maybe you meant if the corp is AFK for a moment?  In that case, it'd be good to show AFK when the window isn't current on the opponent's screen perhaps.  In practice, I've found when I hit jack out I had to wait for the corp's actions so I'm not sure if I'm missing something.  

I should note, I've only played as runner so I'm definitely overstepping my knowledge on the corp side.  I just thought it valuable as a total newbie to the online version to express how it went and where there was confusion.

**Comment by nealterrell** [comment]
@koalabearski You are missing one point in favor of Jack Out as "undo" -- if you click *the wrong server* when starting the run. 

I think this is a won't-fix.

**Comment by queueseven** [comment]
I agree with @Saintis  and @nealterrell here; we won't change the behaviour because of the reasons listed above. 

Another point is that there are indeed card that lets you jack out on the first ice, like Snitch and Nero Severn, and the way the Jack Out button works now works nicely with those cards.

The a-new-player-who-doesnt-know-better-could-click-the-button-reason is not a good one.

**Comment by koalabearski** [comment]
I'm coming around to the maximum flexibility philosophy you guys have, especially having played a lot more since my original comment.  I still think ICE encounters could be smoother though.  

@zaroth It's really interesting to code something that I might not even notice I do when I play in real life, like letting the corp know I have no action before subroutines fire.  I like the idea of a "No further action" button for the runner (just like the corp has) to give the go ahead.  People type 'fire' (or 'fire?' if you're corp) in the chat anyway.  I remember multiple times where either I or my opponent fire subroutines too soon for whatever reason e.g. firing Data Raven's tag on encounter trigger without realizing it's the runner who chooses a tag or ETR.  I also respect that the more button clicks you need to resolve things the slower the game can seem to the experts out there, so you could just make the button not be mandatory before corp can act.  

Lastly, I wouldn't dismiss new player mistakes too casually.  I think the success of Jinteki.net is mostly due to there being lots of players on it and low wait times for match ups.  The easier it is to pickup, the more that'll stay true.  (Experience ratings anyone?  That's another issue I'm sure ;) When are you guys setting up a Patreon anyway, this seems like tons of work!).

**Comment by queueseven** [comment]
Well, I get your points, and it would be awesome if we had 100% automation without the ability to break the rules. But that's not going to happen, so we try to be as pragmatic as possible.

I say if you don't have problems to play with a new player (and I know a lot of players on J.Net and basically every netrunner player in RL love to introduce new players to the game) play on in the *casually* room; if you want your opponent to know all the rules etc, play in the *competetive* room.

**Comment by koalabearski** [comment]
Fair enough.  I definitely agree that just about everyone playing it on there loves sharing the game.

The casual/competitive channels work really well.  No doubt about that!

**Comment by Saintis** [comment]
One alternative fix would be to make the "jack out" button highlighted as "casual" perhaps when it should not be used for normal jack out. Maybe orange / yellow.
