### ISSUE TITLE
Apocalypse + Hostile Infrastructure doesn't deal the correct amount of damage

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1365]
Somewhat related to #1270, but about a different aspect of Apo + HI interaction. Specifically, HI effect stops once it's trashed and the cards are trashed in a sequence using `doseq`. This leads to unpredictable amount of damage dealt by this interaction. Example: when trashing 9 corp cards with Apocalypse, it could deal anywhere between 1 (when HI is trashed first) and 9 (last) net damage.

A suggestion to fix it by @nealterrell is to copy the current event handler list for :trash prior to doing the trashing, and invokes those events by hand. This would require adding a parameter to `trash` function to prevent triggering trash effects when called by apocalypse, since they will be fired manually.

A similar parameter (prevent firing events) could be used in `draw` function to prevent #1350 or Andromeda Palana trigger.

**Comment by JoelCFC25** [comment]
Is this still a valid issue? I've tried several times now with 1 rezzed Hostile Infrastructure and anywhere from 4 to 6 total installed Corp cards, and every time Apocalypse results in the correct number of instances of 1 net damage.

**Comment by mattchainsaw** [comment]
I just played a game where this messed up. The corp had 6 unrezzed servers, and rezzed it at position 5. Apocalypse did 2 net damage meaning it trashed position 6, then 5 ... down to 1. That's how Apocalypse is coded, so as to iterate on the servers being destroyed. Since the trash all takes place at once, you would need to fire 6 net instead of 2.

**Comment by JoelCFC25** [comment]
Fixed at #3284!
