### ISSUE TITLE
Celebrity Gift: Not Working properly (closed)

### ISSUE THREAD

**Issue by Ian517** [mtgred/netrunner#145]
Celebrity Gift: Not Working properly, or if it is fixed it is not clear when and how you make you selections. Each time i used it, i lost 2 clicks and Celebrity Gift went to Archives without something else happening. :)

**Comment by mtgred** [comment]
The architecture of the server has been changed recently and it causes the server to crash every few hours. The server has been rolled back to a version before the change while the issue is being fixed.

Celebrity Gift was not implemented at the time so you have to resolve the ability manually. Simply list the card you want to reveal in the chat and add yourself credits.
