### ISSUE TITLE
Feature Request: Psi game "Random" button...

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1486]
...to randomly spend 0,1 or 2 $

**Comment by zaroth** [comment]
I find such a button a bit restricting, since not very often you want to put equal odds 33% on every chance. What I think would be more flexible is a local  (just JS, no server communication) die roll, with being able to select the number of die sides (e.g. d3, d6 and d10). This way players could mimic real life random decision making.

**Comment by queueseven** [comment]
Related: #1135

**Comment by queueseven** [comment]
Related: #1195

**Comment by lostie** [comment]
Would integrating something like this in the client do the job: https://github.com/noviny/react-dice do the job ?

There's another nice one http://vicentemundim.github.io/dice-roller/examples.html , but this one seems to use angular, which is not using in this app.

**Comment by queueseven** [comment]
A little overkill to use a library for generating a random number... ;-)

**Comment by lostie** [comment]
Well, the idea was more to have an actually dice rolling on the screen, but if it's ok to just generate a random number, yeah, no library needed

**Comment by queueseven** [comment]
Well, if you want to take the time to implement this, feel free to make a pull request.
I just don't know if such a dice animation would fit into the sites appearance, but if you could make it work... ;-)
