### ISSUE TITLE
Councilman's effect incorrectly persists when a card changes zones

### ISSUE THREAD

**Issue by narcow** [mtgred/netrunner#1571]
This bug probably only has any real impact on CI.

Expected: Cards do not remember their state when trashed and re-installed.

Actual: If Councilman is used to de-rez a card and then that card is trashed and re-installed in the same turn, it still cannot be rezzed for the rest of that turn. Initially observed on Jackson Howard during a CI combo, but it seems to happen elsewhere too.

Steps to reproduce: 
1. Rez Jackson Howard
2. Runner uses Councilman to de-rez
3. Corp installs over the Jackson Howard the Runner de-rezzed
4. Corp returns the trashed Jackson Howard to hand
5. Corp re-installs the copy of Jackson Howard which was trashed. It cannot be rezzed by clicking on the card or by /rez.

**Comment by JoelCFC25** [comment]
Thanks for the report. I'm not sure off the top of my head how best to write it, but broadly put: since this card uses the turn flag system, `deactivate` probably needs to scan the portions of the state related to turn/run/persistent flags for the trashed card's `cid` and wipe all flags related to it.
