### ISSUE TITLE
Feature Request : Add a "Fire" button...

### ISSUE THREAD

**Issue by Salem2612** [mtgred/netrunner#1599]
...in the runner's run menu. When the Runner clicks on it, it adds a text in the chat to inform the Corp that the Corp can fire the subroutines of the encountered ice. ie : "The Corp can resolve the unbroken subroutines of the encountered piece of ice."

**Comment by queueseven** [comment]
Good idea. I hate it to switch from mouse to keyboard during a run. This button should then only be active when there's a rezzed Ice currently encountered.

**Comment by Saintis** [comment]
I had a thought that runner could have same the same ability pop-up as Corp upon clicking ice, although they would just print "runner is not breaking x" or "runner indicated you can fire X" or something like that. 

That way you can be more specific.

**Comment by queueseven** [comment]
Also a good idea!

**Comment by Salem2612** [comment]
Very good idea Saintis.

By clicking a rezzed ice, the runner could have the following choices in the following order :
 * "The Corp can trigger the _when encountered_ ability "xxx" " (xxx indicates the "when encountered" ability.)
 * "The Corp can resolve all subroutines" (Usefull to indicate to fire all subroutines)
 * "The Corp can resolve "xxx"" (xxx indicates each subroutine of the ice. Usefull in the case where few subroutines were broken and not others, ie: Clickable subroutines of Bioroids)

**Comment by Saintis** [comment]
Expanding on that, maybe an ability to spend clicks on Bioroid ice as well.

**Comment by JoelCFC25** [comment]
> "The Corp can resolve "xxx"" (xxx indicates each subroutine of the ice)

Note that there is no system in place yet for tracking the number of subroutines a piece of ICE has. This would be a pretty involved project, since some ICE has variable number of subs and there are several cards that add new extra subs to ICE.

**Comment by Salem2612** [comment]
> Note that there is no system in place yet for tracking the number of subroutines a piece of ICE has. This would be a pretty involved project, since some ICE has variable number of subs and there are several cards that add new extra subs to ICE.

The system in place yet seems creating one pop-up item per subroutine when the Corp clicks on a rezzed Ice. I thought it will be possible to create as many pop-up items on the Runner side. I thought that if the Corp side can retrieve all the subroutines of an Ice from the Database, the Runner side should be able too. Isn't it ?

Here is an example of the pop-up items when a Runner clicks on a rezzed Ichi 1.0 :
- The Corp can resolve all subroutines
- The Corp can resolve "Trash 1 Program"
- The Corp can resolve "Trash 1 Program"
- The Corp can resolve "Trace² : Do 1 brain, give 1 Tag"

These texts could be the ones written in the chat box, and could be smaller in the pop-up items. The more important is to let "The Corp can resolve all subroutines" be on top of the subroutines, because it will be the by-default-choice of all players.

**Comment by nealterrell** [comment]
These are all fine ideas, I'm just commenting on the technical aspects.

We don't have a system right now for showing different abilities to different players when clicking a card. It would not be the end of the world to add one, but it is not there currently. Also, card abilities are *static*, not *dynamic* -- they are initialized one time only (when the card is rezzed) and from then on cannot change in number or labels. The only exception to this rule is the icebreaker "Match strength" code, but that is a unique system that we haven't expanded to other areas yet.

I think the easiest solution here is to show the exact same ICE menu (perhaps without "Derez") to the runner if they click the ICE, so they can just trigger the subs themselves.

**Comment by AlecGamble** [comment]
> I think the easiest solution here is to show the exact same ICE menu (perhaps without "Derez") to the runner if they click the ICE, so they can just trigger the subs themselves.

I think the danger with adding the same options to both players is that maybe both players will end up firing them at the same time and for example with taking damage that could give the corp an unfair advantage because even after rectifying that the corp has essentially exposed one of the cards in the runners hand.

I think it's the runner that should be given the subroutine options anyway because it's them that decides whether they fire or not. Especially in situations where the corp might not be familiar with the deck they're playing against some people rush to fire the subroutines prematurely even when they can be avoided by the runner. (one example of this I've found most common is when people are using traps because they're in the mindset it can't be broken by normal icebreakers and if you're not running AI they will fire it even if you could do something like Security Nexus or something)

Also you'll save time when the runner is choosing specifically which subroutines are firing and which ones aren't.

You could then also include using clicks to break ice for the HB ice (i.e. eli, heimdall etc.) which would help for clarity.

If you leave the corp with the "no more action" prompt you're still leaving them in control of letting the runner through so that both players have to agree that all subs have been dealt with.

**Comment by Salem2612** [comment]
> We don't have a system right now for showing different abilities to different players when clicking a card. It would not be the end of the world to add one, but it is not there currently. Also, card abilities are static, not dynamic -- they are initialized one time only (when the card is rezzed) and from then on cannot change in number or labels. The only exception to this rule is the icebreaker "Match strength" code, but that is a unique system that we haven't expanded to other areas yet.

Ok I understand the technical limitation. It would be a lot of work to show different labels for the 2 players.

> I think the easiest solution here is to show the exact same ICE menu (perhaps without "Derez") to the runner if they click the ICE, so they can just trigger the subs themselves.

I think it is dangerous to let the 2 players firing the subs. They all will fire the subs and they will have to undo what they did twice.

I think a simple new Runner button would be great :
 - Button label : "Resolve subroutines"
 - Button effect : Show the following message in the chat box : "The Corp can resolve the unbroken subroutines of the encountered piece of ice."

It is simple to add (I think), and it helps the Runner to not switch to the chat box just to write "fire".

**Comment by AlecGamble** [comment]
> I think a simple new Runner button would be great :

> Button label : "Resolve subroutines"
> Button effect : Show the following message in the chat box : "The Corp can resolve the unbroken subroutines of the encountered piece of ice."

> It is simple to add (I think), and it helps the Runner to not switch to the chat box just to write "fire".

but it still doesn't give any information on which subroutines to fire. The runner still has to communicate  that which is going to take the most amount of time.

**Comment by Salem2612** [comment]
> but it still doesn't give any information on which subroutines to fire. The runner still has to communicate that which is going to take the most amount of time.

 - In 99% of cases, all subroutines must be fired.
 - If the Runner doesn't break all subroutines, he has to communicate in the chat box which subroutines fire and which doesn't, but it's very rare.
 - For Bioroid clickable subroutines, the Runner just reduces its number of clicks then the Corp understands.

**Comment by AlecGamble** [comment]
> In 99% of cases, all subroutines must be fired.

I think you're being a bit hyperbolic there. I'm only saying it because it's something I frequently encounter. If it was only 1% of the time it's not something I would be bringing up to be a dick. Especially with regards to damage (i.e. komainu, sometimes people let X subs resolve) or traces (playing high link jesminder I always let traces resolve)

And then I think it's also relevant to data raven because there's usually that hang period where the corp doesn't know if they want to take the tag or end the run.

I just think it would be a nice choice for bioroid subs HOWEVER I think it could also be confusing if the first piece of ice encountered when running with Enhanced Login Protocol which isn't automatically implemented.

**Comment by Saintis** [comment]
Working on this. Will have something in a few days hopefully.

**Comment by Salem2612** [comment]
> Working on this. Will have something in a few days hopefully.
I would like to work on it because it seems easy to start contributing on Jinteki.net, but I don't manage to install and run my own dev environment.

**Comment by queueseven** [comment]
That can be tricky. Maybe you want to join our Slack Channel? If you're already on stimslack there's also a j.net room. It might be easier to resolve such issues in chat

**Comment by Salem2612** [comment]
I am not on any slack channel. I would be glad to join yours. I sent an email to mtgred but he didn't answer me. My dev environment is now working on my local machine.

**Comment by Salem2612** [comment]
#1684

**Comment by Salem2612** [comment]
This is done in #1684 .
