### ISSUE TITLE
Fan Site messaging every time agenda is scored

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1609]
I had a single Fan Site installed, and the corp player scored 3 agendas over the course of the game. After each score the Fan Site message triggered. On the second score I still had it installed, but on the third it was in the rfg zone. I had two more Fan Sites in my hand at various points but never installed them (they ended up in the bin over a couple turns due to BioEthics ping).

**Comment by nealterrell** [comment]
So it never got added to your score area?

**Comment by FarCryFromHuman** [comment]
It did as normal when the first agenda was scored.

Up to and just past the time the second agenda was scored, it remained in my score area, but printed a message when the second agenda was scored.

I used it to install a Deus Ex via Artist Colony, which got used that turn, moving the Fan Site to my RFG zone.

The third agenda was scored and Fan Site messaged a third time while still residing in my RFG zone.

**Comment by nealterrell** [comment]
OK, thank you, that is much more helpful :).

**Comment by nealterrell** [comment]
Note to self/devs, I believe this is because the `trigger-event-simult` code does _not_ try to `get-card` make sure that the card that registered the event listener is still in the same zone it was before. So a phantom copy of Fan Site is receiving the events, then attempting to move itself to `:scored`, but `move` is smart and checks to make sure the card is really there. `as-agenda` needs to `deactivate` the card first (because it is being moved to `:scored`, `move` will _not_ deactivate the card), and `trigger-event-simult` needs to retain the load-the-card logic from the old `trigger-event` code.
