### ISSUE TITLE
Political Dealings + Merger (+ Palana Agroplex?)

### ISSUE THREAD

**Issue by atreios** [mtgred/netrunner#1695]
When you try to trigger Political Dealings after drawing Merger, this agenda is not listed as an option for the install, whether you drew it alone or with other agendas. If you draw it with other agendas, those others will be shown in the list, but Merger will not. 

In my present case, I was using 2x Palana Agroplex to draw 3 cards at the start of every turn, and only saw the bug on the agroplex draws, though other means of drawing may also be affected.

**Comment by JoelCFC25** [comment]
Fascinating--I've confirmed this one and I'm totally stumped by it! Any drawn agendas that don't include Merger and Political Dealings will show them just fine. Thanks for the report!

**Comment by JoelCFC25** [comment]
OK, I see the issue now. Political Dealings listens for the `:corp-draw` event, and then scans the `n` rightmost cards in the Corp's hand (where `n` is the number of cards just drawn) to see if any agendas are in there. In the case of an Agroplex where you allow it to fire automatically instead of triggering it manually before your mandatory draw, the system is doing `(draw 1)` twice instead of `(draw 2)`. So if Merger is the top card, the opportunity for Political Dealings to see it is lost when the second `(draw 1)` occurs. 

The workaround here is to always fire your Agroplexes manually prior to your mandatory draw if you have Political Dealings in play.

**Comment by queueseven** [comment]
`Whenever you draw` trigger are quite tricky. A lot of cards don't work correctly (DBS and SAU come to my mind). I don't have a good solution to this at the moment.
