### ISSUE TITLE
Combining Jak Sinclair and Patron (and maybe Security Testing)

### ISSUE THREAD

**Issue by mn200** [mtgred/netrunner#1831]
The UI lets me nominate a Patron server and then make a Jak Sinclair run before taking clicks, but it then asks me to nominate a Patron server again after I press the "Take Clicks" button.  In this case, it's easy enough to click "No server" (thanks to Patron's "the runner _may_ select a server" language), but it still seems like the UI might let you make two Patron runs.

I haven't checked, but Security Testing might have the same problem.

**Comment by nealterrell** [comment]
I thought we fixed this, to be honest. I'll look into it.

**Comment by Saintis** [comment]
I think the fix was to check if `:server-target` was set. When Jak Sinclair makes a successful run the `:server-target` is removed, hence asking again for a server when clicks are taken. Fix might involve either a rework of how `:server-target` works, or adding a custom tag to the card to specify that the server has been set and triggered.

**Comment by nealterrell** [comment]
Aha, brilliant.

**Comment by danhut** [comment]
Think I fixed this here:
[PR](https://github.com/mtgred/netrunner/pull/2323)

**Comment by Saintis** [comment]
This has been fixed.
