### ISSUE TITLE
Satellite Grid?

### ISSUE THREAD

**Issue by Spellapeaka** [mtgred/netrunner#1841]
Satellite Grid (Wetland Upgrade) Does nothing when installed and rezed.

**Comment by JoelCFC25** [comment]
Satellite Grid is not implemented. For future queries like this, the [card status sheet is here](https://docs.google.com/spreadsheets/d/1ICv19cNjSaW9C-DoEEGH3iFt09PBTob4CAutGex0gnE/pubhtml). :)

**Comment by JoelCFC25** [comment]
Just thinking out loud here...

Satellite Grid doesn't provide an extra physical counter, so that rules out interactions with Constellation Protocol and Trick of Light. Really it only boosts the space ICE and anything that counts advancements to determine strength (Ice/Fire/Hadrians walls, etc). This is definitely crude, but what if Satellite Grid set `:additional-advance-counter` in ICE and then the existing `advance-counters` and `space-ice-rez-bonus` functions just added those to the number of `:advance-counter`?

**Comment by Saintis** [comment]
That would be a quick-and-easy solution. A more proper solution might be to change the `:advance-counter` to use similar `:base`, `:modifier` code as `:hand-size`.
