### ISSUE TITLE
Doppelganger triggering after accessing upgrade in central servers

### ISSUE THREAD

**Issue by Repulze** [mtgred/netrunner#1849]
Happened in my game:
1. Corp had unrezzed upgrade in HQ.
2. I had Doppelganger installed and successfully ran HQ.
3. I chose to access the unrezzed upgrade first. Doppelganger then immediately prompts me to make another run.
4. As I have yet to access HQ (Corp's hand), this somehow breaks the run into 2.

Good luck!

**Comment by nealterrell** [comment]
Thanks, this is helpful.

**Comment by nealterrell** [comment]
BTW, what was the upgrade?

**Comment by nealterrell** [comment]
Well, assuming it was CVS or another on-access optional ability for corp, then I have identified the issue. Runs are triggered as "complete" once the runner moves to the access phase if at any point the runner does not an active prompt. Normally accessing an upgrade/asset shows a "Pay to trash?" prompt to the runner, so the run would not be complete, but CVS's on-access effect must be resolved before the runner can trash it; this means the _corp_ gets a prompt, the runner does not _yet_ see the "pay to trash" prompt, so the run ends because the runner has no prompt.

I can fix this one specific issue by showing a "Waiting for..." prompt to the runner when CVS is accessed, but then this problem extends to any other trashable card with an on-access effect that requires corp interaction, like Shi.Kyu. We either need to add waiting prompts to all THOSE cards (annoying) or fix up the run code so that runs end at a more appropriate time. (The current code is legacy.)

**Comment by Repulze** [comment]
Yup, it was CVS. The moment I access CVS, all runner actions become enabled and it can be misleading for the runner. I think it makes sense to show a "Waiting for..." prompt to the runner. But a longer term solution (with a longer amount of work) would be indeed to fix up the run code.

**Comment by Repulze** [comment]
I think the fix broke Doppelganger. Nothing happens when you pick "yes" on the Doppel prompt, so I'm guessing the run is getting ended immediately or just not triggering.
