### ISSUE TITLE
Housekeeping triggers twice on Hayley ability

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#1869]
Prompt appears twice. Easy to circumvent by clicking "Done" on second prompt.

Selecting a card with the second prompt apparently does nothing as well.

**Comment by nealterrell** [comment]
This one is Mostly Harmless as you noted. It's because the "once per turn" part of the ability is only recorded when the ability is actually resolved, not when it is triggered. Same issue comes up when Haley uses Replicator + Bazaar; if her first install is a hardware, she'll see the "Choose Haley or Replicator or Bazaar" prompt, and if she chooses to resolve Bazaar, then she will continue to see Haley as an option to resolve even though it's no longer the first install. The

**Comment by erbridge** [comment]
I feel like something profound was about to follow that.
