### ISSUE TITLE
Sandburg appears to apply strength twice if Rumor Mill has been used on it and then lost.

### ISSUE THREAD

**Issue by triorph-emacs** [mtgred/netrunner#1879]
Unsure of the exact steps that caused this, but I'm pretty sure there was a combination of trashing a sandburg, having it brought back with team sponsorship, rumor mill being played, and a hostile takeover being scored to cancel the rumor mill. When the sandburg was ressed again, the ice was given +6 strength despite the corp only having 15 credits.

**Comment by JoelCFC25** [comment]
My initial read on this is that Rumor Mill isn't doing anything to check that the Corp cards it's disabling are rezzed either when it takes effect initially or when it leaves play. This could lead to doubly-registered events.

**Comment by Saintis** [comment]
I agree with Joel's read. Not checking for being rezzed likely meant that the Rumor Mill disable did not trigger before being trashed (due to multiple score triggers etc) but the leave play effect still triggering, hence causing Sandburg to be initiated with `card-init` twice. 

Probably fixable by either adding rezz condition to the check (and updating to use card rezz trigger) or doing some `when-complete` / `delayed-effect` magic to prevent double init in this corner case (ensure current is trashed before triggering Team Sponsorship)

**Comment by nealterrell** [comment]
Rumor Mill disables unrezzed cards in order to prevent on-rez effects from firing when the card is rezzed. (Elizabeth Mills.) The card has no other way to interrupt those effects.

`enable-card` probably just needs to check to make sure the card being enabled is actually marked as `:disabled true`. Furthermore, to be safe, it should probably only call register-events if the target card is active. Do we have something for `is-active`?
