### ISSUE TITLE
Museum of history only allowed to rez one at a time, but acted as if two were rezzed

### ISSUE THREAD

**Issue by DocCroaker** [mtgred/netrunner#1890]
It's possible this was caused my a rule change I missed. If it was I may have found a rare bug
I was under the impression I could have multiple Museum of History cards rezzed at the same time.
After I played a second museum of history card, but before my next turn started I tried to click on the 2nd museum, but no effect or error message occurred. After a quick chat with my opponent and a quicker rule search, we agreed I could test it by de-rezzing the first MOH, getting a free credit, and then rezzing the 2nd. It did allow me to rez the 2nd. It would not allow me to rez the 1st again.
However once I decided to move on, assuming it had been changed to unique and I couldn't find that rule change. I then choose to activate one MOH before the mandatory draw step, and it forced me to shuffle two cards back into R&D, even though only one MOH was rezzed.
I have a screen shot of the table at the time if it will help.

**Comment by JoelCFC25** [comment]
Museum of History received errata to become unique in version 3.1 of the official FAQ, which took effect on July 18th.

**Comment by DocCroaker** [comment]
I had a feeling it was unique and I missed it.
As a side note... if a player makes the same experimental error I made, the code currently acts as if two had been rezzed. I doubt it's worth wasting a lot of time fixing that though :) Your code correctly prevented me from normally rezzing the 2nd.

**Comment by kevkcc** [comment]
Come to think of it, this is something I've noticed as well. I believe the way MOH was coded was it would prompt you to shuffle up to 3 cards depending on the number of museums (both rezzed and unrezzed since you can rez before start of turn). The code never got changed after the errata so it will allow you to shuffle more than one card into R&D if you have 1 rezzed and 1 unrezzed MOH out which is still legal. It's not a huge issue though because like Jackson, you don't have to shuffle the max cards back in.

We could consider recoding MOH so that you can only shuffle 1 card or leave as is in case it gets unerrata'ed i guess.

**Comment by nealterrell** [comment]
Easy fix, the `:max` on the prompt needs the same rezzed filter as the `:prompt` message. It was wrong before, as you're not allowed to rez cards in the window during which MoH triggers, so any unrezzed MoH should not count for the ability.
