### ISSUE TITLE
Invisiable cap on AstroScript Pilot Program addions in Deck builder

### ISSUE THREAD

**Issue by simianspaceman** [mtgred/netrunner#1895]
Hey Guys,
I am attempting to build a Corp deck using the "NBN: Making News" as an identity. I am finding regardless of the number of "AstroScript Pilot Program" cards I add in the number text field, It will only allow the addition totalling 1. Using the + icon is ineffective. Manually changing the number to a 2 or 3, turns the Text entry on the left side of the window red (invalidating the deck). A quick search shows no erratta to this effect, though it is on the most wanted list on pp 7 of the [tournament rules](https://images-cdn.fantasyflightgames.com/filer_public/de/bb/debb8a85-d0db-40d7-8b62-be12260f2fa7/adn_tournament_rules_v302.pdf).

**Comment by JoelCFC25** [comment]
AstroScript Pilot Program received errata in FAQ version 3.1, which took effect on July 18th. It is now limited to 1 copy per deck.

**Comment by simianspaceman** [comment]
Ah, Brilliant. Great! Happily close the ticket then! sorry!

**Comment by simianspaceman** [comment]
As a procedural question: Instead of invalidating the Deck and having an invisible card cap , would it not be better to highlight the card set, and make the deck classed to be casual only?

**Comment by Saintis** [comment]
I agree more explicit reasons for decks being casual or invalid would be useful.

In the case of Astro Script errata the change is technically in place and enforceable for all kinds of netrunner, not just for tournament play (as is the case for the Most Wanted List). That's why "invalid" is more correct than "casual" (which just means non-compliant with MWL).
