### ISSUE TITLE
Scored puppet master desyncs when using advancement from ability to score accessed breaking news

### ISSUE THREAD

**Issue by michaeltchapman** [mtgred/netrunner#1915]
Hello! I'm not sure if this affects other cards, I (corp) had a breaking news with 1 advancement on it, and a scored Puppet Master. Runner successfully runs this server. Puppet Master triggers and I place the advancement token on Breaking News. I then score breaking news. At this point, the runner has a single option available: to steal the breaking news, which is already scored for the corp. Clicking on this for the runner caused an error stating 'Desync from server' or something similar. The corp has no buttons available. The runner did have two tags applied correctly from scoring the breaking news.

Sorry I don't have screenshots or anything.

**Comment by Saintis** [comment]
The problem is that you cannot score an agenda during the runner's turn. According to the game rules you can only score agendas at the start of the Corp turn or before/after a Corp action.

Preventing scoring cards on the runner's turn should fix the potential desync issue though.

**Comment by michaeltchapman** [comment]
Aha! Thanks!

**Comment by FarCryFromHuman** [comment]
The corp can score on the runner's turn with [Plan B](https://netrunnerdb.com/en/card/05023), so that might be a potential landmine when fixing this issue. The "Score" action option found on agendas can certainly be disabled on the runner's turn though.

**Comment by Saintis** [comment]
So the solution is to either disable the "Score" action on the Runner's turn. This would be slightly inconsistent though since then "Advance" should technically be disabled as well.

I feel it would be better to write some wrapper function for the `score` function so that it is not called directly by the "Score" action, and restrict the usage in this wrapper function.

And maybe add a `/score` command if one does not already exists for potential corner-cases or weird interactions.
