### ISSUE TITLE
Plan B appears broken.

### ISSUE THREAD

**Issue by cwoac** [mtgred/netrunner#1919]
Two seperate games, running on chrome 52.0.2743.116, both times I get the message that I have scored braintrust, but nothing happens - it remains in hand, the plan b remains in the server.

Stack Trace:
```clojure
Error do select Braintrust #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops "Numbers.java" 1013]}]
 :trace
 [[clojure.lang.Numbers ops "Numbers.java" 1013]
  [clojure.lang.Numbers gte "Numbers.java" 233]
  [game.core$score invokeStatic "core-actions.clj" 282]
  [game.core$score invoke "core-actions.clj" 276]
  [game.core$fn__8414$fn__8424 invoke "cards-assets.clj" 738]
  [game.core$do_effect invokeStatic "core-abilities.clj" 233]
  [game.core$do_effect invoke "core-abilities.clj" 229]
  [game.core$do_ability invokeStatic "core-abilities.clj" 214]
  [game.core$do_ability invoke "core-abilities.clj" 187]
  [game.core$resolve_ability_eid invokeStatic "core-abilities.clj" 97]
  [game.core$resolve_ability_eid invoke "core-abilities.clj" 77]
  [game.core$resolve_ability invokeStatic "core-abilities.clj" 72]
  [game.core$resolve_ability invoke "core-abilities.clj" 15]
  [game.core$resolve_select invokeStatic "core-abilities.clj" 352]
  [game.core$resolve_select invoke "core-abilities.clj" 340]
  [game.core$select invokeStatic "core-actions.clj" 168]
  [game.core$select invoke "core-actions.clj" 153]
  [game.main$handle_do invokeStatic "main.clj" 75]
  [game.main$handle_do invoke "main.clj" 72]
  [game.main$handle_command invokeStatic "main.clj" 148]
  [game.main$handle_command invoke "main.clj" 137]
  [game.main$run$fn__24022 invoke "main.clj" 183]
  [game.main$run invokeStatic "main.clj" 173]
  [game.main$run invoke "main.clj" 167]
  [game.main$_main$fn__24057 invoke "main.clj" 237]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by cwoac** [comment]
Possibly worth noting that in both times, I had mushin'd out the plan b and was trying to score a braintrust.

**Comment by Saintis** [comment]
Think I know what the problem is. Since the privacy rework, `score` doesn't trust the data that is passed to it, specifically the `card` value, and instead reloads it with `get-card`. This means Plan B implementation doesn't work since it specifically adds the required advancement tokens to the card it passes.

Not sure why the message prints, but this would be why the card is not scored.

I see two potential solutions:

1. Update the state in Plan B so that `get-card` does not overwrite the `:advancement-counter` value.
2. Rewrite how scoring is handled and make the user "Score" action call `try-score` or similar function and make the actual scoring take place in `score` where requirements are not checked. Then you could move the `get-card` function to just be in the `try-score` function exposed to the client. (Would solve #1915 as well)
