### ISSUE TITLE
Space camp in archives doesn't end run properly

### ISSUE THREAD

**Issue by kevkcc** [mtgred/netrunner#1929]
1. Put space camp in Archives
2. Runner runs on it
3. After the advancement token is placed, the run should end since that was the last thing to access but the Runner gets to click successful run again

Other notes: If space camp isn't the last effect in Archives, for instance, if you access Space Camp first and then a News Team, run will end properly. Also the :cancel-effect on Space Camp is busted, it just kicks you out of the run completely.

Shi-kyu might have a similar issue since it's an Archives trap but I can't test it due to the weird character not rendering in my browser

**Comment by zaroth** [comment]
I can't help but notice how you casually mentioned another huge usability bug at the end (a card not loading/working) at the end of your post ;-) Could you tell us what browser/system are you using and what problems with gameplay does Shikyu cause?

**Comment by nealterrell** [comment]
I get this issue too, when running the game server on Windows. Card names with special characters get mangled somewhere along the way; they render with wrong character sets, and must be represented internally with the wrong characters as well, because their behaviors are not hooked up (which would happen when the server attempts to find the `card-def` for a card with a "wrong" title).

**Comment by kevkcc** [comment]
Yea I'm on Windows 10/Firefox and the behaviour is just like Neal described. Since the card-def can't be found, it's effectively a blank card. It's not an issue on the live server though, only for my dev environment. Don't think we need to do anything.

I only brought up Shikyu because it might be worth testing it whenever Space Camp gets looked at.
