### ISSUE TITLE
Psychic Field and archives

### ISSUE THREAD

**Issue by kevkcc** [mtgred/netrunner#1965]
When the runner runs archives, Psychic Field shows up as one of the cards able to be accessed, which is unnecessary.

**Comment by JoelCFC25** [comment]
This will get fixed in `defmethod choose-access :archives` in core-runs.clj--I'm guessing there needs to be another case right below the or statement that starts with: `(or (not (get-in cdef [:access :req]))`

I think for Psychic Field to get evaluated it would have to be: `(or (not (get-in cdef [:access :psi :req]))`
