### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Beancake12** [mtgred/netrunner#1970]
Please describe the circumstances of your error here.

Stack Trace:

``` clojure
Error do play Sports Hopper #error {
 :cause "No matching clause: "
 :via
 [{:type java.lang.IllegalArgumentException
   :message "No matching clause: "
   :at [game.core$play invokeStatic "core-actions.clj" 15]}]
 :trace
 [[game.core$play invokeStatic "core-actions.clj" 15]
  [game.core$play invoke "core-actions.clj" 11]
  [game.main$handle_do invokeStatic "main.clj" 75]
  [game.main$handle_do invoke "main.clj" 72]
  [game.main$handle_command invokeStatic "main.clj" 148]
  [game.main$handle_command invoke "main.clj" 137]
  [game.main$run$fn__24694 invoke "main.clj" 183]
  [game.main$run invokeStatic "main.clj" 173]
  [game.main$run invoke "main.clj" 167]
  [game.main$_main$fn__24729 invoke "main.clj" 237]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by Saintis** [comment]
So this seems to have triggered by the `(:type card)` evaluating to `nil` in the `play` function.

I think most of these weird errors are caused by sending a command relating to a non-existent card.

My suspicion is that the cause is minor lag or similar which causes two commands to be sent back-to-back targeting the same card, but the second command referencing a missing card since the first command caused it to be moved (hence the errors in `play` and `score`).

These could probably be solved by doing proper guarding against duplicate commands sent.
