### ISSUE TITLE
Gang Sign and Corp win condition bug

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#1981]
Situation: Both players at or near game point.

If the Corp scores an agenda giving them a game-winning number of points, the points are not registered until after `:agenda-scored` effects complete, which can result in a Gang Sign HQ access that hits an agenda wrongly giving the Runner the victory.

**Comment by nealterrell** [comment]
So I originally made this decision because of Project Beale, whose agenda points can't be gained until its on-scored trigger is resolved. So I just waited for all on-scored triggers to resolve before granting the points. I could "hack" around this by making a silent trigger handler that adds the point after the active player's handlers go, but before the opponent's do.
