### ISSUE TITLE
Invasion of Privacy removes cards

### ISSUE THREAD

**Issue by McBEASTse** [mtgred/netrunner#204]
Corp used Invasion of Privacy with Trace 5. In my hand was 3 events and 2 programs. All cards where removed (not in any space on screen) including programs.

**Comment by mtgred** [comment]
Don't worry it's normal. Invasion of Privacy moves all the card in the Runner's hand to a zone visible only to the Corp. It's then up to the Corp to drag and drop cards back to either the discard pile or the hand of the Runner.

The card are not visible to opponent because it's the same mechanism used for Indexing or Precognition.

I will change the code to show only the back of the cards in that special zone to the opponent to avoid confusion.
