### ISSUE TITLE
Shards free install + additional costs

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2153]
Played some games with Docklands Crackdown and Scarcity of Resources. I noticed at least Hades Shard cost 2c when installing for free from an archives run. I think in this case it was Scarcity of Resources, but could have the same issue with Docklands Crackdown as well, since both have additional costs for installs.

**Comment by JoelCFC25** [comment]
Thanks for the report. The Shards are all set to have a fixed `install-cost-bonus` of `:credit -7`, so that wouldn't factor in other cards that increase install costs. Docklands and Scarcity will each do this independently and in fact would combine if both were active. We can just boost the the Shard install cost bonus (e.g. -20) or something to make sure it would cancel out all other increases--you wouldn't "make" credits this way either. But Docklands and Scarcity would still print their effect messages to the game log...

**Comment by artturipi** [comment]
Good thing the Shards don't say "install from grip by paying 1c, ignoring all additional costs" or something similar. That'd be a pain to implement. :)
I'm not sure if the log messages are a problem (they could be misleading for sure), but it's better if the end result is correct, since it's currently easy to miss that you're paying something for the install if you're not paying attention to the log. If the "ignoring all additional costs" part is clear enough, I doubt it's too confusing that the corp cards log something irrelevant. And actually, for Docklands, it's almost better that it does print into the log since it's triggering for the first install only (and you could wonder why it isn't triggering if it never printed anything in this case).
