### ISSUE TITLE
Unable to use Leela Patel Ability on unrezzed HQ Upgrades

### ISSUE THREAD

**Issue by asertus** [mtgred/netrunner#2163]

**Comment by JoelCFC25** [comment]
Thanks for the report. I think you must have clicked on the portion of the upgrade that overlaps the Corp's ID, and due to a z-index CSS issue it tried to return the identity itself. Leela's card targeting needs to be tightened up and require that an eligible card to click on be `installed`. That should fix this by making it impossible to select the identity.

**Comment by JoelCFC25** [comment]
OK, my fix works, but it will still require the Runner to click on the portion of the HQ upgrade that **does not** overlap the Corp identity.
