### ISSUE TITLE
Hellion Beta Test

### ISSUE THREAD

**Issue by Macduffle** [mtgred/netrunner#2179]
Howdy!
Tested Hellion Beta Test a couple of times, and it doesn't fire or give a prompt. 

Once after a Jackson Howard was thrashed, and once after Sensie Actors Union got thrashed. 

I've got a feeling it might just be a difficult to card to code?

greetz,
Macduffle

**Comment by JoelCFC25** [comment]
This card is not implemented. The [card implementation status sheet](https://docs.google.com/spreadsheets/d/1ICv19cNjSaW9C-DoEEGH3iFt09PBTob4CAutGex0gnE/pubhtml) is linked on the main site's About tab. And yes, at this point if a card remains unimplemented, in 99% of cases it's because it's terribly difficult to do--as is the case for this one.

**Comment by nealterrell** [comment]
If the condition is too hard to enforce, then we should at least program the trace effects. I think (?) those are easy enough?

**Comment by JoelCFC25** [comment]
I might be overestimating the actual difficulty, but the corner case--which someone would find and report within 30 minutes I'm sure--involves Salsette Slums, yet again.

**Comment by Macduffle** [comment]
*shakes fist* SALSEEEEEETTE!!!!

**Comment by JoelCFC25** [comment]
Coming in #2186. There are gonna be some corner cases to tidy up as we go for cards that trash things you access going through `handle-access`. Imp comes to mind immediately, but let me know if there are others. Remember it has to be a card you *access*, so for example Singularity doesn't count.
