### ISSUE TITLE
Couldn't drag cards after overdrawing with Jackson

### ISSUE THREAD

**Issue by haradan** [mtgred/netrunner#2195]
I was playing NEH, installed some cards and drew with Jackson last click, then found I was unable to discard because every time I tried to drag a card it got highlighted with a blue border but didn't move. This happened for every card I tried to drag until they were all highlighted with a blue border.

I then tried refreshing the page and it sent me back to the lobby and I couldn't get back to the game.

**Comment by nealterrell** [comment]
What browser?

**Comment by haradan** [comment]
Firefox. I can check the version this evening if you need that.

**Comment by nealterrell** [comment]
I'm just guessing that this is because of a slight misclick. If you click and drag on an area of the screen that isn't a card (even if you're only off by 1 pixel), the browser will see that as a "I want to select contents of the page to copy" operation and start highlighting the elements you have selected. Once that happens, the browser will interpret any further click+drag operations as its own drag+drop, intercepting Jinteki's attempt to receive that information. I don't know how we can fix this; in the future, try just clicking once in the chat log to deselect everything.
