### ISSUE TITLE
/discard without the hash discards the first card from hand

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2315]
If you use /discard 3, rather than /discard #3, the command is executed despite the incorrect syntax and the first card from hand is discarded.

**Comment by danhut** [comment]
Likewise if you a command intended to be used with no #, and you mis-use it unexpected things happen.  For example "/credit #4" will result in setting to one credit.  

The intent of using # is that you can count your cards from 1 to 5, rather than the standard computer index from zero.

A fix would be to split the input processing out for the commands using # such as discard.  I could do this if the team wanted me to.
