### ISSUE TITLE
Multiple Space Camp Access Bug

### ISSUE THREAD

**Issue by autumnleaves** [mtgred/netrunner#2348]
If multiple Space Camps are in Archives, they fire twice. Eg. 2 Space Camps fires 4 times.

Haven't tested for multiple accesses from R&D or HQ, or when 3 Camps are accessed, but 2 is definitely buggy.

**Comment by danhut** [comment]
I just tried it and it works as expected.  Was there something else in R&D or other cards rezzed?  
My setup was just 2 Space Camp in Archives, and an Ice Wall installed on HQ

**Comment by autumnleaves** [comment]
It's happened every time I've had 2x Space Camp in Archives for me.
Generally it was Ice Wall or another advanceable Ice out, and 2x Space Camp + misc assets and operations in Archives (eg. 2x Beanstalk Royalties, 2x Space Camp, Grndl Refinery, Dedication Ceremony)

I will make a note of the exact setup next time it occurs.

**Comment by Barbrarian** [comment]
Just wanted to note that I have experienced this a few times - after the runner has accessed space camp, it seems to restart the access (e.g. If in Archives with three shocks and the runner triggers all three shocks followed by Space Camp the runner is prompted to access all of the shocks and space camp again or if the runner accesses Space Camp in HQ they are given a second access after the first.)

It seems to happen more if I click through the prompts quickly, so it might have something to do with the Corp and runner simultaneously responding to a prompt, but I've only ever seen one side of the interaction so I'm really not sure.

**Comment by JoelCFC25** [comment]
> It seems to happen more if I click through the prompts quickly

If you scan through all of the issues marked "can't reproduce" this is usually the common factor.

**Comment by Barbrarian** [comment]
Makes sense - I suspect that might also mean it is extraordinarily difficult to fix! For the time being I will try taking my time after a Space Camp access to give the runner a chance to respond.

**Comment by TheRealC** [comment]
Just wanted to "necro" this to mention that I've been experiencing this multiple times as well. I'll try the above mentioned "trick" of not clicking too rapidly, but it seems to me there are issues even when I do take my time. There's also been exactly one case where accessing a Space Camp inexplicably made a Medium gain another Virus counter, and then caused the run to enter a state where it could not be completed or aborted without console commands, but I feel like that one will be essentially impossible to reproduce...

**Comment by JoelCFC25** [comment]
The key will be to have as much detail as possible about what else was in Archives, what was installed, how the run was initiated (click? event? other?).

**Comment by TheRealC** [comment]
The thing is, this has happened quite a lot of times, in various combinations of board states. I've had it happen from R&D and Archives - can't remember if it's happened in HQ, have never seen it in an external - and I've had it happen with 1x Space Camp only card in Archives or Space Camp on top of R&D during single access, both with completely empty boards (save probably an ice on HQ) and full boards (ice everywhere, Runner with full rig). I've also had it happen during huge multiaccesses, like basically full Archives and Counter Surveillance, and it has happened also in cases where the Runner _did_ access more than one Space Camp (e.g. three pop-ups for two Space Camps). First and last click seem to make no difference, same with normal runs and event runs - although I'll try to log it more carefully.

To be clear, the "it" that happens is in almost all cases is simply that the Space Camp pop-up shows up more times than expected (precisely once more than expected, as far as I've noted). However, very rarely (now twice) there's been cases where this has interfered with other cards on the board. The first is as I just explained - the Medium suddenly getting more counters and the run "jamming" - and the second, which happened only minutes ago, was a Temujin Contract suddenly emptying itself of its remaining credits (sadly I could not make out if this number was 4 or 8, since it happened quite quickly and was quickly remedied). This was during a normal run on Archives - the third such run this turn, fourth click of the turn - where both players had significant numbers of installed cards, the only of which affected the run in question (normal run on un-iced Archives) were Desperado (there was a John Masanori present, but he had already triggered earlier, on the first run of the turn - also on Archives, but here Space Camp behaved nicely).

I'm quite clueless as to why this weird interaction takes place, but maybe it in some way is tied to the issue? Space Camp somehow triggers Successful Run triggers where it shouldn't... in some way? Beats me.

**Comment by JoelCFC25** [comment]
I'm sure all that is true, but meanwhile...I have _never once_ managed to reproduce this.
