### ISSUE TITLE
Brain Chip hosted on Supplier issue

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#2358]
Install The Supplier, host a Brain Chip on it. Brain Chip should be inactive by definition. Give yourself tags, then as Corp, trash The Supplier. Brain Chip's `:leave-play` effect is firing for some reason, despite the card not being installed, and the Runner's MU and maximum hand size get reduced.

**Comment by danhut** [comment]
I just realised this issue is for hosting on the supplier not peddler. Will have to try it out but since card is not facedown it seems unlikely!

**Comment by danhut** [comment]
I take it back - the fix should work.  :facedown is set when hosted on The Supplier
Just needs testing.

**Comment by danhut** [comment]
Added a test case to ensure this is the same fix

**Comment by JoelCFC25** [comment]
This is still occurring.

**Comment by danhut** [comment]
Do you know the process to reproduce?  I put a unit test for this when I thought I fixed it but the test must be the wrong process...

`(deftest the-supplier-trashed
  ;; Issue #2358 Brain chip mem is deducted when it is hosted and Supplier is trashed
  (do-game
    (new-game (default-corp)
              (default-runner [(qty "The Supplier" 1)
                               (qty "Brain Chip" 1)]))
    (take-credits state :corp)
    (is (= 4 (:memory (get-runner))) "Runner has 4 MU")
    (play-from-hand state :runner "The Supplier")
    (let [ts (get-in @state [:runner :rig :resource 0])]
      (card-ability state :runner ts 0)
      (prompt-select :runner (find-card "Brain Chip" (:hand (get-runner))))
      (is (= 4 (:memory (get-runner))) "Runner has 4 MU")
      (take-credits state :runner)
      (core/gain state :runner :tag 1)
      (core/trash-resource state :corp nil)
      (prompt-select :corp (get-resource state 0))
      (is (= 2 (count (:discard (get-runner)))))
      (is (= 4 (:memory (get-runner))) "Runner has 4 MU"))))`

**Comment by PesiTheWizard** [comment]
It may help to know that this happens with all cards that include :leave-play, be it on The supplier or Personal Workshop. Confirmed instances follow:

A trashed The Supplier hosting...(Let's call this group A)
...Q-Coherence Chip : -1 memory (not anymore since the Q-C fix)
...Muertos Gang Member : Corp can rez something for free
...Akshara Sareen : Corp has only 2 clicks per turn henceforth
...Wireless Net Pavilion : Trashing resources no longer costs any money (doing this twice does not cause the corp to gain money when trashing resources)
I have no doubt that if it were possible to host Origami in some manner the same would apply.

This also removes effects from other copies of cards already installed. Confirmed are:

A trashed The Supplier/Personal Workshop hosting...(Let's call this group B)
...Theophilius Bagbiter : The active Theophilius Bagbiter stops doing it's thing
...Clot : Existing clots stop working
Suspected to be the same : Raymond Flint, Paparazzi

Although I haven't tested it specifically, I have no reason to believe that the 'fix' that was applied to Brain Chip previously will be different from group B. It was basically moved from group A to group B.

**Comment by JoelCFC25** [comment]
Haven't written full unit tests to ensure it, but so far all of the scenarios listed above work correctly if the following is added directly below line 22 of `installing.clj`:

`(not (and (= (:side card) "Runner") host (not installed) (not facedown)))`
