### ISSUE TITLE
Server reset

### ISSUE THREAD

**Issue by CptHilts** [mtgred/netrunner#237]
Is it possible to have the server automatically reset? This could alleviate the dead games issue. Alternately would you be willing to allow another user to reset the server? Someone who has done programming for the site, someone you trust.

**Comment by mtgred** [comment]
I don't think the ghost games have any impact on performance. The server currently runs a fast dedicated server with 16GB of RAM. During peak time, only 1 GB is used.

The lag is probably due to inefficient networking code and bandwidth limitation.

So a server reset won’t yield any lag improvement, except a very temporary one by killing all the running games. :)

**Comment by CptHilts** [comment]
Fair enough. Thanks for letting me know. I guess it feels like there is a correlation but you have the data.

**Comment by CptHilts** [comment]
How much would more bandwidth cost? Is it worth trying to get the community to pay for it?

**Comment by mtgred** [comment]
The best solution would be to rework the networking code to make it more efficient.

The server has been already upgraded twice and now runs on a quite performant server. After each upgrade the performance improved a bit but then more players start playing until it lags again. So upgrading the server a third time won't help much i think.

**Comment by CptHilts** [comment]
I wish I could help with the programming but alas I am not proficient. Your popularity is working against you in the case. Thanks again for all the work!
