### ISSUE TITLE
Dedicated Neural Net and trashing HQ Upgrades

### ISSUE THREAD

**Issue by poi2000** [mtgred/netrunner#2376]
I was playing a game with Nisei Division against Andromeda and had some strange things happening. I had scored a Dedicated Neural Net and had an unrezzed Hokusai grid on HQ. My opponent ran HQ and I rezzed the Hokusai. It gave me a list of choices, activate hokusai first or DNN. I activated Hokusai, then activated Dedicated Neural Net and was successful. My opponent accessed mushin no shin from my HQ but wasn't given the option to trash Hokusai Grid. They then ran HQ again and I was again given a menu asking if I wanted to activate Hokusai or DNN despite me having already used DNN this turn. If I clicked on the DNN trigger however, it would correctly do nothing the second time. I think the Neural net is activating, sending the run directly to accessing HQ and skipping the process of accessing upgrades on HQ.
![dedicated neural net issue 1](https://cloud.githubusercontent.com/assets/22971454/23098679/bb3a2174-f622-11e6-8876-3c807fb26fc2.PNG)

**Comment by danhut** [comment]
This is because the replacement access effect blocks accessing upgrades in the current code.  I think a fix could be split up the current function access-helper-hq into one function that handles HQ access, and a second which handles access to upgrades.  Then latter could then be referenced from the card replacement effect.

If other guys on the team think that is ok I'll have a stab.
