### ISSUE TITLE
Admins and/or game killing

### ISSUE THREAD

**Issue by eah13** [mtgred/netrunner#238]
Lag seems to be 1:1 related to how many games are running.  Many of these games seem to be old or abandoned.  A way to kill these games without restarting the server would make the platform much more resilient.  If trusted users could be made admins and given this ability then old rooms could be killed.  If you were worried about killing legit games, a message could be dispalyed to the players "This room will be killed in 5 minutes.  Click here to prevent this."

Ideally these admins would be in several different timezones.

**Comment by mtgred** [comment]
The server currently runs on a fast dedicated Xeon server with SSD and 16GB of RAM. During peak hour the cpu usage is very low and only 1GB of ram is used.

I think the lag comes from inefficient networking code causing a bandwidth bottleneck. The ghost game don't send any data so i don't think it has an impact performance. The ghost games actually appear because the server lagging. When multiple users tries to join and/or leave games at the same time the server can get out of sync. Of course the longer the lag time, the more likely this happens. That's why there is a correlation between the lag and the number of games. :)

Fixing the ghost game issue is actually tricky because it happens only when the server is lagging so it's hard to reproduce the issue in development. I tried to modify the code handling the list of game "blindly" hoping it will fix the issue but still haven't managed to solve the issue yet.
