### ISSUE TITLE
Wasteland does not give a credit when triggered on the corps turn

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2467]
Geist with wasteland against HB ETF - consistently did not give a credit when cards were trashed on the corps turn (eg fall guy).

**Comment by tolaasin** [comment]
Actually, probably delete this - this was on zaroth this afternoon so it could be old code on that server.

**Comment by JoelCFC25** [comment]
No, this is a legit bug. The backup server is current with master now. This bug was introduced at #2448 (paging @danhut). Each player's `[:register]` lives on until the end of the opponent's turn, only getting wiped at the start of the player's subsequent turn. So if you trigger Wasteland on your own turn, the new faulty code will stop it from firing if it should trigger again on the next Corp turn.
