### ISSUE TITLE
Neutralize All Threats Bugs

### ISSUE THREAD

**Issue by ZeromusPE** [mtgred/netrunner#2506]
There are two bugs I've seen for Neutralize All Threats.

1) If I run twice on HQ in one turn, it lets me access twice both times.
2) Sometimes I am not forced to trash a card when I access it.  I think it might be when I access a non-trashable card first.

Thank you for supporting your friendly Adam players!  =-)

**Comment by JoelCFC25** [comment]
I don't see how #1 is a bug, as NAT's text is: 

> Whenever you access cards from HQ, access 1 additional card.

As for #2, we would need more details--e.g., the entire sequence of actions during a turn when this occurs. Note that a run on Archives (when it contains a card with a trash cost) will "use up" NAT for the turn, so that if you subsequently access a card in R&D/HQ/remote with a trash cost, you aren't forced to trash it.

**Comment by ZeromusPE** [comment]
You are so right.  I got them confused.  Also, I'm dumb.

I will attempt to get more data for the second issue.  Thanks!

**Comment by JoelCFC25** [comment]
Have confirmed the "not forced to trash" issue, and I know the logic in line 849 is wrong, still trying to determine what the right code is to fix it.

**Comment by ZeromusPE** [comment]
Thank you, good sir!
