### ISSUE TITLE
Bad Interaction with Exile and Customized Secretary install from heap

### ISSUE THREAD

**Issue by graydoo** [mtgred/netrunner#2588]
Installed Customized Secretary with Scavenge, creating a list of top 5 cards and then drawing the top one. Top card was then in hand but still part of top 5 selection, resulting in lock up.

**Comment by nealterrell** [comment]
The problem here is that both abilities are supposed to trigger in the same window, and the Runner should choose between them... but the way things are coded, Exile is informed of the install after Secretary becomes active, but before Secretary's prompt resolves, so the Exile draw is triggered while the "Choose a card to host" prompt is still active. We need to trigger both the installed card's effect and the `:runner-install` event in the same window, like how we trigger both the effect of a scored agenda and any `:agenda-scored` triggers in the same window. Requires surgery.

**Comment by nealterrell** [comment]
I have fixed this issue. Prove to me it was worth it :P.

**Comment by danhut** [comment]
Fixed via #2907
