### ISSUE TITLE
Synthetic Blood and Titanium Ribs

### ISSUE THREAD

**Issue by HongkongKoma** [mtgred/netrunner#2617]
Triggers don't resolve in the correct order. When Synthetic Blood and Titanium Rips are installed and runners get a damage, he first gets a card then may choose a card to trash. 

In my understanding, the runner first takes a damage and trashes a card, then Blood triggers and gets him a card.

**Comment by JoelCFC25** [comment]
Possibly solvable by adding `:interactive (req true)` to both cards.

**Comment by chrisferg** [comment]
I wonder if this isn't a bug. My understanding is that you _should_ draw a card before choosing what to discard, because the card draw on taking damage is simultaneous with the discarding a card on taking damage, and so the runner can choose which order these happen. Not 100% sure about that, it seems like a tricky ruling...

**Comment by JoelCFC25** [comment]
Actually, I now think this is a result of Titanium Ribs brokenness, which is close to being fixed.
