### ISSUE TITLE
Off-Campus Apartment draws even if you can't actually install onto it

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#2620]
To reproduce:

1. Have Off-Campus Apartment installed.
2. Have a connection in hand with an install cost of more than 0.
3. Have fewer credits in your credit pool than it takes to install the connection.
4. Click Off-Campus Apartment and use the ability that lets you spend a click to install + host the connection from your hand.

What should happen: nothing, as the Runner cannot afford to install the connection.

What actually happens: a click is used, a message is printed to the log saying what connection is being installed on Off-Campus Apartment, and Off-Campus Apartment still draws a card for the Runner.

Edit: on the off chance it only happens to specific connections, I was testing using Maxwell James, who costs 1, while I had 0 credits in my credit pool. But I suspect it's a less specific case where OCA does not actually check if something was installed.

**Comment by JoelCFC25** [comment]
Yes, it's the general case and would apply to any connection you can't afford. There is a reason why the `:cost` vector was nested inside a `resolve-ability` but I'll be damned if I can remember why. Probably a long-ago complaint that OCA was deducting clicks when you used it even if it turned out you had no connections at all or none you could afford.
