### ISSUE TITLE
Eater and Counter surveillance interaction.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2661]
Eater does not allow access yet counter surveillance will allow the runner to access x number of cards for the declared server on a counter surveillance run.

**Comment by stoppableforce** [comment]
Counter Surveillance declares a max-access again, overriding the one from Eater; it shouldn't do so. The implementation appears to be based on a misunderstanding of how the card works, and also does not work correctly with other sources of bonus accesses like RDI, Medium, HQI, and Nerve Agent.

**Comment by JoelCFC25** [comment]
> Counter Surveillance declares a `max-access` again

Yeah, this part is definitely wrong. Dropping that alone makes it combo with an HQ Interface correctly. I haven't tried all the other stuff yet.

**Comment by stoppableforce** [comment]
>I haven't tried all the other stuff yet.

Medium/Nerve Agent are going to be the tricky one. They appear after you pay for Counter Surveillance, and the Medium/Nerve Agent access seems to completely replace Counter Surveillance's access. I'm guessing this is again due to CS being a weird access replacement that's currently implemented as a bonus access; Medium/Nerve Agent just replaces it a second time.

**Comment by Saintis** [comment]
This is probably fixed in my PR, mostly since the `:max-access` is removed.
