### ISSUE TITLE
IT department doesn't count up the strength propertly after a few uses

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#273]
After the first 2 or 3 uses of IT department to boost the strength of a piece of ice it doesn't add strength like it should, 
Example:
Install it department in new remote, install tollboth in front. Rez it department and give it 4 counters then rez the tollboth and start uping its strength with it department. Here are the results:
one counter spent:     str 9 (correct)
two counters spent:    str 11 (should be 12)
three counters spent: str 11( should be 14)
four counters spent:   str 9 (should be 15)

**Comment by mtgred** [comment]
If i understand the ruling for IT Department correctly the current implementation is correct.
Each counter give 1 + n strength, where n is the number if counter remaining on IT Department.

In your example:
1 counter: 5 + 1 * 3 + 1 = 9
2 counters: 5 + 2 * 2 + 2 = 11
3 counters: 5 + 3 * 1 + 3 = 11
4 counters: 5 + 4 * 0 + 4 = 9

**Comment by osiridecascioli** [comment]
There is an Updated F.A.Q. on the FF site
https://images-cdn.fantasyflightgames.com/filer_public/e9/49/e949d137-b885-437b-a13d-e29c12880f94/adn01_faq_eng.pdf (page 10)

103 IT Department
- Once triggered, IT Department results in a constant ability that continually tracks how many power counters are on the card.
- IT Department always gives a piece of ice +1 strength due to the token spent to activate the card ability, even if there are no other counters left on the card or IT Department is no longer installed.
Example: There are 5 tokens on IT Department. If the Corp spends 1 token, the ice has +5 strength (1 for the initial token + 4 for the token still on IT Department). If the Corp spends another token, now the ice has +8 strength (2 for the initial tokens + 3 for each of the two instances of the ability). If the Corp spent a third token, now the ice has only +9 strength (3 for the initial tokens + 2 for each of the three instances of the ability).

Hope this help.

**Comment by Balkmeister** [comment]
Guess i misread the card. Please close.
