### ISSUE TITLE
Near-Earth Hub Installing Top Card with Architect Prematurely Draws

### ISSUE THREAD

**Issue by scifantasy** [mtgred/netrunner#278]
If, as Near-Earth Hub, you fire Architect's subroutine to install from R&D and install the top card creating a new server, the card ends up in HQ instead of on the table.

As far as I can tell, this happens because the "draw" condition technically fires before the "install" condition, so the top card--the one intended to be installed--ends up in HQ, and therefore isn't there to be installed.

(In the best tradition of not teaching granny to suck eggs, I'll stop here...)

**Comment by nealterrell** [comment]
Can confirm that this happens because `:server-created` is triggered in `corp-install` before the card is actually moved to its new zone (server), so NEH handles the `:server-created` event while the card being installed is still in R&D. 

I can't speak to why the event is triggered before the server is actually created (@mtgred?). If it's necessary for some other interaction, then we could be clever and first `move` the card to some other zone (`:play-area`?) in Architect's subroutine, then trigger `corp-install`.

**Comment by nealterrell** [comment]
@DominicKexel I know you have been working on Architect. Would you like to tackle this one too?

**Comment by DominicKexel** [comment]
Sure, I'll take look

**Comment by percomis** [comment]
This issue is still in place and creates a whole lot of mess with Daily Business Show on the table. Any solution in sight?

**Comment by nealterrell** [comment]
Fix submitted in #500.
