### ISSUE TITLE
Daily Business Overdraw: Tech Startup Complicates Matters

### ISSUE THREAD

**Issue by scifantasy** [mtgred/netrunner#282]
As you can tell from #278 and #281, I have been dealing with a lot of Daily Business Show/Near-Earth Hub interaction. Here's the new one:

If NEH has Daily Business Show rezzed and a Tech Startup in play, and use TS after the Runner's turn to create a new remote, you will properly trigger DBS and get to draw the extra and choose. That's all good.

But then, when you hit Start Turn, you _again_ get an extra and choice. The Start Turn button resets the once-per-turn flag on DBS--even though Tech Startup technically happened at the start of the Corp's turn.

In conversation, @nealterrell mused on the idea of a flag on "when your turn begins" cards on the Corp side (Daily Business Show, Executive Boot Camp) that will, if any of those cards are active when Start Turn is clicked, separate out the Corp Draw step from Start Turn, giving an artificial rez window...that could work.

**Comment by nealterrell** [comment]
So I am finally working on this! I have a good prototype working as was discussed. 

[These cards](http://netrunnerdb.com/find/?q=x%3A%22when+your+turn+begins%2C+you+may%22+d%3Ac&sort=name&view=list&_locale=en) will have a flag that tells the UI to split the corp's turn into "Start Turn" and "Mandatory Draw" phases. If no such cards are present, then gameplay proceeds as currently. The abilities of each card have been reworked to be manually activated, with a message showing in the upper right corner to remind the Corp that they can use certain cards in this window. (It will name the cards that qualify.)

I am stuck on how to incorporate non-optional start-of-turn effects like Adonis Campaign. In 90% of use cases, the corp wants the mandatory effects to come first, so they get their Campaign monies before using Tech Startup or Executive Bootcamp. The one opposite test case we can think of is Blue Sun bouncing a Campaign before it runs out. If the Campaign fires automatically at Turn Start but Blue Sun is manually triggered, then the campaign will run out before the bounce can happen.

Two potential solutions:

1. Leave it like this. Blue Sun players already bounce before clicking Start Turn, and can continue to do so for Campaigns.
2. Do __not__ automatically fire mandatory start-of-turn effects until the corp clicks Mandatory Draw.  For each card with a mandatory start-of-turn effect, add an ability to manually trigger the effect (e.g., "Take 3cr from Adonis Campaign"). If this ability is not used, then it will be triggered automatically by Mandatory Draw. 

    Supports these use cases:
    
    * If you don't care about the order these manual effects trigger, just ignore them and click Mandatory Draw. They will happen in an arbitrary order.
    * If you need money from a Campaign to rez an ice with Executive Bootcamp, click the Campaign, take the credits, then click Bootcamp and resolve its effect. If you have other campaigns, they will grant credits on Mandatory Draw.
    * You can take one payout from a Campaign that has 2 payouts left, then bounce it with Blue Sun.

I like option 2. I like it because it also solves this problem:

* We don't want the UI to give away hidden information about the corp's cards. If a corp card causes the start-turn process to be split into a Mandatory Draw phase, we don't want to reveal that information to the runner. If Campaigns trigger automatically on Start of Turn, but an an asset is installed that causes Mandatory Draw to halt the corp's turn, then the runner will see log messages about the Campaign but won't see a message about the corp drawing until the corp moves to Mandatory Draw. That will be different than when the Start of Turn phase _isn't_ being split, as the runner will see Campaign money and the draw immediately. If Campaigns don't pay until Mandatory Draw is clicked, then the runner will get no information about the corp's hidden board state.

Finally, I am not sure if this Mandatory Draw phase should be triggered by __unrezzed_ assets. According to game rules, you cannot rez Execute Bootcamp etc. in the "Start of Turn" rez window and have its effect available during that window. With this rule enforced, you would not get the Mandatory Draw phase if your EBC is unrezzed when you click Start Turn. This is the correct from a rules standpoint, but potentially unforgiving from a gameplay standpoint. Players commonly forget to rez assets before clicking Start Turn, and this would eliminate the possibility of correcting their mistake prior to getting their Mandatory Draw. This is certainly the __current__ user experience, but perhaps can be improved. The justification for letting a player rez in this window would be the implication that they really wanted to rez at runner's turn end, before corp turn begins.

Thoughts?

**Comment by dinte** [comment]
I really like the second proposed setup, and it could possibly be expanded to help runners. Wyldside before MaxX, Drug Dealer before Daily Casts, etc. As long as you can automatically trigger the remaining, untriggered effect as soon as soon as the corp starts the rest of their turn it seems very usable.

**Comment by nealterrell** [comment]
Agreed. I think most of the problematic runner interactions would be solved by manually triggering one card (like Drug Dealer) and then auto resolving the rest.

**Comment by SevenCs** [comment]
I think the second setup is preferable.

**Comment by nealterrell** [comment]
This is my current list of cards that I have implemented the new start-of-turn phase for. We refer to this as "Step 1.2", as that is the FFG term for the window in which "when your turn begins" triggers. 

Cards generally fall into these categories:

1. A mandatory action at 1.2, whose effect can influence other 1.2 abilities (Adonis Campaign: take credits to pay for an Executive Bootcamp ice rez). 
2. A mandatory action at 1.2

### Corp

**Comment by gumOnShoe** [comment]
I like the category system that you have. For the "optional, but things you wouldn't want to do every turn", I still recommend highlighting them. When the ability is used up; remove the highlight so that people know the option is gone to use that ability again. If nothing is highlighted the system can move on automatically. 

_Potential Hiccups_
Personal workshop is both Category 1 and Category 3. You have the mandatory drip, but you also have the general triggered ability that you might use to drop things into play before drawing. I think you probably want to make sure that cards can be considered to be multiple types by the system. And you'll need to disambiguate what the click does when it could be "remove a counter" or "pay 1 cred" to remove a counter.

Personal Workshop highlights the primary usability concern that I have with this feature. Which is that a user intending to do something during 1.1 should be notified that they're in 1.1 and that this is the last chance to manually trigger "triggered abilities with a cost" before the "turn begins triggers" become available for selection.

I don't think notifying 1.1 needs to be difficult. When the corp hits "end of turn" the runner is in 1.1 and vice versa. So it may just be a rebranding of 1.1 which is needed. 3.2 (corp turn) and 2.2 (runner turn) might also similarly be upgraded at some point.

Maybe this is just a slippery slope and I'm asking for too much scope increase. I'll rely on you to draw the line, but users should understand that while they're in 1.2, they can't trigger normal abilities that have costs until they've finished everything. And if the system does not warn and note when this condition has ended it could be frustrating.

**Comment by Saintis** [comment]
Maybe an indication above the action list that states the current stage the player is in. Or states 1.1 at least.

**Comment by nealterrell** [comment]
Thank you for the thorough feedback! I appreciate it very much. The highlighting is something I will look into. I currently show a "toast" notification in the upper right with the names of all cards that can trigger during 1.2, but that isn't perfect. Still, the tech is there... somewhere.

For Personal Workshop, I currently have removed the "1 Cr: Remove 1 token" ability, leaving only the "X Cr: Remove X tokens" for general use. I then added "Remove 1 token (start of turn)" that falls in to Category 1. 

Also, the Category system is just my way of applying patterns to each card's implementation. Category 1 cards, for example, all follow a similar pattern in their implementation, but the "category" label itself does not appear in the codebase, so there's no worry about multiple classifications.

Your points about 1.1 vs 1.2 are good, but warrant a discussion on whether this feature should seek to enforce the rules 100%, or if there is wiggle room for ease of use. I lean towards the latter. For that reason, I currently don't restrict the Corp from rezzing Adonis Campaign during 1.2 and then taking credits from it... I believe the implication is clear that they intended to rez at 1.1 (or even Runner 2.2 -- discard). Yes, this allows some illegal plays, like taking credits from Adonis to pay for the rezzing of another Adonis. But it also allows greater flexibility in interpretation, because 90% of such plays would be valid if it was understood that the rez/paid ability was done during 1.1, and the trigger at 1.2. 

It would be possible to prevent rez and paid abilities when in 1.2... but that would mean no flexibility, so if you click Start Turn before rezzing your Adonis, there's no going back. (In meatspace, this happens so frequently that everyone [I think?] accepts what was really intended.) I already enforce that some (not all) 1.2 abilities can only be used during 1.2, particularly Category 1 abilities. Category 3 abilities are generally marked as once per turn, so if you miss 1.2 you can sometimes still trigger them during your turn. Again, this allows incorrect play -- you could use Aesop's after installing a Cache and taking its credits. Your opponent would have to know the rules and explain why that's not valid, because the software wouldn't enforce it. But that's how things currently are, and I think it's better than being completely unable to trigger an ability because we don't have an "Undo/Go back" feature and you missed the one window in which the software allows you to use Aesop's. 

I lean towards incomplete rules enforcement, leaving much up to the players, but allowing for the correction of mistakes that are obvious. Thoughts?

**Comment by gumOnShoe** [comment]
Go with the general philosophy of J.Net. Whatever that is. But keep in mind that a lot of players are learning on the site and that they often think that what Jnet allows is how the game works (or maybe I'm just being trolled). I feel like the system is at a point where its probably better to agree upon a philosophy if you don't have one yet. Be like OCTGN and rely on users to understand game intricacies, or just do it right and users don't have to understand the system on the level you would need to at a real table.

It depends entirely on what you're trying to accomplish.

**Comment by nealterrell** [comment]
:+1: Historically, Minh has been in favor of simplified UI over exact mechanics, which is why we don't have a UI window for 4.3 in a run. 

Perhaps a large red WARNING message when someone rezzes or uses a paid ability in 1.2, explaining that their action is technically invalid and should have been done prior to hitting Start Turn.

**Comment by nealterrell** [comment]
Submitted in #1218.
