### ISSUE TITLE
Crypsis trashes itself at zero counters after passing ICE it didn't interact with

### ISSUE THREAD

**Issue by arjungm** [mtgred/netrunner#2909]
Steps to reproduce:
* create a remote server
* put a porous ICE over it (Hunter in HB)
* run on it with crypsis installed with zero counters
* pass the ICE with "No More Actions"

Observe that Crypsis will trash itself.

**Comment by danhut** [comment]
I could not reproduce this at all.  Looking at the code - we clearly only trash Crypsis if it was used during the run.  Unless you can provide other steps to reproduce I won't be able to help.  Any ideas?

**Comment by nealterrell** [comment]
For the record, this issue occurred because we do not remove custom keys from cards when those cards move zones. The custom `:crypsis-broke` key, once set to true, remained associated with Crypsis even after the card was trashed and then reinstalled, perhaps by Clone Chip, Levy, etc. So a Crypsis that trashed itself from a lack of counters and was later reinstalled would unpreventably trash itself after each encounter.
