### ISSUE TITLE
Suggestion: other playing leaving notification in chat log

### ISSUE THREAD

**Issue by percomis** [mtgred/netrunner#294]
I'm not sure how to send suggestions, but this would be great. Often you are unsure if you're opponent left or is still there, so it would be really good if there was a "Your opponent left the game." message, just like one for disconnecting/reconnecting.

**Comment by Balkmeister** [comment]
second this. There used to be a notification for this, not sure why it was removed

**Comment by mtgred** [comment]
The "disconnect", "reconnect" and "left game" notifications are bugged at the moment. It is added to the message log when the event happens but the update log is not sent to the other player. Fixing the problem is in the todo list.

Meanwhile you can check the status by writing a test message in the chat to refresh the message log. Another work around is to go to the game lobby with another browser tab to check if you are alone in your game or not.
