### ISSUE TITLE
CTM versus By Any Means crashed the game

### ISSUE THREAD

**Issue by hencook** [mtgred/netrunner#2999]
Corp had installed an _AR Enhanced Security_ agenda into a naked remote. Runner played _By Any Means_, accessed said agenda, and the game just sorta crashed.

**Comment by butzopower** [comment]
I wrote up a failing test for this (it doesn't matter the agenda):

```clojure
(deftest by-any-means-ctm-crash
  (do-game
    (new-game (make-deck "NBN: Controlling the Message" [(qty "Paper Trail" 1)])
              (default-runner [(qty "By Any Means" 2)]))
    (play-from-hand state :corp "Paper Trail" "New remote")
    (take-credits state :corp)
    (play-from-hand state :runner "By Any Means")
    (run-empty-server state "Server 1")
    (prompt-choice :corp "No") ;; Don't trigger CTM trace
    (is (empty? (:prompt (get-runner))) "No prompt to steal since agenda was trashed")
    (is (= 1 (count (:discard (get-corp)))) "Agenda was trashed")
    (is (= 0 (count (:hand (get-runner)))) "Took 1 meat damage")))
```

After doing a bit of debugging with other identities, I think the problem is that the `resolve-trash-end` for the agenda happens after `handle-access` due to waiting for the `runner-trash` event on CTM to resolve, and so the card is still considered in the same zone and `handle-access` doesn't short-circuit.  You can actually see this by running the test with some logging if you don't have the corp answer Yes / No to the trace (`handle-access` is still called and therefore the agenda is accessed / stealable).

No idea what change would be needed, since I'm still very much wrapping my head around this codebase, but maybe that's a useful starting point?

**Comment by nealterrell** [comment]
That is useful, thank you. I think By Any Means (BAM 😁) needs to wait for `trash` to finish before triggering `damage` (and therefore marking its own effect as complete). `handle-access` has protection against showing a Steal? prompt if an accessed agenda was trashed, but that code isn't triggering because the trash effect doesn't move the agenda to archives until the CtM trace completes. (Exactly as you said.) BAM needs to not resolve itself until the trash is resolved, which will prevent the `:pre-access-card` event from returning back to `handle-access`.
