### ISSUE TITLE
Auto-scrolling history makes it difficult to hover over linked cards

### ISSUE THREAD

**Issue by harrisont** [mtgred/netrunner#3010]
Hovering over a history-linked card:
![image](https://user-images.githubusercontent.com/144260/35213688-52b30508-ff13-11e7-8463-1ae5ebc54c2b.png)

Players take actions, causing the history to auto-scroll the text up, which changes the hover selection, thus preventing reading the card:
![image](https://user-images.githubusercontent.com/144260/35213693-56377b0a-ff13-11e7-9873-98da4e2e4828.png)

This is particularly painful:
 * As a new player, that doesn't recognize cards by name and needs to read the cards frequently.
 * When spectating and reading history-linked cards from either player's actions.
 * When playing and reading history-linked cards from the opponent's actions.

Potential solutions:
 * Have an option to disable history from auto-scrolling.
 * Have an option to disable history from auto-scrolling when your mouse is in the history box.
 * Other?

In these solutions that disable history from auto-scrolling, when the player/spectator is done reading/hovering-over-links and wants to see the most recent history, they can either manually scroll down or re-enable auto-scrolling.

**Comment by jwarwick** [comment]
I took a shot at making the autoscroll smarter (35f3b958e9f4a2fdbb5f055cfc677b10d419e072). Sadly, it turned out to be flaky for various browsers/zoom levels, so we backed out the changes (fa77b85ff18ce15bb529a8050bc95ac2e7c57bad). I think the problem is with the code to detect when you are at the bottom of the view, but haven't had time to go back and try to fix it.

**Comment by NoahTheDuke** [comment]
This is fixed.
