### ISSUE TITLE
If Shi.Kyu is trashed while being accessed, it will not end up in the Runner's score area.

### ISSUE THREAD

**Issue by JoeyKL** [mtgred/netrunner#303]

**Comment by JoelCFC25** [comment]
Tested out Shi.Kyu just now--this only happens when the Runner accesses one of these installed in a remote. When you hit one in R&D the "take damage or -1 agenda point" prompt is correctly ignored, and when you hit one in Archives or HQ that prompt correctly appears first. 

For some reason, only in a remote the Runner prompt to trash Shi.Kyu is getting priority over the Corp-initiated prompt. The workaround for now is for the Runner to choose "No" when hitting one in a remote--that will let the other procedure play out properly.

**Comment by javel-by** [comment]
Similar situation, but when runner accessed Shi.Kyu from HQ.
I think, he choosed to trash it first and then made choice about net dmg/agenda area. Shi.Kyu ended in archives, but runner got -1 to the agenda points.

**Comment by JoelCFC25** [comment]
Fixed at #914.
