### ISSUE TITLE
Tori Hanzo Breaks Net damage

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#3176]
Hi dunno if this has been brought up before or not but this seems quite consistent whenever Tori Hanzo triggers to replace Net with Brain from that point on Net damage no longer makes the runner discard at random it still appears in log but nothing happens.

I had been using it with Hokusai Grid &/ House Of Knives in case it's linked to those cards.

**Comment by PesiTheWizard** [comment]
To make sure I understand you correctly, do you mean that you use House of Knives, Tori makes it brain, then Hokusai doesn't do damage? In what other situations does this happen?

Does that it "still appears in log" mean that 'Corp uses Hokusai Grid to do 1 net damage' without 'Runner trashes Card due to damage'?

In relation to a previous bug, do you ever see Hokusai Grid logging 2 damage from a single run?

**Comment by JoelCFC25** [comment]
Galactic-sized sigh. I can barely bring myself to look at this project at all anymore, and I for damned sure can't bear to struggle with Tori Hanzo *AGAIN*.

**Comment by PinkWarrior** [comment]
@PesiTheWizard yes that is correct Tori makes makes the first Net brain and then for the rest of the game net damage doesn't do anything the 'Corp uses Hokusai Grid to do 1 net damage' still appears in the log along with anything else that deals Net damage but nothing actually happens.

@JoelCFC25 ah i hadn't realised it was such a sticking point i just was playing and the bug occurred seemingly every time so i felt i should report it. I am not a programmer my self so reporting bug is all i can really do to help out.

**Comment by PinkWarrior** [comment]
@JoelCFC25  well i can certainly understand that, wasn't it ruled at one point that even if the net was prevented it could still do the brain. I know it's had some silly rulings in the past.

**Comment by PesiTheWizard** [comment]
This certainly explains a lot about the results of the latest UCF test [(#2619)](https://github.com/mtgred/netrunner/issues/2619#issuecomment-362761542)

**Comment by JoelCFC25** [comment]
I can tell that `:damage-replace true` is not being dropped from `[:damage]` in state after Tori usage, which short circuits `resolve-damage`. Compare to answering "no" to Tori, which does dissoc this key. There has to have been a reason for this, but it's lost from my memory.

**Comment by JoelCFC25** [comment]
Here's what you can do to grab the glory: 

We need to add `(swap! state update-in [:damage] dissoc :damage-replace)` towards the end of the `resolve-damage` function. Make it the penultimate line, for example. 

In that same `resolve-damage` function, you can slip the type of damage into the card trashing message:   
`(str "trashes " trashed-msg " due to " (name type) " damage")`
