### ISSUE TITLE
Persephone + AR-Enhanced Security

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#3183]
With a copy of AR-Enhanced scored, Runner usage of Persephone should result in gaining a tag if it's the first Runner trash of a Corp card that turn. Currently Persephone is doing: `(mill :corp target)`, which only moves cards from R&D to the discard and never generates a trash event.

**Comment by NoahTheDuke** [comment]
This seems like an issue with `mill` moving cards directly into the discard instead of doing some sort of short-form trashing. I'd try switching it out for `trash`, but that then interacts with the entire lattice-work that is "the Runner trashing things they access", which isn't directly what this is. Maybe borrow the `trash-no-cost` functionality, without the scoring agendas bit? Or `resolve-trash-no-cost` without the `card :seen true` bit, because the cards are trashed facedown.
