### ISSUE TITLE
Tinkering + Ankusa bug (Tinkering counter does not clear at end of turn if in grip)

### ISSUE THREAD

**Issue by dezigerator** [mtgred/netrunner#3193]
If Tinkering is played on a piece of ICE that is bounced by Ankusa, it doesn't clear the Tinkering counter at the end of the turn and still has it if it is reinstalled.  It disappears only if installed at the end of turn.

**Comment by danhut** [comment]
I fully regret adding that icon now ;)

**Comment by nealterrell** [comment]
You brought this upon yourself, @danhut !

**Comment by danhut** [comment]
This needs a re-write of `remove-icon`.  Having thought about it... this could happen any time the ICE is moved or trashed.  In fact trashed is worst since all custom keys in it are wiped when it is moved to discard - and these keys are needed for the `remove-icon` to work.

Was someone working on creating a new "master" key to custom keys to get nested in and not cleared?  I think so but forget...

**Comment by JoelCFC25** [comment]
Yeah, it's `[:special]` created in a card. Look at Test Run for example.

**Comment by nickbrown10** [comment]
There is a similar issue with Laamb and Ankusa. 

Steps to recreate:

1. Runner has Laamb and Ankusa installed
2. Make a run on a server with a non barrier ice protecting server
3. Pay 2 with Laamb to make that ice gain barrier
4. Use Ankusa to break ice subs and add to HQ
5. Corp reinstalls same ICE protecting any server
6. Runner runs that server, Corp rezzes that ICE, but runner is unable to Pay 2 with Laamb

**Comment by lostgeek** [comment]
This could be related to #4039
