### ISSUE TITLE
Medium and Nerve agent do not ask how many cards you want to access

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#32]
By the rules, I am permitted to access fewer than the maximum number of cards allowed by Medium or Nerve Agent if I wish, but that option is not given to me.

This is probably a pretty minor consideration as there aren't that many play-states where you want to access fewer than the maximum, but it does come up every so often (and accessing fewer could act as a decent work-around for Crisium grid not being implemented yet #31).

**Comment by tekyro** [comment]
I know this is an edge case but it's making problems with Wendigo when you try to disable medium for a run...

I assume the best way is to ask with a drop down how many cards the runner want to access, I don't know how difficult it could be to implement though...

**Comment by DominicKexel** [comment]
We need a way to bring the game into a state where it will wait for an answer of the non-active a player.

For example:

- At the start of the game, the game should pause for the corp until the runner has decided to mulligan or not
- When activating Jackson during a run, the game should pause for the runner until the ability is resolved by the corp player (yeah, I know, Jackson isn't implemented yet)
- When firing a trace, pause the game for the corp until the runner was finished boosting his/her trace

**Comment by JoelCFC25** [comment]
Choice of how many extra accesses is implemented at #881.

**Comment by josemgarcia** [comment]
I was playing with medium, and needed to use this feature (manually running using Jak Sinclair, which is not implemented yet), but it didn't work for me.

First, the message to warn the runner that he can choose fewer cards to access was shown before reaching the "successful run" prompt. Second, when I clicked on Medium, a virus counter was added (!), and when choosing the number of additional cards to access, the number I chose were actually added to the number of virus counters (!).

**Comment by JoelCFC25** [comment]
My first reaction is that this sounds like a mix of the old and the new functionality--so either you or (more likely) your opponent had not done a forced refresh of the site (hold Shift while reloading in your browser) since the last server restart. This is really important to do every time you see that there's been a restart as indicated in the News header. 

The site currently compresses multiple steps of the timing chart into one for the sake of reducing player back-and-forth. The way the access code works, there is no way to block the execution of everything else on the `:pre-access` event trigger, so it's impossible to have this new Medium prompt come up after hitting "Successful Run" and still work. Since there is a pause after the Corp has hit "No more action" for the last time, doing the prompt and having the Runner set the number of additional accesses right before hitting "Successful Run" is basically the same thing. 

If you try Medium in a private test game against yourself with a second account in another browser (both of them having done a forced refresh), I'm pretty confident that it will work correctly.
