### ISSUE TITLE
Feature: Connection Keep Alive 

### ISSUE THREAD

**Issue by SephiTrax** [mtgred/netrunner#340]
Hey,

We're trying to play from work (yeah yeah, we have some relaxed hours), but every time we idle for more than 10 minutes, the server disconnects. Though it reconnects, we're not able to resume our game.

Can you implement some keep alive feature? Like keep the game up for max 60 minutes and if there's not activity only then disconnect?

**Comment by JoelCFC25** [comment]
> Can you implement some keep alive feature? Like keep the game up for max 60 minutes and if there's not activity only then disconnect?

This might run counter to some of the server side changes that reduced the amount of data pushed to clients and thereby significantly improved peak time lag.

**Comment by SephiTrax** [comment]
A keep alive "ping" should not cause that much of a problem. But I don't know the server structure/speed so it might be.

Just saying, if it can be added, that would be gold.

**Comment by olompumpa** [comment]
We have a reoccurring problem: a lot of games are suddenly disrupted because one of the players becomes disconnected. It can be read in the log that the player is disconnected, and also that an attempt for reconnection is in progress, and finally that the player is reconnected. Still, reconnection does not really happen. Although the player tries to make some actions, nothing happens any more. When trying to refresh the site, the disconnected player gets out to the play platform, where he or she can see the game among the others, but cannot enter again.
Did we do something wrong in such cases? Have others also faced this problem? Can you suggest us something?  For instance, which type of browser should be used (if not chrome)? Is there a solution for this very annoying problem, is it a real error at all? If it is, and there is not yet a solution, can one be expected in the not so distant future?
