### ISSUE TITLE
Trashing a hosted card triggers its "gain MU" leaves-play clause, even when it shouldn't

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#350]
If a program is hosted on a card that reduces the number of MU the hosted card takes up (cards like Djinn, Leprechaun, Dinosaurus, etc), and the hosted card is trashed, you gain "back" the MU that the card would be taking.

So if Kate has Dinosaurus installed, puts Garrote on it, then trashes Garrote with no other programs installed, she'll gain the 2 MU that Garrote would have taken if it weren't hosted, going up to 6 MU available.

**Comment by JoelCFC25** [comment]
This one might be tricky, because the MU savings granted by these special hosts are given by the host card (e.g. you *gain* MU equal to the hosted program instead of stopping MU from being lost). But then the MU gain from a program trash occurs when the *program* leaves play--so it would somehow need to look back and see if it had been installed on one of the special hosts.

**Comment by nealterrell** [comment]
It will probably be easier for these cards to handle the `:card-moved` event, which triggers any time a card moves zones. See if the card moved was the card previously hosted, and then update MU if so.

**Comment by JoelCFC25** [comment]
I have Dinosaurus fixed to do this correctly. Leprechaun and Djinn should only need a slight modification since they can host multiple items.
