### ISSUE TITLE
Chat log sequencing for Team Sponsorship installs is not clear.

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#3542]
I'm frequently confused by the sequencing of the chat log for team sponsorship reinstalls/installs, such that it's hard to work out immediately which card is installed into which server. We've just chatted about it on slack and others feel the same way. Could this be looked at?

**Comment by nealterrell** [comment]
Can you give me an example? I just ran this brief test, in which I scored a Hostile Takeover with a rezzed Team Sponsorship to install a card form archives:

nealpro spends  and 1  to advance a card in Server 2.
nealpro uses Team Sponsorship to install an unseen card from Archives.
nealpro installs a card in Server 3 (new remote).
nealpro uses Hostile Takeover to gain 7  and take 1 bad publicity.
nealpro scores Hostile Takeover and gains 1 agenda point.

Can you describe how you'd like that improved? (The "gains 1 agenda point" line is last due to technical reasons... because Project Beale does not calculate its agenda points until its When Scored trigger resolves, we don't print how many points you gain until that trigger goes through.)

**Comment by Eric-Fletcher** [comment]
That order ends up being mildly annoying when scoring the winning agenda, and needing to click through all the "scored triggers" before the game ends.

It's more of a issue with the log when there are multiple team sponsorships running, and maybe you're installing upgrades?

**Comment by tolaasin** [comment]
Very much more an issue with multiple installs and triggers. 

Perhaps this is a sublety, but 'nealpro uses Team Sponsorship to install an unseen card from Archives into Server (new remote) would be clearer.
