### ISSUE TITLE
Suggestion: A player ranking system. Feature request

### ISSUE THREAD

**Issue by lpoulter** [mtgred/netrunner#355]
It would be great if players had a ranking either elo or gilcko. This could be used to find even skilled opponents and to track your own performance.

**Comment by eah13** [comment]
In addition to skill, a rating of sportsmanship or etc would be nice and along the lines of #354

**Comment by nealterrell** [comment]
As someone with personal experience implementing a ranked ladder system for an otherwise casual online play community... I recommend passing on this. Once you attach a number to wins/losses, people get very aggressive and antagonistic over matches, even more than what we're already seeing. And as long as we have many unimplemented/bugged cards, we'll get no end of complaints about losing e-Penis Points due to site errors, demanding that points be adjusted manually, etc. 

I think a better solution has been proposed: adding self-chosen labels to games, along the lines of "Beginner", "Intermediate", "Advanced", "Tournament", etc.

**Comment by DominicKexel** [comment]
I'll agree with @nealterrell here. Let's keep it casual by default, so we maintain a friendly environment. 

I could think of keeping some anonymous statistics like number of plays/wins for each fraction/deck like OCTGN does...

**Comment by thehunter518** [comment]
Could implement a selection of  buttons for game creation that accomplish the same thing as typed labels, but with a standardized meaning (like the beginner/intermediate/advanced suggestion). This could be implemented in a way that was more visually obvious in the games lobby (e.g. all "beginner" games are highlighted green, or have a special icon) and could theoretically be used to filter desired game types.

Downsides? (other than a lot of extra programming work) 
Without an actual matchmaking system, people could just lie about their experience level in order to lure in less experienced players. While you can technically still do this now, the suggested system would enable people to do it more readily.

**Comment by athayn** [comment]
i have to third @nealterrell. skill and sportsmanship ratings will make the jinteki atmosphere more competitive. the anonymity of online play has already brought out [hostility and harassment](https://github.com/mtgred/netrunner/issues/356). do we want it to feel like league night, a tournament, or casual play?

**Comment by DominicKexel** [comment]
At least I want a way to report rage quitters. Maybe add a :-( smiley to the user name if someone joins your game that was reported several times as rage quitter or douche bag.

**Comment by zaroth** [comment]
A tiny bit in this direction was done in the room split in #1215 (it's worth to read mtgred's comment there, too). However, we are still quite far from a full-blown ranking system, soon I'll try to write up a proposed roadmap for that.
