### ISSUE TITLE
Code of conduct & enforcement

### ISSUE THREAD

**Issue by eah13** [mtgred/netrunner#356]
Jinteki is an awesome community.  Let's keep it that way with a statement of how community should behave and what will happen if they don't. Homophobia, racism, sexism, and other kinds of hate speech are an unfortunately reality on the internet and [our community is no exception](http://imgur.com/TwEpee1).

Let's start a discussion on this.  There's lots of ways to go, the first of which is a code of conduct.  From there enforcement can be ad hoc at the DB level (deactivating accounts) to some sort of karma system. "Was [user] a courteous opponent?" or something would let the positive community members be shown as such over time.

Anyways the point isn't that someone said something homophobic to me.  It's that there is at least one person like this in our community which means it's time to say what we're about.

[The Python Code of Conduct](https://www.python.org/psf/codeofconduct/) is an awesome starting point I'd suggest.  Open. Considerate. Respectful.  That's a nice summary of what Jinteki should be too.

**Comment by DominicKexel** [comment]
I would support this. This week I played against some dude who was clearly a noob, played slow and did a lot of mistakes. I told him that he could just take back bis actions (he once tried to combine an inside job and an account siphon etc.) and that we could play core  set only if he wants, and he was impressed by my behaviour. He told me he was afraid that when he had told me upfront that he is a noob I would get angry because he had made a lot of negative experiences in other online communites. 

Let's ensure that people have a posivite experince on jinteki.net!

While I don't think it's an urgent  problem (I never had a negative experience  on jinteki.net), I heard that rating your opponent after the game really helped other online games that had serious problems with the behaviour of their players.

**Comment by thehunter518** [comment]
I've been playing since August 2014, and while I have met my share of rude, disrespectful, and verbally abusive players, I would say that they are by far the exception. I've always been impressed with this community's ability to more-or-less regulate itself by just ignoring the bad eggs, and while it's certainly grown more popular recently (and thus much larger), I would much rather promote that type of individual responsibility.

I like the idea of a very minimalist code-of-conduct, whose message was "Please respect each other" instead of "Please respect each other OR ELSE". What I personally wouldn't support is full-on moderating and the handing-out of punishments. I think that is a classic "best intentions" scenario that can do a great deal of harm to the community.

**Comment by NoahTheDuke** [comment]
Someone is welcome to PR a code of conduct! In an effort to clean up the backlog, I'm going to close this for now.
