### ISSUE TITLE
Laramy Fisk and Jinja City Grid: Fisk ability and access happens twice if ICE is drawn

### ISSUE THREAD

**Issue by demoy** [mtgred/netrunner#3577]
If Jinja is rezzed, and they draw an ICE from Fisk's ability: I receive the option to use Fisk's ability again (regardless of whether they use Jinja to install the ICE). Also I see the access prompt again immediately after the first access. I observed this behaviour across 4 different matches.

**Comment by nealterrell** [comment]
This will require some digging.

**Comment by nealterrell** [comment]
OK, I am fairly certain this can be played around by pausing for a few seconds after you Fisk. The Corp is seeing a prompt to install the card they drew, and because nothing is shown to the runner, the run UI defaults to the Successful Run prompt. Just don't click that and things should resolve once the Corp makes their choice. 

In the longer term, I suppose we should add a wait-prompt to the runner if Jinja is installed, similar to the discussion in #3607.

**Comment by nealterrell** [comment]
Nevermind, we'll go with the approach recommended in #3607 and show a "waiting" prompt when drawing with Jinja on the runner's turn, and a fake-out prompt when you don't draw any ice (also on the runner's turn).
