### ISSUE TITLE
Starting Splash Screen

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#3797]
The Splash Screen at the beginning, along with the quote, is quite cool!

What went behind the decision of the quote being for your identity instead of your opponents? If there's not room for both, then surely you'll see a larger variety of opponent IDs than of your own. Besides, your opponent is talking to you, you're not talking to yourself!

**Comment by nealterrell** [comment]
You can click the opponent ID to see their quote! 

We went with this direction because lore wise, the Corp doesn't know who's hacking them and wouldn't be directly communicating with the runner. The corp quotes are motivational to the Corp player, as if you're a mid level exec or sysop getting geared up to stop an attack.

We are working to have unique quotes for each matchup! It will take some time, but then you'll have a ton of variety for your quote :).
