### ISSUE TITLE
Psych Mike not triggering

### ISSUE THREAD

**Issue by Chemscribbler** [mtgred/netrunner#3828]
Not sure if this is just after an Akiko Nisei Psi game, but Psych Mike did not generate credits after an R&D access

**Comment by hiddenaway1** [comment]
I checked it and it does generate the credits (bear in mind it has to be the first successful run on R&D that turn, not just the first after Psych Mike is installed). However, there is no message in the chat  to indicate that credits are gained. Checking the code, here's no ":msg" code for Psych Mike.

Don't know if that's by design or just forgotten in the rush to implement the card.

(Tested with a dummy deck firing a Maker's Eye with Psych Mike installed)

**Comment by Saintis** [comment]
Can also confirm Psych Mike only triggered if it was the first successful run off the turn as well.
