### ISSUE TITLE
Sundew is broken

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#3955]
Not running on a sundew server first click does not give the corporation 2 credits.

**Comment by HongkongKoma** [comment]
For me, several games froze and I highly suspect Sundew to play a part in this. I tried to leave -> refresh Browser -> rejoin and then suddenly when I started my turn, it instead started the opponent's turn! And all chat messages were doubled. After trying this again in hopes to fix it, I conceided - but instead, the chat said my opponent conceided.

**Comment by NoahTheDuke** [comment]
Currently, Sundew is unimplemented: [assets.clj](https://github.com/mtgred/netrunner/blob/348c522a3549c87ed0de6001777fc656725113e7/src/clj/game/cards/assets.clj#L1738). The reason is we changed how we handle spending clicks and initiating runs, which made it more difficult to make Sundew work as intended. I hope to fix this when (some day in the far future) I can revamp run timings, but until then, we're stuck manually doing this one.
