### ISSUE TITLE
Undo click with Patchwork

### ISSUE THREAD

**Issue by 5N00P1** [mtgred/netrunner#3986]
when doing /undo-click everything was reverted back, but the card I used to feed to Patchwork, it was still in the heap, so undo click is not undoing the click.

**Comment by NoahTheDuke** [comment]
That’s super interesting , I wonder why! Thanks for the report, I’ll take a look

**Comment by NoahTheDuke** [comment]
I found the bug, and it has to do with the way we currently track clicks and handle the `undo-click` functionality. It looks like we encode the previous click's state at the moment before we spend a given click, which makes sense but means that "resetting" a given click doesn't undo any non-click abilities (which Patchwork currently counts as, because of the way we had to implement it).

I have a thought on how to fix it, but it's more than the quick fix I originally expected.

**Comment by NoahTheDuke** [comment]
Closed with #4262
