### ISSUE TITLE
Erm... Amani Senai, Arabyata, Freedom Through Equality and Legwork?

### ISSUE THREAD

**Issue by mcgreenhalgh** [mtgred/netrunner#4074]
I had Freedom Through Equality in play. I Legworked. On access the corp rezzed Amani and Arabyata. I accessed Traffic Accident, so nothing happened. Then I accessed AR Enhanced, so stole it and added FTE to my score area. Then it all went wrong.

Amani fired with a base strength zero, which we thought might be an FTE glitch? So we tried to resolve it but it seemed to keep refiring. We were able to close-prompt out of it. But the only options it gave me were for Successful Run and Jack Out, and neither of them were responding. Nothing responding on Corp side either, and close-prompt didn't work either. We had to abandon ship.

I was running as Kit, which I doubt is relevant. But the corp was Sol, which may have thrown another trigger into the mix.

**Comment by presheaf** [comment]
Oops, part of this is on me. As seen in the definition of Amani Senai (https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/assets.clj#L140), she currently gets the advancement cost by assuming the stolen/scored agenda is the last one in score area, but that is probably going to be FTE. So that explains why the base trace is off, and is easy to fix (if the agenda-stolen/scored events do not already pass the agenda as a target, that needs to be added, but is not too hard).

What's weirder to me is that the prompt sticks around. It will likely be the case that the advancement cost is `nil`, making the base trace `nil`, but I think that should be fine. So I would bet either Sol, Arabyata or the fact that Senai fires mid-Legwork is the issue here. (I also notice from the screenshot you shared that Comet was in play, which I doubt is relevant but is worth noting.) Maybe Amani needs to be async?

**Comment by NoahTheDuke** [comment]
I have a “fix” for this that I wrote up for my optional branch. Lemme see about adapting it

**Comment by presheaf** [comment]
Oh, you know what the issue is? Please share!

**Comment by NoahTheDuke** [comment]
Maybe! I rewrote Amani cuz it’s not written well and in doing so found a bug and fixed it, so we’ll see!

**Comment by NoahTheDuke** [comment]
Turns out I didn't have a fix, but I think I found a solution anyways. We'll see!
