### ISSUE TITLE
Mr. Li dumps part of hand into trash

### ISSUE THREAD

**Issue by salavant** [mtgred/netrunner#41]
A few times, when using Mr. Li, normally when I have a nearly full hand, the card I wanted appears in my hand, but about 3-4 cards that were in my hand are dumped into trash, and I have to manually drag them back (visible to corp). This happened with a hand size of 5 or 6 cards.

**Comment by mtgred** [comment]
If you decrease the zoom level of your browser, there was a issue that would cause the 6th card in hand to disappear if you have exactly 6 cards in hand. This issue is now fixed.

This is unrelated to Mr. Li but i believe you had 5 cards when using Mr. Li bringing your to 7 cards. When putting 1 card back you would have 6 cards in hand causing the 6th card to disappear. Everything should work fine now.

**Comment by JoelCFC25** [comment]
I can't get this to happen anymore, so I'm closing it.
