### ISSUE TITLE
Blueberry Diesel showing only one card

### ISSUE THREAD

**Issue by JeffMol** [mtgred/netrunner#4132]
Played a Blueberry Diesel and saw only two options when asked if I wanted to choose a card to put on the bottom of the stack, the options being 'Diversion of Funds' and 'No'.  Chose No and drew two Diversions.  So if Blueberry Diesel sees two of the same card, it only gives the runner the option of that card.  This gives the impression that the card is bugged since it's not readily apparent to the player what's happening.  Please change this.

**Comment by NoahTheDuke** [comment]
Thanks for the report! We’ll get that fixed quick.

A word, tho. In the future, saying “Please change this.” is at best redundant because if it’s a real bug we will work on fixing it. At worst, it’s demanding and rude, as all of us who work on jnet are volunteers who do this for the love of the game.

The rest of your report is clear and helpful, so I appreciate you taking the time to write it, but I’ll ask that you leave off comments like the final sentence in the future. Makes me feel bad.

**Comment by JeffMol** [comment]
Yeah, no problem.  Like I realize it's not really a bug, more of a request,
so I tried to demonstrate that I knew that without being like "this is
dumb, why u do dis?"  Sorry if I still ended up coming off as rude, not
sure where else to really request feature updates like this.

**Comment by JeffMol** [comment]
Also you guys are all awesome and I love you.  Things have come a long way
on jnet over the years.

**Comment by NoahTheDuke** [comment]
No worries, and no harm done! Like I said, I appreciate you taking the time to come to github and write a bug report. It's super helpful.
