### ISSUE TITLE
Screen frequently goes black while playing

### ISSUE THREAD

**Issue by Erenoth** [mtgred/netrunner#4153]
For the last week since the new cards dropped my screen will randomly go completely black while playing. Can't determine any particular pattern. I've had to leave the game, refresh, then rejoin to continue but its been happening so frequently that this doesn't really work.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

Next time it happens, could you open the Dev Console and take a screenshot of whatever error is displayed? This is a tricky one we’ve had a lot of trouble replicating.

**Comment by Erenoth** [comment]
![image](https://user-images.githubusercontent.com/48885392/54881766-bcd1c300-4e29-11e9-8722-b67066d4402a.png)
think this is what you mean?

**Comment by Erenoth** [comment]
![image](https://user-images.githubusercontent.com/48885392/54881772-e5f25380-4e29-11e9-9215-b3c487e01c49.png)
this is what the screen looks like

**Comment by Erenoth** [comment]
Since this issue doesn't seem to be affecting most players is there something specific about my settup thats causing this? I've tried reinstalling java and clearing out my history to try and fix this, is there anything else I can try to avoid this issue?

**Comment by NoahTheDuke** [comment]
Are you using jankteki or anything similar? That might be causing issues? I’m honestly not sure

**Comment by Erenoth** [comment]
I have never heard of jankteki but I'll try disabling some other things and see if that helps. Its been happening on both chrome and firefox.

**Comment by Erenoth** [comment]
So after trying a few different things disabling a thing I have for MtG called autocard anywhere I now seem to be able to get through a few games, haven't seen the screen go yet. Hadn't thought of trying without that since its for a different game and shouldn't matter for netrunner. Thanks!

**Comment by ZomBagus** [comment]
Had black screen happen in Edge browser mid game this morning at approx 0925 BST. Was switching between browsers and when I switched back the screen was black. Tried F11 to exit and enter full screen - had no effect.
Console: 
44 WEBAUDIO17055: Cannot set buffer after it has been already been set. howler.min.js (2,20145)
2 SCRIPT5: SCRIPT5: Access is denied. play (169,194)

On refresh and rejoin screen was still black. Console was:

(i) HTML1300: Navigation occurred.
play (1,1)

(!) HTML1402: Character reference is missing an ending semicolon “;”.
play (3,88)

(!) WARN [taoensso.sente:904] - SECURITY WARNING: no CSRF token available for use by Sente

(!) 3 Warning: Every element in a seq should have a unique :key: ([zZ {:faction "Shaper", :format {:standard "legal", :eternal "legal", :core-experience "rotated", :snapshot "rotated", :snapshot-plus "rotated", :socr "legal", :classic "legal"}, :rotated false, :cycle_code "ashes", :runner-abilities [], :zone ["onhost"], :cid 369477, :new true, :added-virus-counter false, :art nil, :type "Program", :abilities [{:label "Make currently encountered ice gain a subtype"}], :image_url "https://netrunnerdb.com/card_image/26025.png", :title "Pelangi", :counter {:virus 1}, :uniqueness false, :host {:faction "Shaper", :format {:standard "legal", :eternal "legal", :core-experience "rotated", :snapshot "legal", :snapshot-plus "legal", :socr "rotated", :classic "legal"}, :rotated false, :cycle_code "mumbad", :runner-abilities [], :zone ["rig" "hardware"], :cid 369505, :art nil, :type "Hardware", :abilities [{:label "Install a program on NetChip"} {:label "Host an installed program on NetChip"}], :image_url "http://www.cardgamedb

(!) 3 Warning: Every element in a seq should have a unique :key: ([zZ {:faction "Shaper", :format {:standard "legal", :eternal "legal", :core-experience "rotated", :snapshot "rotated", :snapshot-plus "rotated", :socr "legal", :classic "legal"}, :rotated false, :cycle_code "ashes", :runner-abilities [], :zone ["onhost"], :cid 369477, :new true, :added-virus-counter false, :art nil, :type "Program", :abilities [{:label "Make currently encountered ice gain a subtype"}], :image_url "https://netrunnerdb.com/card_image/26025.png", :title "Pelangi", :counter {:virus 1}, :uniqueness false, :host {:faction "Shaper", :format {:standard "legal", :eternal "legal", :core-experience "rotated", :snapshot "legal", :snapshot-plus "legal", :socr "rotated", :classic "legal"}, :rotated false, :cycle_code "mumbad", :runner-abilities [], :zone ["rig" "hardware"], :cid 369505, :art nil, :type "Hardware", :abilities [{:label "Install a program on NetChip"} {:label "Host an installed program on NetChip"}], :image_url "http://www.cardgamedb.com/forums/uploads/an/med_ADN31_24.png", :title "NetChip", :uniqueness false, :host nil, :corp-abilities [], :normalizedtitle "netchip", :code "10024", :side "Runner", :cost 1, :subroutines [], :quantity 6, :installed true, :deck-limit 6, :implementation "full", :set_code "bf", :subtype "Consumer-grade - Chip", :previous-zone ["hand"]}, :strength 0, :corp-abilities [], :normalizedtitle "pelangi", :code "26025", :side "Runner", :facedown nil, :cost 1, :hosted [], :subroutines [], :quantity 3, :installed "this-turn", :deck-limit 3, :memoryunits 1, :implementation "full", :set_code "df", :subtype "Virus", :previous-zone ["rig" "program"]} nil])
 (in reagent10 > gameboard >  >  > TZ >  >  >  >  > zZ)
app10.js (1398,363)

(X) SCRIPT257: SCRIPT257: Could not complete the operation due to error 80020101.
app10.js (141,71)
