### ISSUE TITLE
Ability to reconnect to existing game

### ISSUE THREAD

**Issue by laganojunior** [mtgred/netrunner#418]
Sometimes, I lag out and I instinctively refresh the page. Now, I'm out of the game and see my poor opponent alone in the game that I can't come back to. It would be great if I could just reconnect to the game I was previously in from the lobby. It'll cut down all of those people complaining about opponents disconnecting from games in the chat.

I'm happy to try implementing this unless this conflicts with some internal architecture decisions.

**Comment by mtgred** [comment]
Sure go ahead.

What you can do is store the game id in the html5 local storage when a game starts. When a user leaves the game, the game id should be cleared. If a game id is present when a player go to the lobby there should be prompt asking if he want to rejoin the game. If not the game id should be cleared from local storage

**Comment by zaroth** [comment]
While tackling this issue, it might be worth to take a look at keep-alive issue #340

**Comment by olompumpa** [comment]
We have a reoccurring problem: a lot of games are suddenly disrupted because one of the players becomes disconnected. It can be read in the log that the player is disconnected, and also that an attempt for reconnection is in progress, and finally that the player is reconnected. Still, reconnection does not really happen. Although the player tries to make some actions, nothing happens any more. When trying to refresh the site, the disconnected player gets out to the play platform, where he or she can see the game among the others, but cannot enter again.
Did we do something wrong in such cases? Have others also faced this problem? Can you suggest us something?  For instance, which type of browser should be used (if not chrome)? Is there a solution for this very annoying problem, is it a real error at all? If it is, and there is not yet a solution, can one be expected in the not so distant future?

**Comment by JoelCFC25** [comment]
Should be much improved now.
