### ISSUE TITLE
Card name hover/highlight issues

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#429]
Minor issues from #424 today:

1. Usernames are being linked to cards. "TheCodeTroll" highlights and links Troll.
2. Gimoire links as Grim.
3. e3 Feedback Implants -> Imp.

![highlights](https://cloud.githubusercontent.com/assets/10083341/8998141/8bf21f70-36de-11e5-85d1-46cf714f3eb8.png)

**Comment by nealterrell** [comment]
Sometimes cards have strange output:
![image](https://cloud.githubusercontent.com/assets/10083341/8859649/59da84ec-3133-11e5-8bcb-8aad6cccbb68.png)

Saw this with Plascete Carapace and Grimoire as well.

**Comment by mtgred** [comment]
I had the same issue with Drive By played on Adonis Campaign.

Upgrades in remote servers are also positioned weirdly now (next to each other instead of overlapping).

<img width="1552" alt="screen shot 2015-07-23 at 20 57 17" src="https://cloud.githubusercontent.com/assets/284114/8859715/603ef5f6-317f-11e5-9160-edd142dbc2a7.png">

**Comment by mtgred** [comment]
I was just thinking Kati Jones, Plascrete Carapace, Adonis Campaign... it might be due to alternate art cards.

Grimoire has not alt art though.

**Comment by DominicKexel** [comment]
OK, the cards needs to be sorted before changing the message. I'll provide a patch later this evening.

**Comment by DominicKexel** [comment]
I proved a simply fix by using a regular expression with word boundaries. Don't know why I didn't do it from start.

"TheCodeTroll" should also no longer link Troll.

A user name that matches exactly a card title is still linked to the card. The question is: Is this worth "fixing" or should be keep this behaviour as easter egg?

**Comment by DominicKexel** [comment]
BTW, is jinteki.net up ATM? I always get a 522 error from cloudfare...

**Comment by DominicKexel** [comment]
Are you both running OS X? Just asking because I can't reproduce the issue where the card ID is shown in the log window. Makes me wonder if it's some kind of browser specific javascript issue.

**Comment by nealterrell** [comment]
Chrome on Windows.

**Comment by mtgred** [comment]
All the alt art cards consistently have the issue.

Dominic you have access to alt art cards on the live server. I'll mail you a json file to import then into your local db.

**Comment by DominicKexel** [comment]
@mtgred my email is my github username @gmail.com 
What's special about the alt arts? Is there just another image code used?

**Comment by DominicKexel** [comment]
I can't reproduce the issue with the upgrade positioning.

**Comment by JoelCFC25** [comment]
I'm seeing the side-by-side upgrades in the same remote in both Chrome and Firefox on Windows.

**Comment by mtgred** [comment]
The issue is still present with Chrome/Firefox on Mac OS. In the screenshot below, Jackson is in server 1, the 3 others in server 0 and the 3rd card can't be clicked.

But the card preview has been removed from the live server. So the positioning issue seem comes from elsewhere. I'm investigating the issue and will continue the discussion in #427.

![screen shot 2015-07-24 at 20 57 25](https://cloud.githubusercontent.com/assets/284114/8882369/a98cc860-3246-11e5-9061-9bae502d3151.png)

**Comment by mtgred** [comment]
@DominicKexel Regarding alt art, yes they have a different code starting with 005.

**Comment by DominicKexel** [comment]
@mtgred thanks, I found the issue. Since some cards are now multiple times in the `:card` collection, the card title in a message would get replaced multiple times, resulting in the strange behaviour seen on the live system. I changed it so that alt art images (`:setname "Alternates"`) are now preferred.

**Comment by queueseven** [comment]
@nealterrell I think this issue can be closed.
