### ISSUE TITLE
Pad Campaign triggers twice or don't trigger at all

### ISSUE THREAD

**Issue by Zulyen** [mtgred/netrunner#43]
During some games my PAD campaign triggers twice each start of a turn...
Other games, not triggering at all.
Same happened with Adonis Campaign and Marked Account.
For Marked Account, the credits stays on it when it didn't triggered.

**Comment by mtgred** [comment]
There was an issue with ability triggering not being removed when a card leaves play and then installed again (eg. Interns, Blue Sun). That would cause the ability to trigger twice. That problem is now fixed. 

There might be other issue causing abilities to trigger multiple times. So if you encounter the problem again please let me know.

**Comment by mtgred** [comment]
The issue causing the problem has been found and fixed. It shouldn't happen anymore.

**Comment by Zulyen** [comment]
Nice work ! Thx !
