### ISSUE TITLE
Firefox getting very slow

### ISSUE THREAD

**Issue by davide-ceretti** [mtgred/netrunner#431]
Firefox is getting very slow on a high end machine (8gb ram, 3.5ghz CPU) while playing a games. Task manager shows 5-20% CPU usage and 800mb of RAM used. When I close the Jinteki tab everything goes back to normal.

FYI I have never had this issue and I encountered it yesterday/today for the first time.

**Comment by DominicKexel** [comment]
How long was the game you played or did you play multiple games? Did the performance increase when you left a game?

Enabling the card preview in the log pane should increase memory since a lot of event handlers are created, but I had no performace penalties when playing in Chrome.

Nonetheless, I'll do some tests with firefox and see if I can do anything to reduce the memory demand.

**Comment by mtgred** [comment]
The card preview in the chat log has been deployed yesterday and might be the cause.

It has been removed today from the live server due to other issues (#427, #424). Can you try now and see if there is any difference in performance?

**Comment by davide-ceretti** [comment]
I don't remember how much I played or how long the game was, sorry. I'll try again and let you know how it goes.

**Comment by davide-ceretti** [comment]
It seems OK now, haven't had any issue in 5+ games,

**Comment by DominicKexel** [comment]
@davide-ceretti Some improvements have been deployed. The memory need should be reduced and the performance should be increased. Do you still have any issues?

**Comment by davide-ceretti** [comment]
@DominicKexel Nope, all good now!
