### ISSUE TITLE
Game freezes on Adonis auto-trash

### ISSUE THREAD

**Issue by limnrix** [mtgred/netrunner#4379]
A whole lot of things happened at once:
Adonis drops its last 3, but doesn't trash. Instead, the log shows the corp trashing, then the runner trashing 130 times, as recorded by an installed Gravedigger.
Corp cannot choose any other start-of-turn triggers.

<img width="1576" alt="Screenshot 2019-08-12 11 42 17" src="https://user-images.githubusercontent.com/30281448/62878494-2f6b0e80-bcf7-11e9-8bad-dde225dadb3b.png">
<img width="1572" alt="Screenshot 2019-08-12 11 41 43" src="https://user-images.githubusercontent.com/30281448/62878495-3003a500-bcf7-11e9-8baa-b978ea37b911.png">
<img width="817" alt="Screenshot 2019-08-12 11 40 37" src="https://user-images.githubusercontent.com/30281448/62878496-3003a500-bcf7-11e9-9438-62c360c5864b.png">

BTW, having the drop down menu for cards where the only option is rezzing is a lot of extra clicking and moving that makes the design way more clunky. Is there any way to implement an option for more experienced players to speed the interface up around that, and the ICE menus?

**Comment by NoahTheDuke** [comment]
The drop down menu thing is a mistake. We're going to keep it such that any rezzing requires the two clicks, because that's the safest way to avoid accidentally rezzing something, but otherwise all card-clicking functionality should be back to how one expects.

The Adonis trash issue is wild. I'll dive into that and see what I find!

Thanks for the report!

**Comment by limnrix** [comment]
Thank you Noah!
