### ISSUE TITLE
Ice encounter window cannot be closed during encounter: issue for some cards

### ISSUE THREAD

**Issue by MrCowbird** [mtgred/netrunner#4381]
I am having an issue that the new and improved ice encounter window (which I love, by the way) cannot be closed during an encounter. This can be a problem because the ice encounter window can block other cards. Thus far, this has lead to two problems:

1. The window is in the way when you are asked to select what ice you want to rez for Architects of Tomorrow.
2. The window is in the way when you are asked to resolve a subroutine on another ice, like you might do for Ravana or Wormhole.

Thanks for the great work!

**Comment by AndersRask** [comment]
I agree. The popup should not without option to close. 
examples:
I want to swap an ice with Thimblerig, but cannot do so because the popup from thimblerig is on top of the ice i want to swap (or just look at).
Also if i forget to fire Thimblerig, the next ice encounter window is forced open on top of the subs that would let me fire the ice swap on thimblerig.

I think also you should consider if the window popping up by itself should be forced -at least if it does, it should also close by it self. I vote for making it either configurable (like the new Auto effects) weather it should open or not, or be manual. Lots of more seasoned players will not use the interface anyway and just minus the credits, so having to close it manually is a bit annoying. :-)

**Comment by NoahTheDuke** [comment]
Thanks for the report! Based on various feedback, moving it back to the previous method of manually opening it seems the best option.

To your point, @AndersRask, about seasoned players not using the interface, once the bugs are worked out, it’s going to be mandatory. 😛
