### ISSUE TITLE
The Cleaners ability does not trigger

### ISSUE THREAD

**Issue by luclabelleis** [mtgred/netrunner#444]
The Cleaners' ability "Whenever you do meat damage, do 1 additional meat damage." is not added to any meat damage done by the corp.

**Comment by nealterrell** [comment]
This one is bizarre. Cleaners does fire... it just makes Scorched Earth trash 4 cards from the Stack and 1 randomly from the hand, and THEN draws some cards into the hand o_O. I have no idea why and will look into it.

Before: hand and Stack
![scorch_before](https://cloud.githubusercontent.com/assets/10083341/8890036/b1a3bf86-32a5-11e5-9fe2-0e67c54ae9a1.PNG)

After: hand and heap
![scorch_after](https://cloud.githubusercontent.com/assets/10083341/8890037/b3558b02-32a5-11e5-9d6b-4bc2d1f02507.PNG)

**Comment by nealterrell** [comment]
So the issue I was seeing seems to be a some kind of memory corruption issue when using IntelliJ's clojure debugger, whereby half the event handlers in the game get replaced with I've Had Worse's trash-effect. In that case, Cleaners' :pre-damage trigger is actually hooked up to I've Had Worse's runner-draw-3 effect, and so too is Kate's identity o_O. When I recompile in to a jar and run from the jar, everything is fine.

Everything also seems fine on Live. I tested this just now and a fifth meat damage was done during a Scorch. Could you better describe the exact situation you saw? You probably know this, but many cards do not benefit from The Cleaners due to the deliberate wording of "deal" vs "take" vs "suffer", including Argus Security and cybernetics.

**Comment by DominicKexel** [comment]
> memory corruption issue when using IntelliJ's clojure debugger, whereby half the event handlers in the game get replaced with I've Had Worse's trash-effect

O_o very strange, indeed
