### ISSUE TITLE
Eavesdrop breaks game

### ISSUE THREAD

**Issue by demoy** [mtgred/netrunner#4450]
After using Eavedrop on a rezzed Mausolus the ice could not be trashed by Hippo and continue option did not work.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by ch1102chiou** [comment]
According to https://github.com/mtgred/netrunner/pull/3708
Eavesdrop add additional subroutine so that Hippo doesn't trash the ice.
BTW, I attempt to reproduce the issue in the unit test but fail to use Eavesdrop with play-from-hand
subroutines doesn't plus one after Eavesdrop played from runner.
Any suggestion to handle this?

`     (core/gain state :corp :credit 100 :click 2)
     (play-from-hand state :corp "Mausolus" "HQ")
     (let [manusolus (get-ice state :hq 0)]
       ;; corp phase
       (core/rez state :corp manusolus)
       (play-from-hand state :corp "Eavesdrop")
       (click-card state :corp (get-ice state :hq 0))
       (println (count (:subroutines manusolus))))
 `

**Comment by Kubik161** [comment]
@NoahTheDuke retested. Mausolus with Eavesdrop interacts correctly with Hippo. This issue should be closed.
