### ISSUE TITLE
Sneakdoor is not counting as a successful run on HQ when Crisium is on HQ

### ISSUE THREAD

**Issue by Keith-thike** [mtgred/netrunner#4719]
The wording of Sneakdoor means that it beats Crisium for things like flipping Earth Station's ID. Currently, that is not happening. the run is completing but successful run effects are not triggering.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
This is actually how it's supposed to go!

**Comment by dinte** [comment]
According to the rules update 1.3, Sneakdoor should enable successful HQ run effect. It was explicitly mentioned in this article, near the bottom: http://nisei.net/article/cr-1-3-update

"The Runner uses Sneakdoor Beta while Crisium Grid is rezzed in the root of HQ. The run becomes successful, so Sneakdoor Beta has the game treat it as a successful run on HQ. Since the run is declared successful while the attacked server isn't HQ, Crisium Grid can't affect it. The Runner will access cards from HQ, and can also then play Emergency Shutdown."

(Apologies if I missed a more recent rules update.)

**Comment by NoahTheDuke** [comment]
HMMMMMMMMMMMM I'll remind the rules team of that article and see what they have to say!

**Comment by NoahTheDuke** [comment]
Welp, the new CR has errata'd Sneakdoor to work differently:

> [click]: Run Archives. If that run would be declared successful, instead change the attacked server to HQ. Then, the run is declared successful.

So I believe that jnet is now correct in the implementation.
