### ISSUE TITLE
Flip Switch not resetting ice traces

### ISSUE THREAD

**Issue by Keith-thike** [mtgred/netrunner#4746]
Used Flip Switch when prompted by the UI, prior to a trace subroutine firing. The trace went ahead as normal, instead of being at 0 strength.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
Do you have more details? I can't reproduce the issue.

**Comment by dinte** [comment]
I just did some quick testing, and it seems to only happen with Tech Trader installed. Must be something to do with the extra triggers? 

For posterity: I only had Tech trader and Flip Switch installed, and was running on a strength 6 Surveyor. No other ice or corp cards rezzed.

**Comment by NoahTheDuke** [comment]
Thank you! I'll try that out!

**Comment by NoahTheDuke** [comment]
I still can't reproduce this. Can you post a screenshot of the bug happening?
<img width="214" alt="image" src="https://user-images.githubusercontent.com/603677/70857259-f1564500-1eb8-11ea-888b-df275ce54250.png">

**Comment by dinte** [comment]
Attached are images of the board state at the start of the run and the log when all is said and done. It happens if I use the "Fire all unbroken subs" button or do them manually, one-by-one.

I just realized Geist's ability fires too, maybe that's the difference?

![Start of run](https://user-images.githubusercontent.com/7846323/70857350-6ddd2980-1ea1-11ea-9228-31adca5bed3f.png)
![log](https://user-images.githubusercontent.com/7846323/70857351-6ddd2980-1ea1-11ea-8880-fe80651080e6.png)

**Comment by NoahTheDuke** [comment]
Thank you! I have figured it out thanks to your help and have a fix prepared.
