### ISSUE TITLE
Hunting Ground Log

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4763]
it just automatically taxes runner without asking to use Hunting Grounds

**Comment by NoahTheDuke** [comment]
You have to click Hunting Grounds during Approach Ice before Encounter Ice for it to work.

**Comment by AndersRask** [comment]
Runner opponent said there was no popup. Also during the runs i sometimes had no "make the runner pay 3" prompt. It seemed broken

**Comment by NoahTheDuke** [comment]
Yeah, with Hunting Grounds, there's not a pop-up, you have to click the card's ability to make it fire and you have to do it before the encounter prompt opens up. Because we moved it to an automated encounter effect, there's no button anymore to make it happen manually. If you need the effect, the runner can manually change their credit count.

**Comment by AndersRask** [comment]
Ok i have found out what is wrong: there is NO information in the console that runner is using it. That would help quite a lot ;-)
That also causes the confusing why sometimes i had the effect and sometimes not.
Could u please add a "Runner is using Hunting Grounds to prevent encounter of X"? :)

**Comment by NoahTheDuke** [comment]
Thank you! That's a great note. I'll add one!
