### ISSUE TITLE
When accessing multiple The Future Perfect from archives the runner only chooses 1 time.

### ISSUE THREAD

**Issue by tekyro** [mtgred/netrunner#484]
Something strange just happened.

Run archives, hit 3 TFP, selected 0 creds for the first, corp selects 0, and I stole all 3 copies!

I still have the menu to choose for the other psi games, but with only 1 choose it was applied to all of them.

Seems like a mayor bug in the edge case of having multiple psis triggering at the same time.

**Comment by nealterrell** [comment]
Not sure what the cause is, but ultimately it won't matter because I will be checking in a new access system where you choose the order of access. I have tested this scenario and it works as expected: you get a list of three Future Perfects to choose from, and after choosing one you get the Psi prompt. After Psi is resolved, you choose the next to access. :)
