### ISSUE TITLE
Breached Dome / Buffer Drive implementation

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#5003]
The trash from breached dome should be simultaneous for the stack and meat damage. 

The text on the card says 'do 1 meat damage and trash the top card of the stack', and the Nisei comprehensive rules (9.8.1) says this type of wording is simultaneous. Because it's simultaneous, then (I think) Buffer Drive should be able to select either of the two cards trashed to go on the bottom of the stack.

The current implementation always does the top card of the stack first, then applies meat damage.

**Comment by infinitenutshell** [comment]
NBKelly, I believe you are referring to the Composite Effects rules from CR 1.3. This timing category no longer exists. Check the Uprising/CR 1.4 Release Notes for an explanation. You can find links to both CR 1.4 itself and the Release Notes at https://nisei.net/article/uprising-release-notes-live

**Comment by infinitenutshell** [comment]
The way Breached Dome should work (and interact with Buffer Drive) is as follows:
1) Players have an opportunity to trigger interrupts to prevent the meat damage. We'll assume it is not prevented; the case where it does get prevented is straightforward.
2) The Corp deals 1 meat damage, trashing a card from the grip. Buffer Drive does not get marked pending yet, since Breached Dome's instruction isn't finished resolving.
3) The Corp trashes the top card of the stack.
4) The Runner can trigger Buffer Drive to put the card trashed that was by meat damage on the bottom of the stack. They can't put the other card on the bottom, because it wasn't part of the first time cards were trashed this turn.
