### ISSUE TITLE
Media Blitz + Ad Blitz + runner scored Rebranding team not working

### ISSUE THREAD

**Issue by sirloathing1209** [mtgred/netrunner#5028]
Ad Blitz + Rebranding Team is working correctly.
When Media Blitz is copying a runner scored Rebranding Team the Ad Blitz fails to allow assets with printed Advertisement to be chosen.

-- Also this is my first bug report. Just wanted to say, you guys rock. Jinteki.net is such a work of art to be up and running.

**Comment by sirloathing1209** [comment]
Media Blitz + Rebranding Team is also not working with Spark ID ability

**Comment by NoahTheDuke** [comment]
Like I said on Slack, this one is going to be a real pain in the ass to fix because of how we handle subtypes and Rebranding Team in particular. A fix _will_ come, I just don't know how soon. I'm so sorry. Maybe if you get it to become extremely popular, I can push it up on the bug priority list, lmao.
