### ISSUE TITLE
Laramy Fisk ability timing

### ISSUE THREAD

**Issue by JDCaron** [mtgred/netrunner#515]
Hey there, just wanted to site a problem with the new Fisk ID and the timing of his ability.  It should be successful run option, force draw option and then access.  Seems like it is successful run, access, force draw at the moment.  

Thanks for the hard work getting things together, the site is extremely helpful!  Keep up the great work.

-Jack

**Comment by aiannacc** [comment]
This is a bug.  It's particularly ugly when the run is on R&D:

Expected behavior: Corp draws the top card of R&D; runner accesses the second card.

Actual behavior: Corp draws the top card AND runner accesses that same card.  If it's an asset, the runner is given the option to trash it, but it ends up in the corp's hand regardless.

**Comment by qmsm** [comment]
Just had the same issue which crashed the game. Corp drew Hostile Takeover while I was given the option to steal it, then BOOM.

**Comment by nealterrell** [comment]
It's going to be a tricky fix for obscure engine reasons.
