### ISSUE TITLE
Clicks should not be assigned until the actual turn begins, not before start of turn actions

### ISSUE THREAD

**Issue by LeonardQuirm** [mtgred/netrunner#5152]
Witnessed the following situation from the Corp player:

- Corp player rezzed and fired a Rashida Jaheem at the start of their turn (I suspect having clicked "Start Turn", then being given some prompts to use Rashida before mandatory draw)
- They then played three clicks worth of actions (installing cards from HQ), having been given the three clicks by the game.
- They then pressed the Mandatory Draw button that had been waiting there since the Rashida and took their Mandatory Draw.

The game framework should ideally only allocate a player's clicks on the actual confirmed "Start Turn" button press, rather than on one that leads to a prompt for "You have start of turn abilities, do them then press actual Start Turn".  In particular, for the Corp it should assign clicks exactly when the Mandatory Draw occurs.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
After researching this, there is no bug. We currently can't and don't disallow using clicks outside of action windows. We expect players to follow the rules of the game in situations where we can't enforce them ourselves (due to engine limitations).

As seen on page 53 of the [Comprehensive Rules](https://nisei.net/files/Comprehensive_Rules.pdf), the Corp gains clicks, then there is a paid ability/rez/score window, then "start of turn" effects fire, and then mandatory draw happens. We merge the paid/rez/score window and "start of turn effects"  by pausing the game so you can manually fire the optional start of turn triggers as you wish, and then any mandatory start of turn effect that haven't been fired will fire when you click "Mandatory Draw", before you actually draw your cards.

It's a bummer that the Corp player messed this up, but we can't do more than this at this time.
