### ISSUE TITLE
Tollbooth autofires etr when runner has 0 credits, even if runner can generate credits elsewhere

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5286]
Runner has 0 credits but a loaded bankroll. Runs R&D, corp rezzes a Tollbooth. Jnet triggers an auto-etr because 'runner can't pay 3 credits' without respecting the approach window.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by lostgeek** [comment]
As discussed in the jnet slack, this is probably an issue with how the "continue" button works. Right now when approaching the unrezzed Tollbooth, the button says "Continue to pass ice". I expected Runners to press this to indicate, that they don't have any action in the priority window. Now the Corp rezzes Tollbooth and presses "continue", the engine thinks that both players have agreed to continue to the next step, and the encounter happens.

We should change the behavior to have the Runner "continue" press to mean that they agree to continue to passing the ice. If the corp rezzes, this should undo the Runners "continue" press, since now the button reads "Continue to encounter ice" and they haven't agreed to this yet.

**Comment by francescopellegrini** [comment]
Might as well close this.
