### ISSUE TITLE
Lag when taking actions

### ISSUE THREAD

**Issue by AlexBoyd** [mtgred/netrunner#5473]
A reoccurring issue that seems far more common since recent updates is that the triggering any sort of action can cause a 1-3 second pause and then still occur. 

This can occur when playing cards, using card abilities, basic actions, or even sending a message via text chat. When this happens there is no feedback that the action has been registered client side, with the exception of sending a message in text chat, where it will still clear the local form when the message is sent, even if it takes 1-3 seconds for the message to show up in the log. When it does happen, all actions are lagged until it clears, so if you instance you type "test" in the text chat, while waiting on the lag from an action, both will be stalled out and resume at the same time. 

This seems to be occurring for people using a range of browsers, but I can personally confirm it happens on latest stable versions of both firefox and chrome. 

I've been able to repro the issue by opening a private game on public jnet between two of my accounts, one using firefox and one using chrome, and then giving either side 100+ clicks, and just spending them to just take credits. When I was testing I'd often see 1-2 cases of the lag hitting over that ~100 actions, though if this is at all related to load on the server it's possible the repro rate varies based on time of day. When it lags, the action is delayed on both browsers and then comes through at the same time on both ends. (IE the credit up sfx is sent more or less at the same time from both browsers). 

Nothing obviously stands out as an actual stall click side in the browser during these events. Mouse over states continue to transition smoothly and no stalls are apparent the browser profiler.

**Comment by AndersRask** [comment]
@NoahTheDuke  I will second this!  The past couple of weeks it has intensified, and right now it is borderline unplayable at times.
It is a weird lag, because as AlexBoyd describes, it is usually when doing actions like resolving cards or doing a run, and sometimes also the chat log, but i have experienced that chat log was fine but the rest was really laggy on both sides.
I heard in Metropole Grid from one in the chat that a resolve was coming for this? Does that have legs? I really hope so, because it is getting very annoying :-O

**Comment by jwarwick** [comment]
This should be addressed on the production server now. More indexes for the db seemed to be the key.
