### ISSUE TITLE
Punitive Counterstrike when runner stole no agendas freezes the interface

### ISSUE THREAD

**Issue by dtelad11** [mtgred/netrunner#550]
Played a game of Hayley versus Jinteki: PE. Jinteki player played Punitive Counterstrike (I have stolen no agendas the previous turn). He put 0c on the trace (total of 5), then I clicked "ok" to put 0c -- but the nothing happened, the Punitive Counterstrike interface remained on and we could not continue the game.

**Comment by queueseven** [comment]
From looking at the code, I guess `[:register :stole-agenda]` is `nil` when Punitive Counterstrike does the `:meat` damage. In the `damage-count` the `+` function then throws a null pointer exception.

While it's easy to change `(-> n` to `(-> (if (nil? n) 0 n)` in the `damage-count` function, I think PC should do simply nothing in the case `[:register :stole-agenda]` is < 0 or `nil`; otherwise, a scored The Cleaners would do 1 meat damage when in fact no agendas where stolen.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.

@queueseven It's indeed the problem.

**Comment by JoelCFC25** [comment]
Fixed at https://github.com/mtgred/netrunner/commit/af39d728fac4908f13b9149a181e8656fffc3c2b

**Comment by queueseven** [comment]
Actually, playing PC is legal when The Cleaners are scored and no agendas stolen: https://twitter.com/RukasuFox/status/634838036178710528

**Comment by JoelCFC25** [comment]
He seems to have been convinced otherwise:  https://twitter.com/ANR_RulesWiki/status/634854445235355648

**Comment by queueseven** [comment]
Good. Makes more sense this way.
