### ISSUE TITLE
options for change to UI on passing ice

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5555]
at the moment, if the first ice is not rezzed, then the first prompt for a jackout window is after you pass that ice
this creates an ambiguous situation for the corp, since they might assume you wish to continue and rez the second ice, when actually you want to jack out
eg you are farming counters
or you want to provoke a rez on the first ice but then not contiune
so as runner to avoid this, you have to 'continue' then hit 'jack-out' really fast before corp reacts to the pass ice
could we have a 'continue then jack-out' option on the first ice if there's a no-rez
there is obviously a 'farm wheel counters' option but that's universally relevant. and the runner exposing the inner ice because you reacted too slow is a big issue.

**Comment by aiannacc** [comment]
I'm surprised this isn't a more discussed issue. IMO, it's the single most important problem with the UI right now.

With most bugs, it's easy enough for the players to remedy the situation manually. But here the problem is irreversible. Once the corp rezzes, that information is irrevocably revealed and there is nothing the players can do to full remedy the situation. It's unfair to the runner to force them to encounter the 2nd ICE, and it's unfair to the corp to allow them to jack out after seeing that ice rezzed.

Even worse, unless the corp knows about this bug, it looks to them like the runner chose to continue and is now just being a jerk.

I'm willing to take a crack at this myself, but I haven't been involved in the project before. Would someone who knows more chime in with an opinion on how hard this would be to fix?

**Comment by aiannacc** [comment]
> at the moment, if the first ice is not rezzed, then the first prompt for a jackout window is after you pass that ice

@tolaasin, are you sure this only happens (a) between the first and second ICE, and (b) when the first ICE isn't rezzed? I'm pretty sure I've seen it in other situations.

**Comment by NoahTheDuke** [comment]
This is going to be fixed when the Nisei rules team releases CR 1.5 and I finish #5844. There will be a part of the run called "Movement phase" that will ask the runner about jacking out and show "Runner is passing the ice" to the corp.
