### ISSUE TITLE
Marjanah not getting discount

### ISSUE THREAD

**Issue by Red-Gordon** [mtgred/netrunner#5736]
The cost to use Marjanah is not changing after the first run of a turn.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by merrickbrown** [comment]
I think this is just a display issue, using the ability costs the correct amount

**Comment by manveruppd** [comment]
![marjanah bug](https://user-images.githubusercontent.com/44246400/113519932-3dd6ff80-9598-11eb-852e-99d5389da798.png)
Nah, definitely costs the full 2/sub, I just came across it myself and hit "pay 10 to fully break" just to check if it was just a display bug or not. It cost me the full 10.

**Comment by francescopellegrini** [comment]
> I think this is just a display issue, using the ability costs the correct amount

This was also my experience: the amount of credits paid was correct, but the message shown was misleading.

**Comment by francescopellegrini** [comment]
Also I can confirm that the match-strength-and-fully-break shortcut makes you pay it in full.

**Comment by francescopellegrini** [comment]
I've investigated a little bit on what's happening here, though I'm definitely no Clojure expert:

- Marjanah leverages the `:break-cost-bonus` function, which [alters the cost being paid later](https://github.com/mtgred/netrunner/blob/efdf48dac826c449304cb76dde38c2677f9a4cc0/src/clj/game/cards/programs.clj#L1659).
- the `break-sub` function instead [requires the cost upfront](https://github.com/mtgred/netrunner/blob/efdf48dac826c449304cb76dde38c2677f9a4cc0/src/clj/game/cards/programs.clj#L1657), so it has no knowledge of the possible discount.
- because of this, `breaker-auto-pump` function also [has no knowledge of the possible discount](https://github.com/mtgred/netrunner/blob/efdf48dac826c449304cb76dde38c2677f9a4cc0/src/clj/game/core/ice.clj#L638).

So, could Marjanah's `break-sub` function be refactored to look more like [Odore's](https://github.com/mtgred/netrunner/blob/efdf48dac826c449304cb76dde38c2677f9a4cc0/src/clj/game/cards/programs.clj#L1810)?

**Comment by NoahTheDuke** [comment]
Looks like we should be using `break-sub-ability-cost` from `game.core.cost-fns` to calculate the cost, as relying strictly on `:break-cost` won't capture the full story, as you've noted. Thanks for doing the research!
