### ISSUE TITLE
Suggestion:  Stopping the Game while the Corp is acting

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#5776]
Not actually sure if this is a suggestion per se, but for some cards in the game, the Runner gets no indication that the Corp is doing something (this may be the case for some Runner cards as well but I'm not sure).  For example, while the Corp is making a decision with Climactic Showdown, the runner can keep doing things.  My intuition is that the game should pause while the Corp chooses, then allow the players to proceed, since this is a required effect.

Similarly, I have noticed that using Spin Doctor doesn't alert the Runner that the Corp is deciding on cards.  For example, firing Spin Doctor after discarding allows the runner to carry on their turn while the Corp chooses.

Not huge deals, but just wondering if it could be implemented that when the Corp is making a decision on these cards, the Runner is required to wait.  Thanks!

**Comment by lechaz79** [comment]
I was going to make exactly the same suggestion.

In my case, I was recently playing Corp and I was inattentive and took an action while my opponent to make a decision. Of course there was a window "Runner is making a decision" and it was my mistake, but I was surprised that Jnet does not block a player from acting when the other a decision from the other player is pending. I think it should do so in order to avoid problems
