### ISSUE TITLE
Red Team dialog stacking

### ISSUE THREAD

**Issue by morganmaddren** [mtgred/netrunner#5863]
Link to bug replay: https://jinteki.net/bug-report/2fa515c3-693f-40a2-888a-25d256fcf95d?b=0

Description:

Clicking on Red Team multiple times creates multiple stacking dialogs.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by cloudrac3r** [comment]
I found this in the issues list but couldn't load that bug report link. I'm not exactly sure if it's the same as yours. I assume it is?

![image](https://user-images.githubusercontent.com/28467304/120102099-93e1b100-c19d-11eb-9a06-70ae455e8252.png)

I was introducing a friend to the game who clicked on Red Team by mistake and got this prompt with no way to close it. If I recall correctly, we first tried clicking the card again to see if it would cancel (it didn't cancel), close-prompt (it didn't close), declared an archives run and then undo-click (the prompt remained), an archives run for real (could not happen because Red Team was using up the screen space for "continue to encouter ice"), reload page (the prompt remained), finally we had to do undo-turn which did remove it.
