### ISSUE TITLE
Jesminder vs. Authenticator interaction is incorrect

### ISSUE THREAD

**Issue by ais523** [mtgred/netrunner#5884]
Link to bug replay: https://jinteki.net/bug-report/7642c89f-991c-498b-a83d-7e7f20d78cd5?b=0

Description:

When Jesminder runs on a server which has a rezzed Authenticator, she is given the option to take 1 tag to bypass it. Doing this causes her to be tagged even if she hasn't taken a tag so far that run.

I'm not sure offhand whether under Netrunner rules, Jesminder can't bypass Authenticator, or whether she can and then avoids the resulting tag. However, the jinteki.net implementation, allowing her to bypass it but causing her to receive the tag anyway, can't be correct.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
Just to add more information:

* Jesminder does not have the option to take the tag to bypass Authenticator
* The runner does not have the option to avoid the Authenticator tag, because then the cost to bypass hasn't been paid - this part seems to be correctly implemented)
* Jesminder cannot be used to bypass the Funhouse encounter effect (this part isn't properly implemented yet)
* The Funhouse encounter effect cannot be avoided with other "avoid tag" cards, like No One Home (this part hasn't been properly implemented yet)
