### ISSUE TITLE
Tranqualizer Not Putting ICE to Sleep

### ISSUE THREAD

**Issue by Chemscribbler** [mtgred/netrunner#6150]
Installed with Simluchip, had Hivemind and Cookbook out. Can see in action on turn 12

https://www.jinteki.net/replay/eb51f3f6-d77e-469a-8054-1c95552353b0

**Comment by cardboardtech** [comment]
This issue is due to being unable to order the Cookbook and Tranq install triggers. Tranq's derez effect only happens when Tranq puts a virus counter on itself on install or turn begins. Watching the replay, Tranq put its virus counter on first which wasn't enough to satisfy the derez then Cookbook added an additional.

If someone gets to this before I do, the fix for this will be to remove the `:silent` key from Cookbook and to make Tranq `:interactive` at least on install.
