### ISSUE TITLE
[BUG] Arella Not Proccing

### ISSUE THREAD

**Issue by jgeorge82** [mtgred/netrunner#6416]
I was playing as corp with a rezzed Arella, he scored an agenda, and I couldn't install anything.  See pic - I scrolled in the game log to the appropriate set of outputs.
![image](https://user-images.githubusercontent.com/10679503/178161971-e29f583b-9ad6-4c19-b008-18921e335ac5.png)

**Comment by NBKelly** [comment]
Hi,

The runner does not score agendas. They steal them. These are functionally different things in the rules for the game.

You can find more information about this [here](https://nisei.net/players/learn-to-play/learn-to-play-runner) (see "what happens when I access a card?") and [here](https://nisei.net/wp-content/uploads/2021/10/NISEI-Comprehensive-Rules-v1.5-clean.pdf#h.nkap26q22ywr)(CR 1.17.3).

Arella Salvatore only functions when the corporation scores an agenda, and this is in line with the rules and grammar of the game.
