### ISSUE TITLE
Newly installed The Twinning incorrectly does not trigger if Patchwork is used earlier in the turn

### ISSUE THREAD

**Issue by wagnonbe** [mtgred/netrunner#6462]
Reproduction steps:

1. Have Patchwork and Mystic Maemi in play, with a credit on Maemi.
2. Install The Twinning from the grip, using Patchwork's credit reduction ability.
3. Play an event using Maemi, as your first spend of a credit from an installed card - The Twinning does not get a counter.

Twinning also gets a counter if the Patchwork ability is used while it is in play, which is not correct.

![image](https://user-images.githubusercontent.com/1815998/180681557-ec11892d-2f43-4f76-b007-55d3faa4894c.png)

It seems very possible that other sources of cost reduction that use the "hosted credit" interface are broken as well if this is a bug.

**Comment by artemmikhalitsin** [comment]
I'm gonna take a stab at this but this might take me some time since I'm not super familiar with Clojure.

I suppose the issue is that patchwork is using :pay-credits, while actually being a cost-reduction effect. Seems this is the only card like that so I'm not convinced that "host credit" cards would be broken.
