### ISSUE TITLE
Net Mercur Doesn't Allow Off Turn Boosting

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#6535]
Net Mercur credits doesn't currently let you use it to boost breakers on the corp turn.  It should allow this as the credits on Net Mercur are usable for anything.  This is relevant as this is desirable to add Twinning counters on the Corp turn.

**Comment by NBKelly** [comment]
Hi, previously mercur was "restricted" (you can just click on it for credits) to runs/prevention abilities/prompts because having a prompt open literally every time you spend a credit when 95% of the time, the answer would be no, was a bit tiresome.

I'll add "it's the corps turn" to the list of mercur interactions, which should cover the twinning interactions 99% of the time.

Does clicking on net mercur to take a credit give you the twinning counter?

**Comment by doomrat** [comment]
I thought it wasn't, but its actually that twinning isn't printing to the log when it triggers.  Not sure if that counts as a bug, but that's why I got confused.

**Comment by NBKelly** [comment]
No worries, this change is still for the better. I added a log message for twinning.
