### ISSUE TITLE
after Franchise City is used the runner cannot steal the agenda

### ISSUE THREAD

**Issue by H4pp7B1rd** [mtgred/netrunner#655]
One or more rezzed Franchise Cities in remote servers. The runner runs on remote and accesses an agenda. Franchise City then gets added to the score area. That leads the servers to change their position. The run arrow then points on the next outer server or to nothing when there is none. Now the game ist stuck. Nothing happens when the runner clicks on "steal [agenda]". They also cannot jack out.

**Comment by JoelCFC25** [comment]
I actually fixed something that wasn't a problem--the real problem is having an unprotected Franchise City on a lower-numbered server than the accessed agenda. When Franchise City teleports itself to the Corp score area the servers collapse down, which wrecks the access and the run. 

I have a working fix for this (doing the long method of `as-agenda` and passing `{:keep-server-alive true}` if we can live with an empty server sitting in the Corp's area. It can be filled with something else later and will then be removed the next time it becomes empty.
