### ISSUE TITLE
Wasn't Able to use SimulChip to Trash Program and Re-install

### ISSUE THREAD

**Issue by tvaduva** [mtgred/netrunner#6650]
Link to bug replay: https://jinteki.net/bug-report/b205e993-3bb1-442f-902f-4ea1d1ba1598?b=0

Description:

Wasn't able to use SimulChip to trash program and re-install. I may be because I didn't have a program in the heap. Should see the game state in the reply right before the /bug command (it's not coming up for me, so I can't tell more details).

**Comment by GordonsBeard** [comment]
This is actually correct rules here. Because there are no programs in the heap, you cannot begin to start resolving the text, as the play would be illegal. There has to already be a program in the heap, even if you're not going to install that program from Simulchip.

Here is a graphic that will lay out what's all happening.
https://cdn.discordapp.com/attachments/715673394762350622/910278623427178526/unknown.png

**Comment by tvaduva** [comment]
You're correct! Found the ruling:

https://netrunnerdb.com/find/?q=simulchip

I misremembered how it changed from Clone Chip functionality and didn't double-checking the rule.

Shucks, I keep messing up the rules in my recent bug reports. Sorry for a waste of your time.
