### ISSUE TITLE
Critical vulnerability in jsonwebtoken library

### ISSUE THREAD

**Issue by astrostl** [mtgred/netrunner#676]
Howdy,

`npm install` yields "npm WARN deprecated jsonwebtoken@0.4.1: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/"

Just saying :)

**Comment by zaroth** [comment]
So thanks to help from @dodgepong, I managed to find and update the right line in `package.json` ( https://github.com/mtgred/netrunner/blob/master/package.json#L19 ) to the latest version (5.7.0). Unfortunately, it seems like API may have changed in the meantime since version 0.4.1. Connections to server.coffee to retrieve app-state don't work properly after the upgrade - which is resulting, among others, in no "Select deck" button in the lobby. Relevant code part:

    (when (= (:user player) user)
                       [:span.fake-link.deck-load
                        {:data-target "#deck-select" :data-toggle "modal"} "Select deck"])

JWT is called 4 times altogether in `server.coffee`, so these calls should be checked for compatibility with current API of the library https://www.npmjs.com/package/jsonwebtoken

**Comment by erbridge** [comment]
Fixed by #2011.
