### ISSUE TITLE
Ansel firing during a run on archives with virtuoso installed incorrectly prevents an agenda steal on the post-run HQ access 

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#6889]
Runner runs archives with virtuoso installed and archives as the marked server.
Ansel is installed on archives and fires the subroutine which prevents cards being trashed or stolen during the access phase.
Virtuoso fires triggering an HQ breach in which an agenda is accessed.
At the moment, the Ansel fire prevents the steal, but the virtuoso access is post-run and Ansels effect is not active in that access phase.

**Comment by artturipi** [comment]
Are you sure this is how it should work? The comprehensive rules has something similar with Noble Path and Dedicated Response Team:

> Example: The Runner plays The Noble Path to make a run in which they prevent all damage.
> The run is successful but the Runner takes a tag during the run. When the run ends, Dedicated
> Response Team’s ability meets its trigger condition at the same time that The Noble Path’s
> effect expires, so the Runner will suffer 2 meat damage.

`The Noble Path: Trash your grip. Make a run. Prevent all damage during this run.`

`Dedicated Response Team: If the Runner is tagged, Dedicated Response Team gains "Whenever a successful run ends, do 2 meat damage."`

The reason I'm not sure Virtuoso and Ansel work the same way, is because the rules say "at the same time" and when that happens, it's active player first (so TNP expires first, then DRT does dmg). With Ansel and Virtuoso it would be Virtuoso first, then Ansel expire.

Here's the relevant card text for Ansel and Virtuoso:

`Ansel 1.0: The Runner cannot steal or trash Corp cards for the remainder of this run.`

`Virtuoso: The first time each turn you make a successful run on your mark, if that server is HQ, access 1 additional card when you breach HQ. Otherwise, breach HQ when the run ends.`

**Comment by francescopellegrini** [comment]
Allegedly fixed by #7415
