### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by wiriamu7** [mtgred/netrunner#6890]
Link to bug replay: https://jinteki.net/bug-report/fd70b971-daf6-44b0-ab40-0a554310f5c7?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

It looks like after the runner (playing Esa Afontiva sp) accesses Nightmare Archives in HQ, zer (sp) chooses to take the core damage and then sabotage, but Nightmare Archives is offered as a choice for me to trash from HQ, when it should be removed from game already, and in the game replay I just trash it, putting it in archives. I only realize the mistake later (after winning a couple of turns later) and then we discuss it briefly in chat

**Comment by NBKelly** [comment]
Hi,

In this case since nightmare archives has not finished resolving, it has not been removed from the game yet. Since the sabotage ability interupts the resolution of nightmare archives until it completes, then nightmare archives in hq is actually a legal target for the sabotage.

Chances are this is actually a legal play, whether or not it should still be removed from the game afterwards is maybe a question you need to ask the rules team.

**Comment by artturipi** [comment]
NRDB page for Nightmare Archives now has the following ruling:

Updated 2023-03-25
If [Esâ Afontov: Eco-Insurrectionist](https://netrunnerdb.com/en/card/33001) accesses [Nightmare Archive](https://netrunnerdb.com/en/card/33097) from HQ and takes 1 core damage, can the Corp choose to discard that copy of [Nightmare Archive](https://netrunnerdb.com/en/card/33097) to the subsequent sabotage effect?

No. Conditional abilities like the one on [Esâ Afontov: Eco-Insurrectionist](https://netrunnerdb.com/en/card/33001) only become pending at the next checkpoint after their trigger condition is met. The sentence “If they do not, do 1 core damage and remove this asset from the game.” is a single instruction, and will resolve completely before the Runner can resolve [Esâ Afontov](https://netrunnerdb.com/en/card/33001)’s ability.

So, it looks like NA should not be a possible target for sabotage in this case.
