### ISSUE TITLE
Sounds suddently not working

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#6921]
I suddently lost all sounds in jinteki!

I have sounds enabled, and when i go spectate a game, i hear the first "join" sound, but all in game sounds are weirdly missing!

I am using MS Edge but have exact same issue with chrome.
I have same issue with my alt account too. Both have lobby and game sound enabled and turned to max.

**Comment by artturipi** [comment]
Happened to me too. Haven't found a fix. The issue seems to be 404 errors for the sound files:

Failed to load resource: the server responded with a status of 404 ()
sound/run-unsuccessful.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/click-advance.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/click-credit.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/agenda-steal.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/click-run.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/click-remove-tag.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/install-runner.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/rez-ice.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/run-successful.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/game-end.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/rez-other.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/virus-purge.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/agenda-score.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/play-instant.ogg:1          Failed to load resource: the server responded with a status of 404 ()
sound/click-card.ogg:1          Failed to load resource: the server responded with a status of 404 ()

So it tries to download from https://jinteki.net/sound/install-corp.ogg

I can see the files in the github project, but not sure where they're supposed to be. It seems that ting.ogg is found (the lobby join sound)

https://jinteki.net/sound/ting.ogg

**Comment by AndersRask** [comment]
@artturipi that is exacty the issue!
@NoahTheDuke i think this might be related to this commit
https://github.com/mtgred/netrunner/commit/533d0885e67edfc60f098c0a4bb1a08bfea170df

I do get 404 when I try to load the files. People might not have observed this because they have the ogg/mp3 files cached.
If i do a request for example in PowerShell, I also get 404 so it seems like all the sound files are no longer there?

 Invoke-WebRequest -UseBasicParsing -Uri "https://jinteki.net/sound/agenda-score.ogg" `
   -WebSession $session `
   -Headers @{
   "authority"="jinteki.net"
     "method"="GET"
     "path"="/sound/agenda-score.ogg"
     "scheme"="https"
     "accept"="*/*"
     "accept-encoding"="gzip, deflate, br"
     "accept-language"="en-US,en;q=0.9"
     "cache-control"="no-cache"
     "pragma"="no-cache"
     "referer"="https://jinteki.net/play"
     "sec-ch-ua"="`"Chromium`";v=`"112`", `"Microsoft Edge`";v=`"112`", `"Not:A-Brand`";v=`"99`""
     "sec-ch-ua-mobile"="?0"
     "sec-ch-ua-platform"="`"Windows`""
     "sec-fetch-dest"="empty"
     "sec-fetch-mode"="cors"
     "sec-fetch-site"="same-origin"
 };

**Comment by NoahTheDuke** [comment]
That's very interesting. Thanks for looking into it! I'll see if i can get them set up correctly.

**Comment by AndersRask** [comment]
Thank you! playing without sounds are almost impossible to me...

**Comment by AndersRask** [comment]
trace from F12 btw
![image](https://user-images.githubusercontent.com/1651150/230899800-ac11b7e2-2b21-4f17-9b2b-15c63fbf3c12.png)

**Comment by AndersRask** [comment]
No rush, but wondered if you got around to re-upload the sound files?
I miss ½ the opponents round when I play without sound, as I am very visual with those kind of things

**Comment by AndersRask** [comment]
@NoahTheDuke i forgot to ask, does sound work for you?

**Comment by Bovrill** [comment]
Hey @NoahTheDuke I know this is probably not a priority but I've loved playing on here for years and It's just not the same without the sounds. To the point that my other players don't play as much lately.

It looks like just misdirected links but I'm sure it's not that simple! Hope it's not too hard to fix sometime soon.

Amazing work in general by the way :)

**Comment by GRichardson90** [comment]
@NoahTheDuke Bumping this as currently still can't any game sounds. I didn't realise how much I loved the sounds until they were gone :( Thanks!

**Comment by AndersRask** [comment]
Agree 100% i literally cannot play tje

**Comment by Bovrill** [comment]
@AndersRask why did you close this? Not fixed for us?

**Comment by AndersRask** [comment]
Was on mobile so closed by accident

**Comment by AndersRask** [comment]
Was on mobile so closed by accident

**Comment by AndersRask** [comment]
Was on mobile so closed by accident

**Comment by AndersRask** [comment]
Looks like it is now fixed so closing!
Thanx to jdeng for solving this <3
