### ISSUE TITLE
Adding NSG/Neo format to the choice

### ISSUE THREAD

**Issue by darrelltmcd** [mtgred/netrunner#6938]
Can there be an additional choice added when making a game.

The new Null Signal Games only format "Neo"

The card pool is limited to only NSG cards. Currently the ban list is being worked out.

But this would be a great choice so we can test lists rather than playing against standard lists.

Thanks

Darrell/LeviPurple

**Comment by DemianThule** [comment]
This sounds great!

**Comment by tblackwe** [comment]
I can take this on. Classic format should also be removed as it has been [abandoned by the creator](https://runthenet.wordpress.com/2019/01/01/the-classic-format-netrunners-final-form/)

@darrelltmcd is there a Neo announcement anywhere? Link to ban list?

**Comment by NoahTheDuke** [comment]
We're not going to add any more unofficial formats to jnet, my apologies.

**Comment by tblackwe** [comment]
I've had a sidebar going with @NoahTheDuke on this issue, and the concern around new formats is around ongoing support and questions of how widely adopted the format is. Things like SOCR and 1.1.1.1 were very complicated to maintain.

I've done some digging into NSG/Neo. NSG is basically 'everything NSG has printed' while Neo adds in a small ban list. There are lists publicized on NRDB for both formats, although the validation does not exist for it. Neo originated in the GLC discord, and regularly has people looking for games. I think there is wide enough adoption of the format to consider this request. Since this is an unofficial format, I will only refer to it as Neo going forward to reduce confusion.

I propose:

- I steward this format for jinteki.net. This would keep the requests/workload off Noah and the other developers.
- I replace Classic in the drop down with Neo. This would prevent the list from growing. Classic development was stopped by TheBigBoy in favor of his work on Reboot.
- I will research adding format maintenance support to the admin console to make this all easier in the future

Some caveats for the Neo community, these come from my time working with Noah on SOCR format many years ago: 
- I'd appreciate it if we could keep ban list changes to a minimum. A couple per release is fine, but multiple every month will be very tedious to support. When you have a change, you can ping me on GLC and create a ticket here for me.
- We can't speed up the releases for Neo changes. I can get the updates into the pipeline, but it will wait for release until other features are going in
- Standard and Neo will eventually be the same card pool. At that time I'd expect the Neo format to be removed from the dropdown. When that happens, the deck statistics will likely go away with it. We don't have a mechanism for changing formats but keeping all the metadata that went with your deck.

**Comment by darrelltmcd** [comment]
Hi Thomas if you are up for this task it would be greatly appreciated by
our player base.

 Hopefully when this is implemented we will see an uptake of the format.

Hopefully we can get a game in soon.

Darrell/LeviPurple

**Comment by francescopellegrini** [comment]
@NoahTheDuke Neo was added to the list of available formats, so I believe this can be closed.
