### ISSUE TITLE
Some issues with spectators

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#695]
`undefinied` joined the game as spectator

![bild 1](https://cloud.githubusercontent.com/assets/3126597/9756986/2c35efe2-56de-11e5-96d0-3ba6967ce36c.png)

In the same game; are there now 3 or 4 spectators?

![bild 2](https://cloud.githubusercontent.com/assets/3126597/9756985/2c334e7c-56de-11e5-8e4b-e841ed14adcb.png)

**Comment by JoelCFC25** [comment]
I've seen multiple reports lately that spectators can trash cards that are in play. That shouldn't be allowable at all, and the more games that get disrupted by trolls this way, the more likely people are going to stop enabling spectators (which would be too bad, as it's otherwise been a very popular feature).

**Comment by zaroth** [comment]
more checks on identity of spectators, as discussed in [this post](http://ilucipher.tumblr.com/post/137632356779/hacking-jintekinet), could help this one

**Comment by zaroth** [comment]
As @dodgepong suggested, these exploits may be caused by one of the security vulnerabilities mentioned in #676 or #677

**Comment by queueseven** [comment]
This happened to me again last week.
