### ISSUE TITLE
When drawing multiple cards, triggering Jinja City Grid, A Teia cannot install just drawn cards

### ISSUE THREAD

**Issue by marc-jones** [mtgred/netrunner#7125]
This is quite a specific interaction with Jinja City Grid in A Teia.

In this example I've drawn 2 cards with Flower Sermon:

![image](https://github.com/mtgred/netrunner/assets/6664299/bfa5969b-0ce3-4a63-8321-245a5eea6b3d)

Jinja City Grid lets me install Anansi, which I do. This install triggers A Teia:

![image](https://github.com/mtgred/netrunner/assets/6664299/9e9b256d-a514-429b-9e42-4245412b2444)

However, I'm unable to install the Rashida which I drew along with the Anansi. I believe, given the current wording of all the cards, that this should be possible.

**Comment by NBKelly** [comment]
The card is not actually in your hand as per the current nisei rules. While drawing cards, they are set aside while effects resolve.

In this case, jinja resolves, installing anansi. This triggers A Teia, which lets you install another card from hand.

Since you haven't finished resolving the draw (a teia is still going during the draw), rashida is not in your hand, and is still set aside.

So in this case, Jinteki.net is correct and installing Rashida is not a legal action.

**Comment by marc-jones** [comment]
Thanks for the explainer, sorry for the issue spam
