### ISSUE TITLE
Infinite Loop with Jua and Arissana

### ISSUE THREAD

**Issue by Alvin-LeeBCC** [mtgred/netrunner#7240]
Link to bug replay: https://jinteki.net/bug-report/75e60b6a-da85-4d44-8bf8-96f34fcc1f1b?b=0

Description:
In this bug, my opponent had a Jua installed in archives and I had multiple programs and a simulchip on the table.  After using Arissana's ability to install Slap Vandal from the hand, the warnings trigger indefinitely about not being able to install my heap programs which blocks the chat console.
![image](https://github.com/mtgred/netrunner/assets/108835055/93788f98-7dad-482d-878d-7769cf29fe9f)

**Comment by thebigunit3000** [comment]
Experienced this bug today.
![image](https://github.com/mtgred/netrunner/assets/16762630/1255d4c3-abb7-48bd-895a-de196d6b2e02)

**Comment by finnbar** [comment]
Can second this, but not as Arissana. Had the exact same situation but with Akiko, and an Ika hosted on the Jua. Screenshot of the game state below:

![image](https://github.com/mtgred/netrunner/assets/4217801/b0ac4502-f3b5-4c3d-8202-337bce0592e3)

I tried to recreate it and found that clicking on Simulchip after encountering Jua causes the messages - I'm unsure if it's the sole cause because I don't remember doing that in the previous game, but it certainly is a cause.

Steps to reproduce:

1. Have Simulchip installed with programs in heap (to avoid no change in game state) and a program installed.
2. Encounter Jua
3. Attempt to use Simulchip
4. oh no
