### ISSUE TITLE
Inversificator prevents Tatu-Bola from swapping

### ISSUE THREAD

**Issue by Syeoryn** [mtgred/netrunner#7284]
### Issue summary
After [Inversificator](https://netrunnerdb.com/en/card/12048) fully breaks [Tatu-Bola](https://netrunnerdb.com/find/?q=tatu-bola) and swaps it with another ice, the Tatu-Bola "When the Runner passes this ice" ability does not fire.

### Expected Behavior
When the runner passes Tatu-Bola after fully breaking it with Inversificator, Tatu-Bola's "When the Runner passes this ice" ability should fire regardless if the ice was swapped with another ice.

### Example
The corp has 2 ice protecting R&D, the outermost is Tatu-Bola.  There is 1 ice in HQ.  The runner is [Kit](https://netrunnerdb.com/en/card/31026), with Inversificator installed.  On click 1, the runner runs R&D, and uses Inversificator to fully break Tatu-Bola.  After passing Tatu-Bola, the runner has the option to swap Tatu-Bola, and swaps it with the second ice (the innermost ice) on R&D.

As is currently implemented, after the Inversificator swap the corp is not given the option to swap Tatu-Bola with an ice in HQ and gain 4c.  However, Tatu-Bola was passed and the corp should be given the option to fire Tatu-Bola's ability.

### Chat Logs
I didn't think to save the replay at the time, but here is the chat log if it's helpful.
In this game, I wasn't given the option to use Tatu-Bola's ability the first time the runner passed it, only the second.
```
uncreative spends  and pays 1  from Prepaid VoicePAD and 1  from their credit pool to play The Maker's Eye.
uncreative approaches Tatu-Bola protecting R&D at position 1.
uncreative encounters Tatu-Bola protecting R&D at position 1.
uncreative uses Rielle "Kit" Peddler: Transhuman to make Tatu-Bola gain Code Gate until the end of the run.
uncreative pays 1  to use Inversificator to break all 1 subroutines on Tatu-Bola.
uncreative has no further action.
uncreative passes Tatu-Bola protecting R&D at position 1.
uncreative uses Inversificator to swap the positions of Tatu-Bola protecting R&D at position 1 and Drafter protecting R&D at position 0.
uncreative will continue the run.
uncreative approaches Tatu-Bola protecting R&D at position 0.
uncreative encounters Tatu-Bola protecting R&D at position 0.
uncreative pays 1  to use Inversificator to break all 1 subroutines on Tatu-Bola.
uncreative has no further action.
uncreative passes Tatu-Bola protecting R&D at position 0.
Tak uses Tatu-Bola to swap Tatu-Bola protecting R&D at position 0 with a piece of ice from HQ and gain 4 .
uncreative approaches R&D.
uncreative breaches R&D.
```

### Other Issues
This may be a broader issue with Inversificator (and other ice swapping abilities?) and "When the Runner passes this ice" abilities.  It is documented in the [rulings on Inversificator](https://netrunnerdb.com/find/?q=inversificator) that:
> If the runner passes a piece of ice after fully breaking it, and uses [Inversificator](https://netrunnerdb.com/en/card/12048) to swap it to another position, can "when the runner passes this ice" abilities on that ice still resolve?
> > Yes.

### Discussion
After I encountered this issue, I brought it up in GLC and got confirmation from CephalopodWizard that the expected behavior is correct.  [Here is the conversation](https://discord.com/channels/425105101451952128/715673394762350622/1208679171077971979) for more details.

**Comment by the-all** [comment]
Maybe related issue: Inversificator doesn't prevent Tatu-Bola from firing, but the wrong ice gets swapped.

**Expected behaviour:** After being swapped with Inversificator, Tatu-Bolas ability should allow it to be swapped with an ice in HQ.

**Observed behaviour:** The ice _after_ Tatu Bola's _original position_ got swapped with the ice in HQ. The logs meanwhile report what should have happened.

**Attached:** screenshots of the behaviour in question.

![Screenshot_20240726_195143](https://github.com/user-attachments/assets/61a67ee3-f77b-4b3c-b209-834ebeb20763)
![Screenshot_20240726_195224](https://github.com/user-attachments/assets/8caa97b5-19d7-4315-8366-982aa89a157a)
![Screenshot_20240726_195243](https://github.com/user-attachments/assets/7bdb694a-9b9f-4d9f-b2e0-f76f992bc4c5)
![Screenshot_20240726_195305](https://github.com/user-attachments/assets/fb6a416f-89e2-4d02-b88c-0a18b4b94152)
