### ISSUE TITLE
The second run effect not trigger on trick shot if Aginfusion boop happens on the initial R&D run. 

### ISSUE THREAD

**Issue by AlexBoyd** [mtgred/netrunner#7328]
My initial thought is that AG boop is under the hood ending the first run but swallowing it's end of run triggers, and starting a fresh one, but the trigger of trick shot isn't transferred over to the new run window. 

To reproduce, have Aginfusion setup with at least 1 remote server and 1 unrezzed ice on R&D. Run R&D with trick shot, and have Ag boop the run to either archives or hq. When that run ends, the runner isn't prompted to run the remote server with trickshot.

**Comment by NBKelly** [comment]
I'm confused by your explanation. Is trick shot giving you a second run event if the run is successful on a server other than R&D, or is it the other way around? Please clarify your issue.

If the run isn't successful on R&D, the runner **should not** get a second run, because neither HQ or Archives are valid targets for trick shot. So a deflected run **should not** give you the successful effect _(like how Diversion of funds doesn't work if you land on R&D)._

**Comment by AlexBoyd** [comment]
Trick is actually worded a in a way that I think it should work regardless of if the first R&D targeted run is a success or not. The second run on trick shot is a second clause independent of making a successful run, only getting the 2 extra credits and the extra accesses. You should even be able to run R&D with tricky shot, and have a failed run, and still have the opportunity to make a second remote run. 

```

Place 4[credit] on this event. You can spend hosted credits during runs.

Run R&D. If successful, place 2[credit] on this event and access 1 additional card when you breach R&D.

When that run ends, you may run a remote server.
```

**Comment by NBKelly** [comment]
OK, now I understand, thanks. I'll look at fixing this within the next week or so.
