### ISSUE TITLE
Leprechaun Self-Hosting

### ISSUE THREAD

**Issue by yang573** [mtgred/netrunner#739]
Today, I accidentally tried to host Leprechaun on itself due to lag. Leprechaun and a hosted card disappeared as a result. They were not in the heap, stack, or grip, and they weren't marked as removed from the game. Should it perform a check to prevent such an occurrence?
![screenshot 1](https://cloud.githubusercontent.com/assets/14100935/9982521/a7284a24-5fad-11e5-9241-9fd8b1c21855.png)

**Comment by JoelCFC25** [comment]
Scheherazade has the same issue. I tried solving it but got stuck and put it on the shelf.

**Comment by nealterrell** [comment]
@JoelCFC25, I think we won't be able to prevent Leprechaun from being clicked, but in the `:effect` you should be able to compare the `:cid` of `target` and the `:cid` of `card` and just not go through with the hosting if they are equal.

**Comment by queueseven** [comment]
Is there a card that can target itself? If no, then we could change the code to simply not allow a card to target itself.

Or change the `host` function to check the :cid's of the host and the card and prevent hosting if they are the same. I wouldn't want to change individual cards, since this is a problem that affects multiple cards.

Also, I believe it would be beneficial to have a general mechanism to indicate if a triggered ability can't be resolved, and then gracefully abort resolving the ability (e.g. without paying the cost).

**Comment by JoelCFC25** [comment]
Same core issue as #381.
