### ISSUE TITLE
Log: Red Team doesn't say that you take hosted credits if successful

### ISSUE THREAD

**Issue by webbedspace** [mtgred/netrunner#7514]
![image](https://github.com/mtgred/netrunner/assets/83939/9696e872-0ea9-4b08-99ce-9b5eb594c936)
Very misleading log message.

**Comment by NBKelly** [comment]
You'll find that's the same with just about every single card in the game that hosts credits. I don't consider it misleading at all.

**Comment by webbedspace** [comment]
There's a different and much better message for when hosted credits are used to pay for costs, so it's hardly "just about every single card".

The issue is that this text is identical to e.g. what Rezeki's text does, despite the ability being very different in what's actually happening to the game state. To me the correct thing it should say is "<runner> takes 3c from Red Team", i.e. what the printed card actually says the ability does.

**Comment by NBKelly** [comment]
If you look through the code or play the game enough, you'll find that (almost) every single card we've templated as "gains [x] credits".

The only exceptions are:
* Janaina
* Marked Accounts
* Smartware distributor

If anything, those cards should be changed for consistency.

So yes, just about every card in the game which hosts credits and has the corporation gain credits is templated that way.

> There's a different and much better message for when hosted credits are used to pay for costs

Yes, because those are actually doing something significantly different mechanically.

**Comment by NBKelly** [comment]
Closed as not planned
