### ISSUE TITLE
Jnet allows you to steal Degree Mill with only DJ Steve installed

### ISSUE THREAD

**Issue by Schr0dinger** [mtgred/netrunner#7823]
Unfortunately I forgot to save the replay (although it should be easy to replicate), I can copy paste the particular click from the log:

spends to make a run on HQ.
will continue the run.
approaches HQ.
uses Steve Cambridge: Master Grifter to add Diesel from the heap to the grip. Corp removes Trick Shot from the game.
breaches HQ.
accesses Degree Mill from HQ.
**shuffles 1 card (DJ Fenris) into the stack to steal Degree Mill from HQ.**
steals Degree Mill and gains 3 agenda points.

**Comment by heyshiloh** [comment]
The issue lies in the designation of the hosted card as installed, but troubleshooting it has been incredibly difficult to build a fix

Somewhere I have engineering notes with the locations in the code that I was spinning on when I was working this out, but i think this is going to end up as its own patched function down the line because of the installed state

**Comment by heyshiloh** [comment]
`game.cards.resources` -> fenris-effect
`game.cards.agendas` -> degree mill -> `:shuffle-installed-to-stack`
`game.cor.costs` -> ShuffleInstalledToDeck -> cost label `:shuffle-installed-to-stack`


I was able to get it to stop allowing the selection by adjusting `payable` method to look for non fake-identity cards with 

```
(let [installed (remove fake-identity? (all-installed state side))]
    (<= 0 (- (count installed) (value cost)))))
```

but if there is another resource installed (i used earthrise), you cant trash earthrise and dj fenris because it seems like `game.core.moving/move` is reporting the wrong number of cards moved

adjusting :choices as 

```
:choices {:max (value cost)
               :all true
               :card (every-pred installed? (not fake-identity?) (if (= :corp side) corp? runner?))}
```

does not help for i think the same reason

**Comment by NBKelly** [comment]
Hmm. Even if the above worked, it's not ideal, because we would have to touch *a lot* of piece of code (you can sell the fake id with aesops for example).
I have a theory on something we can do for an actual fix, I'll give it a try today.

**Comment by heyshiloh** [comment]
Let me know, I have just been troubleshooting to see where the interaction actually occurs. interested to see the outcome here
