### ISSUE TITLE
Runner trashing un-rezzed corp cards seems to trigger their leaves-play effects

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#79]
Ran into this with Mental Health Clinic where making a run and trashing the card while it is un-rezzed (hasn't triggered to increase runner hand size yet) will still reduce the runner's hand size as the card leaves play.  Not sure if this affects any other cards, but none come immediately to mind.

**Comment by mtgred** [comment]
It's the case if the card is the last one in the server. There was a bug the remote server removal code that  is already fixed but not deployed yet.

Unrezzed cards also had their event handling being registered in the process. That's why cards would sometime trigger while unrezzed or twice while rezzed.

The fix will be deployed tomorrow.

**Comment by anathomical** [comment]
Ah.  That makes sense.

**Comment by mtgred** [comment]
I did some testing and checked the code. Actually the bug you reported is totally unrelated. I'm going to fix it this evening. Thanks a lot for detecting and reporting it.

**Comment by mtgred** [comment]
It's fixed now.

**Comment by anathomical** [comment]
Confirmed.
