### ISSUE TITLE
Runner identity base link strength not included in traces

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#81]
The base link strength on the runner's identity is not included in the automated trace calculation.  This is easy to work around by just giving the runner a free credit to fight traces with, but the first time a runner boosts to fight a trace and then loses it (because their identity base link wasn't counted and they lose by 1) is a bit confusing.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It's fixed now and will be deployed with the next server update.

**Comment by mtgred** [comment]
Base link is actually taking into account and it works fine. There was however a bug in the Trace resolution code. The credits used by the runner for the trace was actually taken from the Corp credit pool (issue #80). If the Corp has less credits than the amount chosen by the Runner, the link would be boosted by the number of credits Corp has. My guess is that's why trace might sometime be succussful although link strength is high enough. Issue #80 is now fixed so everything should be fine again.
