### ISSUE TITLE
Architect

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#82]
In the Italian Facebook Group we are discussing about time sequence, activation and rules.
in a situation when you have a remote server with 2 ice, the runner make a run, corp don't rez the first ICE, runner continue, corp rez the 2° ice, witch is Architect, runner do nothing, the corp fire the sub and install an ice on this remote server in the outermost position.
Now, re-reading the rules seems that the Architect subrutine that install the card (ice) force you to re-start the run, but as from the old discussion about "Minelayer", the outermost piece of ice not already approached would be considered starting from the runner position;
I was playing with a friend as a runner and when architect has fired his sub jinteki.net move my "position" in front of the new ICE.
Have I made something wrong or is a bug?

**Comment by anathomical** [comment]
This appears to be a logic bug in the run-tracking code.  Run position during the run seems to be tracked as an offset from the outermost (rather than innermost) piece of ice.  This means that during a run, if new ice is installed (via any means), the runner is pushed one ice further toward the outside of the server.

**Comment by mtgred** [comment]
The run position logic has been changed to handle ICE install during run. It will be deployed with the next server update.
