### ISSUE TITLE
Triggers at the start of the turn are unstackable which causes issues with some cards

### ISSUE THREAD

**Issue by cring002** [mtgred/netrunner#851]
You are unable to chose in which order triggers resolve at the start of the turn. They resolve in a set order (I don't know exactly the order - timestamp?).

This causes issues with cards such as Drug Dealer and The Supplier when used with drip econ such as Daily Casts or Data Folding.

**Comment by nealterrell** [comment]
The order is arbitrary based on index in the events hashtable, which is unpredictable. This issue is more general and a widely reported flaw with our engine. Unfortunately we do not have an ETA on a resolution. Ideally we would come up with something that isn't super tedious; I don't like the idea of selecting a bunch of abilities from a menu _at every single turn start_.

**Comment by cring002** [comment]
ps, what language do you develop in and can I help?

**Comment by JoelCFC25** [comment]
Keep an eye on the discussion in #282--a new system for "when your turn begins" handling is coming soon.
