### ISSUE TITLE
Chopbot 3000 won't chop facedown cards

### ISSUE THREAD

**Issue by Makai** [mtgred/netrunner#866]
Play Apocalypse, or use Apex's ability to install face down cards. 
At the beginning of your turn try to use Chopbot 3000's ability to trash the facedown installed card and the ability will not trigger. 
Still works fine for other installed cards as long as they are not facedown.

**Comment by JoelCFC25** [comment]
So far I can't reproduce this--I click Chop Bot prior to hitting Start Turn and am able to trash facedown cards (while using Apex as the ID).

**Comment by Makai** [comment]
Might be fixed in dev? I'm using Valencia on the live server and have been able to reproduce it after playing Apocalypse and laying down a Chopbot 3000.

**Comment by JoelCFC25** [comment]
I think I see why now--this is probably only happening after the use of Apocalypse, which I haven't yet tried. Apocalypse moves all installed Runner cards to `[:rig :facedown]`, and the `move` function calls `desactivate` when an installed card is headed to this destination--then `desactivate` is in turn dissociating `:installed true` from those cards, which is why they get missed when Chop Bot asks for `all-installed`.

**Comment by Makai** [comment]
Makes sense, thanks for helping pin-point the issue!
