### ISSUE TITLE
Red Herrings Doesn't Protect TFP/R&D

### ISSUE THREAD

**Issue by Skeskrske** [mtgred/netrunner#868]
I managed to steal The Future Perfect with a rezzed Red Herrings installed in the same server, without paying the Herrings fee. The psi game proc'ed on access and my opponent thought the Herrings would protect him, we both bid 0 and so I won it.

Other possible factors: 
TFP was accessed during an R&D dig of multiple cards using Medium.
I also had Turntable installed.

**Comment by JoelCFC25** [comment]
I think I see what the problem is here, and if I'm right, Red Herrings will be equally unable to charge the 5 credits on an agenda accessed in HQ or Archives if RH is installed in the root of those servers. 

Red Herrings checks to see if its own `:zone` matches that of the agenda about to be stolen. But if installed in the root of R&D, Red Herrings' zone is returned as `[:servers :rd :content]`, but the zone of the agenda you hit in R&D comes back as `[:deck]`.
