### ISSUE TITLE
Chronos Protocol trashing Parasite from hand

### ISSUE THREAD

**Issue by spikeyue** [mtgred/netrunner#886]
This has happened to me twice now. The runner hits archives when I have more than one shock. The option comes up for me to trash from hand. Both times it has frozen for me I was attempting to trash a parasite. The menu stays and nothing gets trashed and I am unable to continue the game. Thanks in advance for looking in to this.

**Comment by justinliew** [comment]
I'll check this out.

**Comment by JoelCFC25** [comment]
I think this is because the Runner went ahead and accessed the second Shock! while you were still in the midst of resolving the Chronos Protocol prompts generated from hitting the first one. In cases like this, ask your opponent to hold off--I don't think we have a way right now of forcing them to stop until you've finished your optional abilities.

**Comment by spikeyue** [comment]
Okay thanks for the help. You guys rule.

**Comment by justinliew** [comment]
Can someone close this, just so it's not in the list of open issues, since it's not a valid issue we are going to address? Thanks!

**Comment by eedok** [comment]
Can we have an automated warning? I sometimes forget and then have broken games due to this
