### ISSUE TITLE
Indication of the effect of a trace

### ISSUE THREAD

**Issue by R2devo** [mtgred/netrunner#893]
When a trace is initiated the only indication of which effect it has is the base trace strength, this can be confusing with multiple trace effects of equal strength or in the same timing window. example; Uroboros or Viper on a last click run; a successful run on a server with a rezed Ash while Manhunt is active.

**Comment by GordonsBeard** [comment]
I have an idea on how to get the trace's effect to print out, but I'm wondering if it's a case of showing too much in the logs.

Right now starting a trace will print out:
`[player] users [card] to initiate a trace with strength [total strength] ([base str] + [boost str]).`
![image](https://cloud.githubusercontent.com/assets/4015791/11459184/891bbd7c-9685-11e5-8a93-39c04ea7c1be.png)


I can change it to:
`[player] users [card] to initiate a trace with strength [total strength] ([base str] + [boost str]) ([trace effect]).`
![image](https://cloud.githubusercontent.com/assets/4015791/11459195/efb3144a-9685-11e5-9823-9cb2d307b6be.png)

or

`[player] users [card] to initiate a trace with strength [total strength] ([base str] + [boost str]) (effect: [trace effect]).`
![image](https://cloud.githubusercontent.com/assets/4015791/11459200/1f1a8db2-9686-11e5-9fee-9bfa40769632.png)

It seems this can be a global change, as long as the card has a `:msg:` defined, the `:trace` will pick it up. There are a few exceptions I've found that would require manual editing, as they are missing a `:msg` tag due to how they fire (Troll, Taurus, TMI, etc.). 

And there is also the Security Nexus, which wouldn't be able to list the part about the Runner bypassing.
![image](https://cloud.githubusercontent.com/assets/4015791/11459230/e2d146c4-9686-11e5-90ab-79475aefda6f.png)

**Comment by GordonsBeard** [comment]
I also just noticed/ran into a problem regarding Data Hound, as it has a `:msg`, but this calculated based on the trace strengths; which (at the time of firing the trace) is unknown, causes a bit of barfo: 
![image](https://cloud.githubusercontent.com/assets/4015791/11459346/86b6f6ba-9689-11e5-8cc4-b252951b421a.png)

**Comment by GordonsBeard** [comment]
I've got a PR in place that would fix this. My only question would be, what should show in the cases like Midseason Replacements, or Data Hound, where the trace will have a calculated cost? "Give the Runner X tags"?
