### ISSUE TITLE
Neutralize All Threat access issues

### ISSUE THREAD

**Issue by ericboivin** [mtgred/netrunner#926]
Neutralize All Threats works fine at first. Then as soon as you use Dr Lovegood on it, from now on and every turn after, you access only one card. 

For this part, I'm not too sure exactly of the sequence but I'm playing Adam a lot lately and I've had this happen many times. If later on Neutralize gets trashed, from now you don't access cards anymore on HQ runs.

**Comment by JoelCFC25** [comment]
Thanks for the report. This is happening because I used `card-init ... false` on the assumption that we wouldn't want the card being "switched off" to act as if it's just been installed for the first time when it gets "switched back on". But it looks like most of the likely targets modify things via `:effect`, so they would need the `false` flag removed from `card-init` to resume proper behavior.
