### ISSUE TITLE
Nerve Agent does not get virus counters when access is through card abilities

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#955]
When making runs through sneakdoor beta with Nerve Agent installed (hosted on Djinn), the sneakdoor runs did not add virus counters to Nerve Agent as they should have.

**Comment by JoelCFC25** [comment]
This one is caught up in the hairball of how the system treats steps 4.1 through 4.5 of runs right now. Because there is no way to make code execution "pause" at 4.4 and let "when successful" effects fully resolve before doing 4.5, the only way to make Nerve Agent (and Medium) allow the choice of fewer than all allowable accesses is to give the Runner the ability after the Corp has clicked "No more action" for the final time (and even that shouldn't technically be the final time, see #334). 

I think if I change line 345 of Nerve Agent (the `:req` for `:successful-run`) I can get it to add counters correctly, but it will never be able to let you choose fewer than the max. So, a partial fix but not a full one.

**Comment by JoelCFC25** [comment]
I should add that the new counter adjustment console command is a workaround for this--right before you hit Successful Run while at the doorstep of Archives on your Sneakdoor run, type `/counter n` into chat, where n is the number of Nerve Agent counters you should end up with.
