### ISSUE TITLE
Enhancement request.  Sounds

### ISSUE THREAD

**Issue by AlvazHall** [mtgred/netrunner#968]
Sounds for major events such as:
Playing as Corp
   opponent end turn
   run initiated
   agenda stolen
   ice breaker installed
   current installed
Playing as runner
   opponent end turn
   new remote created
   agenda scored
   ice installed
   current installed

**Comment by nealterrell** [comment]
We'd like it too. It was discussed in #342 but we never heard back from the sound designer. @bozmond... any updates? :D

**Comment by bozmond** [comment]
Hi guys. Yes, it's been playing on my mind I haven't done anything yet. Been pretty busy setting up a new studio here in Melbourne, along with being pretty busy with other projects. I have some time coming up over the holidays so I'll endeavor to get something happening. The new studio I'm setting up is worth a look if you're interested in old synths. http://mess.foundation

**Comment by xanshin** [comment]
good to see this feature is being looked at, it's probably the main thing i miss from OCTGN when using jinteki.

I'd like to add a request for one event:
**-new card is installed in a sever**

how did things go over the holidays @bozmond ?

**Comment by bozmond** [comment]
Hey @xanshin and all,

I'm pretty flat out for the next three weeks. I'm hoping to look at this after that! 

Just a comment overall about the sounds. Personally, I don't think OCTGN sounds are that great, but my impression is people end up liking them because they are synonymous with playing AN online, and after a few hundred plays a little familiarity is bound to set in. 

My thinking about the sounds was that I'd make something distinct, but probably more abstract. Unlike the literal door opening and closing sounds on OCTGN - something clean and clear, more synth based but with a bit of mechanical flavour thrown in.

I'd be keen if anyone has some references to other interface sounds in other games, films or whatever that they think might be a good match for jinteki. It'll help me to figure out what might be a good fit for the community overall.

**Comment by xanshin** [comment]
thanks @bozmond 
If its helpful at all I had a dig around in freesound.org and found some nice tactile mechanical sounds and some abstract type sounds that might suit certain events.

opponent end turn
https://www.freesound.org/people/suzenako/sounds/48670/
https://www.freesound.org/people/juskiddink/sounds/122683/

current installed
https://www.freesound.org/people/E330/sounds/99444/
https://www.freesound.org/people/BMacZero/sounds/94133/

new card in sever
https://www.freesound.org/people/Omar%20Alvarado/sounds/251544/

new remote created
https://www.freesound.org/people/starinatwalls/sounds/331155/

ice installed
https://www.freesound.org/people/Omar%20Alvarado/sounds/251544/

runner card installed 
https://www.freesound.org/people/BMacZero/sounds/94129/

credit increase
https://www.freesound.org/people/LittleRobotSoundFactory/sounds/276102/

net dmg
https://www.freesound.org/people/JoelAudio/sounds/136542/

meat dmg
https://www.freesound.org/people/RSilveira_88/sounds/216277/
https://www.freesound.org/people/thanvannispen/sounds/9572/

brain dmg
https://www.freesound.org/people/Timbre/sounds/112167/
https://www.freesound.org/people/xsub/sounds/28341/

card draw
https://www.freesound.org/people/magedu/sounds/264386/

trash
https://www.freesound.org/people/philberts/sounds/71512/
https://www.freesound.org/people/LukeUPF/sounds/233048/


ETR fires
https://www.freesound.org/people/Isaac200000/sounds/188013/

breaker boost
https://www.freesound.org/people/uEffects/sounds/180974/

ice routine broken
https://www.freesound.org/people/jim-ph/sounds/194799/

jack out
https://www.freesound.org/people/kemitix/sounds/41867/

run initiated
https://www.freesound.org/people/HunteR4708/sounds/256455/
https://www.freesound.org/people/jim-ph/sounds/194799/
https://www.freesound.org/people/fokshtein/sounds/249193/
https://www.freesound.org/people/LG/sounds/30237/
https://www.freesound.org/people/wubitog/sounds/200462/

trace
https://www.freesound.org/people/Franq/sounds/97151/

virus wipe
https://www.freesound.org/people/SpeedY/sounds/3064/
https://www.freesound.org/people/funkymuskrat/sounds/37416/

agenda stolen
https://www.freesound.org/people/HerbertBoland/sounds/114591/
https://www.freesound.org/people/mariiao2/sounds/232814/

agenda scored
https://www.freesound.org/people/Cooltron/sounds/332919/
https://www.freesound.org/people/syseQ/sounds/267528/

**Comment by bozmond** [comment]
Hey All,

Just writing to let you know I've started in on the sound design. It's taken me a while to get to it with other work. Once I have a first round done, I'll post it here. I'm assuming there has been no other movement on sound?

**Comment by zaroth** [comment]
@bozmond have you seen this thread? http://forum.stimhack.com/t/sounds-on-jinteki-net/7231

**Comment by zaroth** [comment]
In short, @bozmond :

- there's my work for april fool's, full of copyrighted SFX and inside jokes. There are a few sounds there that I mixed myself from freely available stuff, these could be reused if needed (Astro-score most notably ;-) )
- @krystman offered to have his "sound guy" work on this, however I haven't heard from him for a while. Are you krystman's sound guy by chance? ;-)
- there's a list prepared for the sounds that we'd like to have in the first iteration, based on OCTGN's list, a bit stripped:

> Access-server.mp3 (run-successful)
> Advance-Card.mp3
> Corp-Start.mp3
> Credit-Click.mp3
> DMG-Brain.mp3
> DMG-Brains.mp3
> DMG-Meat.mp3
> DMG-Net.mp3
> Derez-card.mp3
> Draw-Card.mp3
> Install-Hardware.mp3
> Install-ICE.mp3
> Install-Program.mp3
> Install-Resource.mp3
> Install-Asset/Upgrade.mp3
> Steal-Agenda.mp3
> Play-Transaction.mp3
> Psi-Start.mp3
> Purge-Viruses.mp3
> Rez-corp-card.mp3
> Run-Start.mp3
> Runner-Flatline.mp3
> Runner-Start.mp3
> Score-Agenda.mp3
> Tag-Remove.mp3
> Trace-Start.mp3
> Trash-Corp-card.mp3
> Trash-Opposing_Program.mp3
> Trash-Opposing_Resource.mp3
> Use-ICEbreaker.mp3
> End-the-run.mp3
> Jack-out.mp3

**Comment by bozmond** [comment]
Thanks @zaroth I hadn't caught that thread!

I'll download that pack of yours and check it out. I'm not @krystman's sound guy, but I make a living at as sound designer/artist. Do you also have an extraction of the OCTGN sound set? Only if it's handy - I can probably go looking for them in the OCTGN install myself. Might be nice to have on hand for reference.

I'll grab your list above and the list made by @xanshin and compare the two. I'll stick with the naming scheme from your list as that way it can fold back into OCTGN if people care to use the sounds I make. I'm making custom sound in synthesis and fusing them with some real world stuff as well. I'm making sure that any factional specific sounds are set in the same key/tonality/style so there is a really clear distinction between faction actions. Initially I'm making the corp stuff slick and the runner stuff gritty. Once I have a draft set, I'll post it here and we can move ahead with changes.

In terms of implementation into Jinteki, ideally it would be nice to offer users some sound preferences that are saved with their account details. I would have thought that 4 tiers could be good? 
Something like: 
- no sound
- minimal (clicks, turn start/end, runs, advances)
- moderate (above plus, installs & rez's, maybe a bit more?)
- maximum (all the sounds)

I'm sure others will be able to advise on the most suitable implementation, given whatever other constraints are at play.

**Comment by zaroth** [comment]
For the start, we'll go just with sounds/mute, I think - later we can think about complicating stuff more ;-) Although user pref for turning off every individual sound, saved per browser, not per account, wouldn't be hard to do even with my implementation. (Especially since people may want their browser at work have no sound, while the browser at home has everything on).

You can grab OCTGN's sounds from https://github.com/db0/Android-Netrunner-OCTGN/tree/master/o8g/Sounds or to download them all get the whole repo zipped and then extract them from the `o8g/Sounds/` directory https://github.com/db0/Android-Netrunner-OCTGN/archive/master.zip .

The only overlap we had in sounds was using the infamous Wilhelm Scream - although OCTGN used it as a meat damage sound (I think), while I bound it to trashed executives/bioroids/sysops/connections.

**Comment by zaroth** [comment]
Also there's the licensing issue - I'd like to make sure that all the sounds we create are free to use for jinteki.net and any derivative projects.

**Comment by bozmond** [comment]
OK, Great! Yep, no probs on the CC licensing!

**Comment by bozmond** [comment]
Hey @zaroth 

On the planning front, I've put together a list of potential sound assets [here](https://docs.google.com/spreadsheets/d/1oVy7CvDyzL1Z-EH0fA-zxUiWOGkMARGzsNKtwQCYNrY/edit?usp=sharing). It also contains the current OCTGN assets that I pulled from that repo and the suggested items above from @xanshin and @AlvazHall. The list is a little crazy at 93 items! 😮 I've basically gone full out with the detail so we can pull it back into something more practical.

The tricky part is deciding how deep to burrow into the card subtypes and if it's sonically useful or not? Essentially how granular do we go with the sounds in terms of game actions? Checking out the OCTGN list is what made me think about it. The OCTGN list is a little confusing as some subtypes are covered but not all. I can understand why some are good for a sound prompt (psi games, push your luck) due to their interaction between players. The inclusion of some of the others in the OCTGN set seem a little arbitrary and is often card, rather than subtype specific (Archer, Breaking News). I get the feeling that maybe someone involved with OCTGN really liked rezing Archer, so they made a sound for it! 😄 

In generating this list, I've basically tried to cover ice rez and program install subtypes as knowing what hits the table sonically for this stuff seems useful, and the subtypes are not too diverse. A question I have around this is about programs - is it useful to also have a sound when certain program subtypes interact with ice? 

To give some more info on this question, in terms of building these sounds what I'm going to do is a lot of combination of smaller sounds. For example I have listed separate sounds for "install program", "install program AI" & "break subroutine". My thinking is that the "install program" is a general sound for this purpose, so when you hear "install program AI" it's a combo of 2 sounds "install program" + "AI". This way we could combine "AI" + "break subroutine", so that players know what is interacting during a run?

If this seems like a good way to go, I'd probably change the list so that instead of "install program AI" I'd just list a specific sound for "AI". This way the "AI" sound can be used to make it clear an AI is doing something. Eg...
- "install program" + "AI"
- "AI" + "break subroutine"
- "AI" + "place power counter"
...and so on.

I have left most other subtypes off as it could almost double this list! The exceptions here are psi games and push your luck (as in OCTGN) as there is direct interaction that falls outside of the normal turn/run structure. As I'm not 100% on the current card pool, are their any other card types that use a similar mechanism to the psi game cards/PYL that I should consider?

Aside from this I've also added stuff like currents as their status effect is ongoing so sound could be a good reminder, and distinctions between things like spending credits, spending recurring credits, spending bad pub and so on. I figure hearing this could make the econ structure aspect a little clearer in runs, installs, etc for both players? It'd be nice to have all this detail, but it could be too much as well!

Naturally there is a bunch to figure out in the implementation here regarding how some of these sounds might trigger. Also with the list of potential sound assets currently sitting at 93 items(!) the size of the asset download will be an issue. With this in mind, in the sheet I've added a priority column to try and sort out which sounds are must have and others that are 2nd or possibly 3rd tier. I'm yet to fill it out, but feel free to add something in there. Some things are obvs not a huge deal, like Mythic, Caïssa and so on...

Sorry for the extensive post, but getting this clear will help me as I build the sounds! 😀

**Comment by Krystman** [comment]
Sounds are being worked on. Sound guy may have something next week for us.

**Comment by zaroth** [comment]
[jinteki-sounds-krystman-v1.zip](https://github.com/mtgred/netrunner/files/286548/jinteki-sounds-krystman-v1.zip)

This is first draft of a soundpack from @Krystman . Soon I'll merge the april fool's sounds framework and deploy it on a test server so you can see them in practice.

**Comment by JoelCFC25** [comment]
2 months have gone by--any progress here or motivation to bring it back towards the front burner?

**Comment by bozmond** [comment]
Hi all. Sorry for the slow reply and slow progress on these sounds. I have been working away on them, but when I can find the time! I'm sure you understand that finding hours outside of paid work can be a challenge. Towards the end of the months my schedule frees up, so I'll aim to get a basic set of sounds delivered by early September.

**Comment by zaroth** [comment]
Sounds delivered by @Krystman are currently up on the test server: http://jinteki.zaroth.net , attached is the soundpack with appropriately renamed files: 
[jinteki-sounds-krystman-v1.tar.gz](https://github.com/mtgred/netrunner/files/524288/jinteki-sounds-krystman-v1.tar.gz)

**Comment by mpeachey1** [comment]
Comments in the thread are fairly out of date.  Is there a more current thread on the ANR sounds on jinteki.net?

**Comment by jbrz** [comment]
my $0.02: Some of the sounds were rather loud, and inability to customize which sounds are on or w/e means I'd tend to just leave them all off.

**Comment by Macduffle** [comment]
Love the sounds! Only problem is that they might be a bit to loud.

**Comment by wombat929** [comment]
I like the sounds! Keep up the good work.

**Comment by jclopes** [comment]
The current sounds are too disturbing. They need to be less intrusive but still give a hint of what is going on.

Also too many different sounds that makes it confusing. The main actions requiring sound are the one that tips you to take a response action:
 - player leave/join game
 - start of your turn
 - make run
 - break sub
 - (use click)

That's pretty much the actions you need to announce when playing on the flesh.
Sure there are people that want every little thing to make sound ... but make it optional.

Sorry if it sounds like I'm complaining. That is not at all my mood. I really want to use this feature.

**Comment by nealterrell** [comment]
Thanks for the feedback @jclopes. I agree that those sounds in particular need to stand out above the rest. We don't have plans to enable sounds on a case by case basis, but in theory it's something we could add.

**Comment by jbrz** [comment]
Think I agree with all of jclopes's points.  Also still not convinced I would use sounds unless I could case-by-case them.

Just FWIW

**Comment by mvelic** [comment]
Appreciate the hard work going into the sounds, but I've turned them off. Just not my sort of thing for ANR. I did find the ding-dong (when someone joined your game in lobby) useful, since sometimes I'd go to another screen. Combine that with a "it's your turn sound" and I'd be golden.

**Comment by erbridge** [comment]
We could make two classes of sounds: high priority sounds and low priority sounds, and allow users to enable / disable them separately.
