### ISSUE TITLE
Hosted chameleon does not return to hand

### ISSUE THREAD

**Issue by cwoac** [mtgred/netrunner#977]
I figure this must be a well known bug, but I can't obviously find an actual issue raised for it.

If you host chameleon (e.g. on dino or scherazade), then it fails to return to your grip at the end of the turn and must be dragged manually.

**Comment by JoelCFC25** [comment]
For some reason I can't duplicate this one, either. Host Chameleon on Scheherazade and it returns to the Grip normally at turn's end. Has it been awhile since you visited and have you done a forced refresh in your browser? Hold the Shift key down while hitting the browser's reload button--but NOT while in an ongoing game. 

We do have a documented problem with Chameleon getting duplicated at the end of turn when hosted on London Library (#325, #409).

**Comment by cwoac** [comment]
So, just refreshed, checked and it still happens. Running Chrome 47.0.2526.73 m (if that matters). 

It's worth noting that if you install chameleon directly onto scherezade/dino, it works fine. It's only if I host it post install (possibly only after bringing it off personal workshop) does this happen.

**Comment by JoelCFC25** [comment]
OK, that aspect of it was not mentioned at first. I'll investigate.
