### ISSUE TITLE
Combo Surfer + PaintBrush doesn't work

### ISSUE THREAD

**Issue by ashton** [mtgred/netrunner#994]
Trying to use the combo with Paintbrush + Surfer and, it didn't work.

how to reproduce:
- Runner makes a run
- Corp rezzes first piece of ice
- Runner activates Paintbrush spending a click to give the current ice being encountered barrier type
- Runner should be able to pay 2 and use surfer on that ice to swap it's position, but surfer doesn't trigger.

**Comment by JoelCFC25** [comment]
I'll check this out, but note that this play is quite illegal! You can't spend clicks on card abilities in the middle of a run. You have to use Paintbrush on a piece of rezzed ice, _then_ initiate a run.

**Comment by nealterrell** [comment]
This actually makes sense why it doesn't work. When you start the run, all the ice in the server is copied into `[:run :ices]`. If Paintbrush is activated mid-run, it will update the ice in `@state [:corp :servers ... :ices]`, but not the copy of that ice in `[:run :ices]`, which is what Surfer will look at when looking for barrier subtype. This isn't a big problem for Surfer because Joel is right, you can't spend clicks during a run except when otherwise noted (Bioroid ice, Turing). However, it would be a problem for one specific interaction I can think of: using Firmware Updates counter to advance a Changeling (or other Morph ice) as the runner approaches the ice. We don't currently track Morph ice subtypes, but if we did we would see the issue I just described.

**Comment by JoelCFC25** [comment]
I am almost done with the Morph ice--the Firmware Updates thing is the last part I need to handle.
